KittyCAD/modeling-app

src/lib/exportSave.ts

save actual file contents

---

src/hooks/useSetupEngineManager.ts

re-execute when we remount the app

---

src/components/Stream.tsx

disable pip for firefox

---

src/lang/std/engineConnection.ts
src/useStore.ts

Type Error: Type error engineConnection.ts

---

package.json
src/hooks/useAppMode.ts
src/wasm-lib/Cargo.lock
src/wasm-lib/Cargo.toml
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/sketch.rs
src/wasm-lib/tests/modify/main.rs
yarn.lock

Hide planes

---

src/lang/KclSinglton.tsx
src/lang/std/engineConnection.ts

wait to execute code until planes are ready

---

src/wasm-lib/kcl/src/std/sketch.rs

Half the fix.  Merge this whenever.

Fix holes in jess's branch

---

src/components/ModelingMachineProvider.tsx
src/components/TextEditor.tsx
src/hooks/useEngineConnectionSubscriptions.ts
src/lang/std/engineConnection.ts
src/useStore.ts

Resolves #834 (last bullet point)
Something I still don't love about this but not directly related (being in edit mode has issues if there's a re-execution etc, but they are for more fixes to come along soon)
I created #868 in the process, just something to be aware of.

fix vertex selection

---

src/Router.tsx
src/components/WasmErrBanner.tsx
src/lang/KclSinglton.tsx

add wasm error banner

---

src/useStore.ts

unused vars

---

src/lang/wasm.ts

Add https://tauri.localhost for Windows

---

.github/workflows/ci.yml
wdio.conf.js

This is what happens when I code before my morning matcha
Part of #987

Fix silly mistakes in previous CI.yml PRs

---

src/lang/KclSinglton.tsx

compare formated asts before execute

---

.github/workflows/ci.yml
src-tauri/tauri.conf.json
src-tauri/tauri.noupdater.json
src-tauri/tauri.release.conf.json

Fixes #982 plus slight reorg, see comments

Build release & sign only on merge / release / release PR

---

src/lang/KclSinglton.tsx

clear errors on good parse

---

src/hooks/useEngineConnectionSubscriptions.ts
src/lib/selections.ts

Follow up to #1013, and partially fixes #1016

selections fix follow up

---

src/lang/KclSinglton.tsx

Really dumb bug that mean that react wasn't getting updated programMemory etc so the debug panels were broken.
Thanks @paultag.

fix variables panel and others

---

.github/workflows/ci.yml
src-tauri/tauri.macos.conf.json
src-tauri/tauri.release.conf.json
src-tauri/tauri.windows.conf.json

Fixes #1015
Was due to #991, the updater url changed location. Also cleaned up whitespace in tauri conf json files

Fix auto-version in nightly builds

---

README.md
src/wasm-lib/Cargo.toml
src/wasm-lib/derive-docs/Cargo.toml
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/fuzz/Cargo.toml

Describe Rust version for devs

---

src/Toolbar.tsx

don't have to scroll post buttons you can't use.

Sort constraint buttons

---

src/wasm-lib/Cargo.lock
src/wasm-lib/Cargo.toml
src/wasm-lib/execution-plan/Cargo.toml
src/wasm-lib/execution-plan/src/lib.rs
src/wasm-lib/execution-plan/src/tests.rs
src/wasm-lib/kcl/src/parser.rs
src/wasm-lib/kcl/src/parser/math.rs
src/wasm-lib/kcl/src/std/segment.rs

Very first simple step for https://github.com/KittyCAD/modeling-app/issues/993
This implements the basic execution plan "virtual machine", although right now it only does arithmetic, no API calls. It also does not compile KCL ASTs into execution plans yet.

Start execution plans

---

.github/workflows/ci.yml
e2e/tauri/specs/auth.e2e.ts
src-tauri/tauri.conf.json

Tauri tests on dev when the CI's BUILD_RELEASE is false

---

e2e/playwright/flow-tests.spec.ts
src/App.tsx
src/components/CollapsiblePanel.tsx

Resolves #1208, I really didn't expect it to be that easy.
https://github.com/KittyCAD/modeling-app/assets/23481541/78ce9e6a-90ba-44a8-95f9-8580e03af4bf

Make stream clickable when panes are collapsed

---

.github/workflows/ci.yml

Reverts KittyCAD/modeling-app#1213

Revert "Bump actions/download-artifact from 3 to 4"

---

.github/workflows/ci.yml
.github/workflows/playwright.yml

Reverts KittyCAD/modeling-app#1214

Revert "Bump actions/upload-artifact from 3 to 4"

---

.env.development
.env.production

So that the web app auth works again

Migrate env variables to zoo.dev

---

.github/workflows/ci.yml

Stop the upload of broken Linux builds

---

src/wasm-lib/tests/executor/main.rs

Execution plans will eventually fix this bug.

Ignore test that stack overflows

---

src/components/Stream.tsx

@mlfarrell and had a chat and this ended up being a really easy fix @franknoirot 🙌

throttle scroll zoom

---

src/wasm-lib/Cargo.lock
src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/native_functions.rs
src/wasm-lib/grackle/src/tests.rs

Support compiling logical not and sign-flipping negation.

Grackle: unary operations

---

src/wasm-lib/grackle/src/kcl_value_group.rs
src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/tests.rs

Oops, I forgot I hadn't implemented this...

Grackle: compile KCL bools to EP bools

---

src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/tests.rs

I suggest reviewing commit-by-commit.

Grackle: Allow arrays to be args to functions

---

e2e/tauri/specs/auth.e2e.ts

Fix tauri tests in build-test-apps

---

e2e/playwright/snapshot-tests.spec.ts
src/clientSideScene/clientSideScene.ts
src/components/Toolbar/SetAbsDistance.tsx
src/components/Toolbar/setAngleLength.tsx
src/lang/std/sketchcombos.ts
src/lang/wasm.ts
src/useStore.ts
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/src/lib.rs

this removed PI since we have the std lib fn `pi()`

Fix default memory so its always initialized in one place -> rust

---

e2e/playwright/flow-tests.spec.ts
src/clientSideScene/setup.tsx
src/lang/std/engineConnection.ts

Should have been done anyway, but was need after some of the selection changes made in https://github.com/KittyCAD/modeling-app/pull/1362

don't put scene commands in the artifact map

---

.github/workflows/ci.yml

CI for macOS on M1 runners

---

package.json
src-tauri/tauri.conf.json

Mostly bug fixes.
- [Enable/disable "start sketch", "edit sketch" and "extrude" appropriately](https://github.com/KittyCAD/modeling-app/pull/1449)
- [draft line snapshots](https://github.com/KittyCAD/modeling-app/pull/1445)
- [mouse listners should be reset outside of sketch ](https://github.com/KittyCAD/modeling-app/pull/1442)
- [fix flacky auto complete test](https://github.com/KittyCAD/modeling-app/pull/1443)
- [jsxify svgs](https://github.com/KittyCAD/modeling-app/pull/1441)
- [cancel execution on file change](https://github.com/KittyCAD/modeling-app/pull/1440)
- [try arm latest](https://github.com/KittyCAD/modeling-app/pull/1439)

Cut release v0.15.1

---

src/clientSideScene/sceneInfra.ts

https://github.com/KittyCAD/modeling-app/assets/29681384/4aaa579b-3532-4cc0-8fe9-61d046960e08

move camera with units

---

docs/kcl/std.json
docs/kcl/std.md
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/extrude.rs
src/wasm-lib/kcl/src/std/sketch.rs
src/wasm-lib/tests/executor/main.rs

closes https://github.com/KittyCAD/modeling-app/issues/1494

Sketch on arc error

---

src/components/TextEditor.tsx

Resolves #1504 and was way easier than I thought when I tried it a while back!
https://github.com/KittyCAD/modeling-app/assets/23481541/5b29e54b-ef0a-47ca-b3aa-00212c234677

Honor mod+z and mod+shift+z even with editor not in focus

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/token/tokeniser.rs

adds a bunch more tests and closes https://github.com/KittyCAD/modeling-app/issues/1532 @greg-kcio you will be happy i hope :)
also closes #1533

fix recast

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs

fixes https://github.com/KittyCAD/modeling-app/issues/1529

fix trailing comma

---

src/wasm-lib/grackle/src/native_functions/sketch/stdlib_functions.rs
src/wasm-lib/grackle/src/tests.rs
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/lsp/kcl/mod.rs

added some rust tests for it 
fixes https://github.com/KittyCAD/modeling-app/issues/1482
@Irev-Dev idk if theres a good way to add a playwright test
I will say if the lsp server has not updated the file this might not work, so it can be racy but its better than nothing

Fix autocomplete in comment

---

.github/workflows/cargo-test.yml
.github/workflows/vector.toml

this should be reusable in any repo after this

Vector for tracking cargo tests

---

src/clientSideScene/sceneEntities.ts
src/clientSideScene/segments.ts
src/lib/selections.ts

https://github.com/KittyCAD/modeling-app/assets/29681384/215073a0-183f-461b-b5e1-395faad907db

show selected color for start selected at

---

e2e/playwright/flow-tests.spec.ts

Here's what the test looks like headed
https://github.com/KittyCAD/modeling-app/assets/29681384/50461ae3-5547-4021-b77d-f545820a2d04
Testing we can drag each of the segment handle types, expecting that it modifies the code.

add test: Can edit segments by dragging their handles

---

src/clientSideScene/sceneEntities.ts
src/clientSideScene/sceneInfra.ts
src/machines/modelingMachine.ts

Changing `raycastRing` to return an array of intersects is the most important change, but a clean up was overdue as well.

Refactor mouse event args

---

README.md

Push same crap to the read me to test if pushes to main were blocked or not. the gh settings are a little unclear.

undo test stuff

---

package.json
src-tauri/tauri.conf.json

```
- Bump kittycad to 0.0.55
```

Cut release v0.15.6

---

docs/kcl/std.json
docs/kcl/std.md
src/wasm-lib/kcl/src/std/math.rs
src/wasm-lib/kcl/src/std/mod.rs

closes https://github.com/KittyCAD/modeling-app/issues/1703

add to_degrees/to_radians fns

---

src/lib/exampleKcl.ts

Starting example wasn't using fillets and had stale structure. Using the mounting plate example instead since it shows off fillets and holes

update starting example 

---

src/wasm-lib/kcl/src/ast/types.rs

closes https://github.com/KittyCAD/modeling-app/issues/1745

fix recast bug

---

src/lang/std/sketch.ts

tag changes followup

---

package.json
yarn.lock

This reverts commit 3e4ce44dc94ac6669d4dc810fc1a52ad0ab93e8b.

Revert "Bump @lezer/javascript from 1.4.9 to 1.4.13 (#1812)"

---

src/wasm-lib/Cargo.lock
src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/tests.rs

Insert KCL source ranges into the KCVM instructions.

Grackle: integrate source ranges

---

src-tauri/tauri.conf.json

This completes the migration to new domains

Add *.zoo.dev origins to Tauri HTTP scopes

---

src/components/CodeMenu.tsx

fixes https://github.com/KittyCAD/website/issues/1736

change KCL Samples link

---

src/clientSideScene/sceneEntities.ts

remove function that's only used once

---

docs/kcl/getNextAdjacentEdge.md
docs/kcl/getPreviousAdjacentEdge.md
docs/kcl/std.json
src/wasm-lib/kcl/src/std/fillet.rs
src/wasm-lib/tests/executor/main.rs

fixes https://github.com/KittyCAD/modeling-app/issues/1935

swap prev and next logic

---

package.json
src-tauri/tauri.conf.json

Here's a changelog for the release:
* [Add helix function to KCL by @jessfraz](https://github.com/KittyCAD/modeling-app/pull/1892)
* [Cleaner clear all implementation by @Irev-Dev](https://github.com/KittyCAD/modeling-app/pull/1908)
* [start of revolve by @jessfraz](https://github.com/KittyCAD/modeling-app/pull/1897)
* [Generate images for examples in derive docs by @jessfraz](https://github.com/KittyCAD/modeling-app/pull/1916)
* [Filter selections by type by @Irev-Dev](https://github.com/KittyCAD/modeling-app/pull/1951)
* Various KCL language bug fixes
* Various testing improvements
* Many bumped software dependencies
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.17.0...v0.17.1

Cut release v0.17.1

---

src/lib/exampleKcl.ts
src/routes/Onboarding/Export.tsx
src/routes/Onboarding/InteractiveNumbers.tsx
src/routes/Onboarding/Introduction.tsx
src/routes/Onboarding/ParametricModeling.tsx
src/routes/Onboarding/Sketching.tsx

- Fixes https://github.com/KittyCAD/modeling-app/issues/1918
- Fixes https://github.com/KittyCAD/modeling-app/issues/1790
- Fixes https://github.com/KittyCAD/modeling-app/issues/1789
- Other feedback from @JBEmbedded on onboarding

Onboarding updates

---

e2e/playwright/flow-tests.spec.ts
src/components/TextEditor.tsx

fixes https://github.com/KittyCAD/modeling-app/issues/2097
it just wont re-render while you tab thru the snippets, which I think is fair, if it becomes a problem or leads people to confusion we can find a different solution but idk who just hanging out in snippets

try hasNextSnippet

---

src/lang/std/engineConnection.ts

in preparation for https://github.com/KittyCAD/modeling-api/pull/313

add headers type

---

e2e/playwright/flow-tests.spec.ts
e2e/playwright/snapshot-tests.spec.ts

the only one that still has inner loops is export but im fine w that until it breaks

cleanup other tests

---

e2e/playwright/flow-tests.spec.ts

found a diffferent way to trigger the error while engine works out the problem
we still ahve the rust test of the segfault so dont worry

turn back on test

---

package.json
src-tauri/tauri.conf.json

Suggested changelog from tool (I'll edit this down while CI runs)
* Massive app performance improvements by Jess
* Rectangle sketch tool by Frank and Kurt
* Code editor improvements by Jess: autocompletion snippets, find extension, and more
* New panes sidebar by Frank
* New setting to toggle edge highlights
* Migrate to Tauri V2 by Pierre, Paul and Adam
* Allow nightly builds of Modeling App to be installed alongside the standard app by Pierre, Paul and Adam
* New help menu in the bottom right by Frank
* Lots of tests by Kurt, Jess and Frank
* New custom updater (what you're reading this in!) by Pierre
* New app icon by Frank
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.17.3...v0.18.0

Cut release v0.18.0

---

make-release.sh
package.json
src-tauri/tauri.conf.json

* Project global origin for sketches and use engine animations (#2113)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.18.0...v0.18.1

Cut release v0.18.1

---

.github/workflows/build-and-store-wasm.yml

Store wasm pkg as an artifact for each push to main

build and store wasm

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/capabilities/desktop.json
src-tauri/src/main.rs
src-tauri/src/state.rs
src-tauri/tauri.conf.json
src/Router.tsx
src/components/FileMachineProvider.tsx
src/lib/routeLoaders.ts
src/lib/tauri.ts
src/wasm-lib/Cargo.lock
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/settings/types/file.rs
src/wasm-lib/kcl/src/settings/types/mod.rs
src/wasm-lib/kcl/src/settings/utils.rs

@pierremtb this fixes the dir bug and does a bunch of other stuff i was already working on
closes https://github.com/KittyCAD/modeling-app/issues/2237
start of https://github.com/KittyCAD/modeling-app/issues/858

Project state improvements

---

package.json
src-tauri/tauri.conf.json

* Fix project directory through state improvements by Jess
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.19.0...v0.19.1

Cut release v0.19.1

---

package.json
src-tauri/tauri.conf.json

* Bugfix for settings file reading and migration by Jess
* A few small dev experience upgrades 
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.19.1...v0.19.2

Cut release v0.19.2

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
src/Router.tsx
src/lang/wasm.ts
src/lib/paths.ts
src/lib/routeLoaders.ts
src/lib/settings/settingsUtils.ts
src/lib/tauri.ts
src/wasm-lib/Cargo.lock
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/settings/types/file.rs
src/wasm-lib/src/wasm.rs

part of https://github.com/KittyCAD/modeling-app/issues/858

Better rust parsing of route uris for files

---

src/routes/Onboarding/CodeEditor.tsx
src/routes/Onboarding/InteractiveNumbers.tsx
src/routes/Onboarding/ParametricModeling.tsx

stop gap fix for https://github.com/KittyCAD/modeling-app/issues/2258

get rid of code pane shit

---

.github/workflows/ci.yml
.gitignore
public/.well-known/apple-app-site-association
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/Info.plist
src-tauri/capabilities/desktop.json
src-tauri/entitlements/Zoo Modeling App.entitlements
src-tauri/src/main.rs
src-tauri/tauri.conf.json
src/lang/std/engineConnection.ts

part of https://github.com/KittyCAD/modeling-app/issues/858
part of https://github.com/KittyCAD/modeling-app/issues/581

Deep links and app store pushing

---

e2e/playwright/flow-tests.spec.ts
src-tauri/Cargo.lock
src-tauri/src/main.rs
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/lsp/tests.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs
src/wasm-lib/kcl/src/settings/types/mod.rs
src/wasm-lib/kcl/src/settings/utils.rs
src/wasm-lib/kcl/src/token.rs
src/wasm-lib/kcl/src/token/tokeniser.rs

next steps will be a hover tooltip, making a specific sheband splainer page on the website to link people to as well (https://github.com/KittyCAD/website/pull/1825)

parse the shebang and make it work with recast

---

package.json
src-tauri/tauri.conf.json

need https://github.com/KittyCAD/modeling-app/pull/2318 merged first

Cut release v0.20.2

---

e2e/playwright/flow-tests.spec.ts
src/hooks/useEngineConnectionSubscriptions.ts
src/lang/std/engineConnection.ts

What you had seemed fine to me @paultag, I don't see why moving the callback up into the other class would be a problem so I've put @lf94 as a reviewer too.
Added a playw test for this too (tests hover which uses the unreliable channel).
Resolves https://github.com/KittyCAD/modeling-app/issues/2326

fix unreliable channel

---

package.json
src-tauri/tauri.conf.json

* Sketch light mode by Frank
* Clean up and fixes by Kurt
* Remove backdrop highlight in onboarding by Frank
* Move the command bar out to the right in the AppHeader by Frank
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.20.2...v0.21.0

Cut release v0.21.0

---

package.json
src-tauri/tauri.conf.json

* Fix Format button by Jess
* Other minor improvements by Jess and Frank
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.21.0...v0.21.1

Cut release v0.21.1

---

package.json
src-tauri/tauri.conf.json

* Make edge helpers + more mock safe (#2357)
* Updating KCL examples on docs (#2355)
* Fix settings overflow by setting grid-template-rows (#2348)
* Ensure that onboarding buttons are visible, even on short viewports (#2324)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.21.1...v0.21.2

Cut release v0.21.2

---

src/wasm-lib/Cargo.lock
src/wasm-lib/derive-docs/Cargo.toml
src/wasm-lib/derive-docs/src/lib.rs
src/wasm-lib/derive-docs/tests/array.gen
src/wasm-lib/derive-docs/tests/box.gen
src/wasm-lib/derive-docs/tests/doc_comment_with_code.gen
src/wasm-lib/derive-docs/tests/doc_comment_with_code_on_ignored_function.gen
src/wasm-lib/derive-docs/tests/lineTo.gen
src/wasm-lib/derive-docs/tests/min.gen
src/wasm-lib/derive-docs/tests/option.gen
src/wasm-lib/derive-docs/tests/option_input_format.gen
src/wasm-lib/derive-docs/tests/return_vec_box_sketch_group.gen
src/wasm-lib/derive-docs/tests/return_vec_sketch_group.gen
src/wasm-lib/derive-docs/tests/show.gen
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/import.rs
src/wasm-lib/kcl/src/std/patterns.rs

finishes up https://github.com/KittyCAD/modeling-app/pull/2357

Mock mode tests, ensure mock mode always works for std fns

---

package.json
src-tauri/tauri.conf.json

* Bug fixes for sketching when model contains fillets and patterns, with tests (#2359)
* Filter hidden directories from home page (#2349)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.21.2...v0.21.3

Cut release v0.21.3

---

package.json
src-tauri/tauri.conf.json

* Default extrusion length is now `5` (#2351)
* UI bug fixes (#2372, #2375)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.21.3...v0.21.4

Cut release v0.21.4

---

src/components/ModelingSidebar/ModelingPanes/MemoryPane.test.tsx
src/components/ModelingSidebar/ModelingPanes/MemoryPane.tsx

fix function variable panel issue

---

package.json
src-tauri/tauri.conf.json

* Sort keys alphabetically in the Variables/Memory panel (#2417)
* remove edit-mode prep (#2370)
* Disable home logo link in the browser app (#2371)
* Fix code editor user input in older version of Safari (#2350)
* Sketch dies on exit XY sketch (#2397)
* Double-clicking a model file (obj, stl, etc) will auto generate a file with an import statement and open it (#2400)
* Missed a file (#2399)
* Make import samples run (#2398)
* Fix function variable panel issue (#2392)
* Fix max std lib (#2391)
* Add "copy to clipboard" button to Variables pane (#2388)

Cut release v0.21.5

---

e2e/playwright/flow-tests.spec.ts
src/App.tsx
src/components/CommandBar/CommandBar.tsx
src/components/FileTree.tsx
src/components/ModelingMachineProvider.tsx
src/components/ModelingSidebar/ModelingPanes/KclEditorPane.tsx
src/lang/codeManager.ts
src/lib/hotkeyWrapper.ts

Wrapper for keybindings (codemirror and app)

---

src/wasm-lib/kcl/src/std/math.rs

closes https://github.com/KittyCAD/modeling-app/issues/2384

add tests for min and max

---

src/wasm-lib/kcl/src/std/sketch.rs
src/wasm-lib/tests/executor/main.rs

fix empty tag on sketch on face

---

src-tauri/src/main.rs
src/lib/tauri.ts
src/routes/Home.tsx
src/wasm-lib/kcl/src/settings/types/file.rs

closes https://github.com/KittyCAD/modeling-app/issues/2353
adds a bunch of rust tests

Fix rename project directory

---

src-tauri/Cargo.lock
src-tauri/capabilities/desktop.json
src-tauri/src/main.rs

closes https://github.com/KittyCAD/modeling-app/issues/2470

use tauri command to run commands

---

src/App.tsx
src/components/LowerRightControls.tsx

quick gizmo homescreen fix

---

e2e/playwright/flow-tests.spec.ts
e2e/playwright/test-utils.ts
src/components/ModelingMachineProvider.tsx

closes https://github.com/KittyCAD/modeling-app/issues/584 and adds a test
ya'll can make this fancier in the future but this at least prevents bad things from happening and shows a user can continue sketching after

fix and simulate engine disconnect when in sketch mode

---

e2e/playwright/flow-tests.spec.ts
src/machines/modelingMachine.ts

continues on from #2543 
Also related to from https://github.com/KittyCAD/modeling-app/issues/2527
https://github.com/KittyCAD/modeling-app/assets/29681384/1c02188d-51a7-432a-9f24-e5e294f9f95c

Update selections after constraint is applied [horizontal and vertical]

---

src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/sketch.rs

Stuff that came up while working on multiple profiles per sketchgroup

Small refactor and renames

---

e2e/playwright/flow-tests.spec.ts
e2e/playwright/test-utils.ts
src/clientSideScene/ClientSideSceneComp.tsx
src/components/ActionButtonDropdown.tsx
src/components/AvailableVarsHelpers.tsx
src/components/ModelingMachineProvider.tsx
src/components/Toolbar/SetAngleBetween.tsx
src/components/Toolbar/setAngleLength.tsx
src/lang/util.ts
src/machines/modelingMachine.ts

technically is the fix for https://github.com/KittyCAD/modeling-app/issues/2527
But bug is lurking for other constraints too, so not going to close out yet.
Follows on from #2551 and #2543

fix single selection angle constraint

---

e2e/playwright/flow-tests.spec.ts
src/components/ModelingMachineProvider.tsx
src/components/Toolbar/SetAbsDistance.tsx
src/lang/std/sketchcombos.ts

More fixes for https://github.com/KittyCAD/modeling-app/issues/2527
Follows on from #2551, #2543 and #2555

fix ABS XY constraint

---

e2e/playwright/flow-tests.spec.ts
src/components/ModelingMachineProvider.tsx
src/components/Toolbar/Intersect.tsx
src/components/Toolbar/SetHorzVertDistance.tsx
src/machines/modelingMachine.ts

Related to https://github.com/KittyCAD/modeling-app/issues/2527

perpendicular distance & remove constraint - constraint fixes

---

package.json
src-tauri/tauri.conf.json

* Many constraint fixes by Kurt
* Improve rectangle code gen by Frank
* Remove FileTree from ProjectSiderbarMenu by Frank
* Small refactor and renames by Adam
* Enable Windows Tauri e2e tests in CI by Pierre
* Axis hover tooltip fix by Kurt
* Export now has a loading spinner by Frank
* Fix and simulate engine disconnect when in sketch mode by Jess
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.21.9...v0.22.0

Cut release v0.22.0

---

src/wasm-lib/Cargo.toml

Suggested reading:
https://doc.rust-lang.org/cargo/reference/profiles.html#profiles
https://doc.rust-lang.org/cargo/reference/profiles.html#debug

Faster debug builds

---

.github/workflows/playwright.yml

In the quest to speed up tests going to try this, This part of the tests takes ~50s so would be good to speed up.
Obviously the biggest win for the tests is going to be increasing workers, but every bit counts.

cache playwright browsers

---

src/wasm-lib/Cargo.lock
src/wasm-lib/Cargo.toml
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/tests/executor/main.rs

This will be helpful for https://github.com/KittyCAD/modeling-app/issues/2580

Refactor: Break functions into smaller functions

---

package.json
src-tauri/tauri.conf.json

* Fix for trackpad zoom jank by Dan
* Add a right-click menus to file tree and gizmo by Frank
* Improvements to selections by Kurt
* Improvements to engine connection status by Lee
* Extrusions now create new constants by Frank
* Click gizmo axis to snap to normal view by Max
* New remove constraints button in sketch overlays by Kurt
* New tab in Settings dialog to view keyboard shortcuts by Frank
* End-to-end test improvements by the team
* Faster debug builds by Adam
* Fix to Firefox paste behavior by Frank
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.22.0...v0.22.1

Cut release v0.22.1

---

e2e/playwright/flow-tests.spec.ts

fast follow to https://github.com/KittyCAD/modeling-app/pull/2521

add lint playwright test

---

package.json
src-tauri/tauri.conf.json

* 3D patterns can now be applied to 3D patterns in KCL (#2680)
* Add shell in KCL (#2683)
* Add chamfers in KCL (turns out they're fancy fillets) (#2681)
* Ensure settings are persisted before onboarding dismissal (#2678)
* Swap out icons for bug and refresh, tweak tooltip appearance (#2641)
* Many developer experience improvments
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.22.1...v0.22.2

Cut release v0.22.2

---

.envrc
.gitignore
flake.lock
flake.nix

I think I'm the only user of nix currently. But, for anyone else using nix this should allow them to install the necessary dev tools automatically.

Add nix flake and direnv config

---

docs/kcl/chamfer.md
docs/kcl/std.json
src/wasm-lib/kcl/src/std/chamfer.rs

closes https://github.com/KittyCAD/modeling-app/issues/2701

rename radius to length for chamfer;

---

src/wasm-lib/kcl/src/ast/types.rs

fixes https://github.com/KittyCAD/modeling-app/issues/2595

Recast bug fix 

---

package.json
src-tauri/tauri.conf.json

* Reset code on critical onboarding steps (#2727)
* Implement Core Dump for modeling app state (#2653)
* Franknoirot/onboarding avatar text (#2726)
* Fix onboarding example code loading (#2723)
* Fix clear diagnostics when not wasm (#2715)
* Add a feature flag to disable printlns in kcl-lib for the lsp (#2712)
* Disable SSAO temporarily (#2709)
* Get responses back from batch (#2687)
* Clear the AST if there was a parse error. (#2706)
* Recast bug fix  (#2703)
* Rename radius to length for chamfer; (#2702)
* Better styling for pane and KCL editor focus (#2691)
* Add a dismiss button to the command bar (#2647)
* Fix zoom issues with sketch mode (#2664)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.22.2...v0.22.3

Cut release v0.22.3

---

package.json
src-tauri/tauri.conf.json

* Fix sharing a sketch surface between profiles (#2744)
* Allow passing a vec of sketches or extrudes thru a user value (#2743)
* Fix one out of bounds error (#2740)
* Disable extrude button if there is no extrudable geometry (#2730)
* Fix sketch on face (#2745)

Cut release v0.22.4

---

e2e/playwright/flow-tests.spec.ts
src/clientSideScene/sceneEntities.ts
src/components/ModelingMachineProvider.tsx
src/editor/manager.ts
src/lang/std/sketchcombos.ts

fixes https://github.com/KittyCAD/modeling-app/issues/2636 and adds tests

fix point and click code pane closed from start

---

package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json

* Go back updater versions (#2746)
* Fix point and click code pane closed from start (#2750)
* Retain sketch selection segment color after adding a constraint to the segment (#2700)
* Allow for editing a sketch where extrude or revolve is in the same pipe (#2749)

Cut release v0.22.5

---

e2e/playwright/flow-tests.spec.ts
src/editor/plugins/lsp/plugin.ts

closes https://github.com/KittyCAD/modeling-app/issues/1111

playwright test for hover lsp functions

---

package.json
src-tauri/tauri.conf.json

* Fix source range for last command when engine error (#2757)
* Playwright test for hover lsp functions (#2756)
* Save specific commands like fillet and chamfer for last (#2753)

Cut release v0.22.6

---

src/wasm-lib/kcl/src/ast/types.rs

closes https://github.com/KittyCAD/modeling-app/issues/2780

fix some recast bugs

---

src/wasm-lib/kcl/src/lint/ast_walk.rs

When I originally wrote the walk stuff, I wanted to be able to stop a traversal by returning false. That didn't get implemented in the first rev, so this will actually build that out so returning false will stop the walk.

Implement stopping a walk from the Walk function

---

.github/workflows/playwright.yml
src/lib/trap.ts

Only show one error at once

---

e2e/playwright/flow-tests.spec.ts
e2e/playwright/test-utils.ts
src/components/ModelingMachineProvider.tsx
src/editor/manager.ts

selections, particularly of extrusion faces would get overridden
https://github.com/KittyCAD/modeling-app/assets/29681384/99a3f023-d017-48db-8155-df9382998f52
somewhat related to #2752

Selections bug

---

e2e/playwright/flow-tests.spec.ts
packages/codemirror-lsp-client/src/plugin/lint.ts
packages/codemirror-lsp-client/src/plugin/lsp.ts
src/editor/highlightextension.ts
src/editor/manager.ts
src/editor/plugins/lsp/copilot/index.ts
src/wasm-lib/kcl/src/lsp/copilot/mod.rs
src/wasm-lib/kcl/src/lsp/test_util.rs
src/wasm-lib/src/wasm.rs

the plugin doesnt run in prod but i also want to make sure it doesnt break or cause other weird shit

fixes up some playwright tests and adds a test for the ghost text plugin only in dev mode

---

src/hooks/useSetupEngineManager.ts
src/lang/std/engineConnection.ts
src/lang/wasm.ts
src/lib/testHelpers.ts
src/wasm-lib/kcl/src/engine/mod.rs
src/wasm-lib/src/wasm.rs

lets pray to the playwright gods this doesnt make things too weird

Move hide grid to rust

---

.github/workflows/ci.yml

see here https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions

fixes perms for releases

---

e2e/playwright/flow-tests.spec.ts

part of https://github.com/KittyCAD/modeling-app/issues/2803

add playwright tests for undo from click and point operations

---

src/components/LspProvider.tsx
src/useStore.ts

part of https://github.com/KittyCAD/modeling-app/issues/819

zustand updated for the lsp provider

---

e2e/playwright/flow-tests.spec.ts

Doing some house cleaning on the e2e tests, 
All but 6 tests are now grouped, please try to add new tests to an appropriate group if possible.

Grouping tests

---

e2e/playwright/flow-tests.spec.ts
src/components/ModelingMachineProvider.tsx

bad code on exit-sketch should no delete code

---

src/machines/modelingMachine.ts

Counter part to https://github.com/KittyCAD/engine/pull/2297/files

remove bad scaling on delete

---

package.json
src-tauri/tauri.conf.json

* Remove scaling code to match engine fixes (only effects delete) (#2902)
* Fix auto complete for circle (#2903)
* Ctrl-c is copy, we should not bind to copy or paste or any common shit (#2895)
* Bug fix:Bad code on exit-sketch should no delete user's code (#2890)
* Fix copilot regression (#2876)
* Disable copilot in sketch mode (#2865)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.22.7...v0.23.0

Cut release v0.23.0

---

src/components/FileTree.tsx
src/components/SettingsAuthProvider.tsx
src/components/Stream.tsx
src/hooks/useSetupEngineManager.ts
src/lang/KclSingleton.ts
src/lib/singletons.ts

Ignore the branch name; **there is no batching going on here**

Hide the view until the scene is initially built

---

src/components/ModelingMachineProvider.tsx
src/components/Stream.tsx
src/machines/modelingMachine.ts

Closes https://github.com/KittyCAD/modeling-app/issues/2676

Pause stream when exiting sketch or extruding

---

package.json
src/clientSideScene/CameraControls.ts
src/lib/settings/initialSettings.tsx
yarn.lock

Related to https://github.com/KittyCAD/engine/issues/2247
@franknoirot, this is all I needed to switch back on for SSAO yeah?

remove all z_near far params in engine calls, enable ssao again

---

src/components/Stream.tsx

Closes https://github.com/KittyCAD/modeling-app/issues/2966 but not the grid issue
Closes https://github.com/KittyCAD/modeling-app/issues/2973 also

Add a timeout instead of insta teardown on window hide

---

e2e/playwright/flow-tests.spec.ts

lots of formatting changes essentialy the change is `test.fixme`

playwright fixmes 😭

---

e2e/playwright/flow-tests.spec.ts
src/machines/authMachine.ts
src/routes/Onboarding/UserMenu.tsx

Closes https://github.com/KittyCAD/modeling-app/issues/2939

Handle the case of no avatar

---

.github/workflows/playwright.yml
playwright.config.ts
playwrightProcess.mjs

I have a feeling the `Install vector` task won't work without tweaks on macos, so might do this in two steps.

send failing test to axiom

---

src/Toolbar.tsx
src/components/ProjectSidebarMenu.tsx
src/hooks/useStateMachineCommands.ts
src/lib/commandBarConfigs/settingsCommandConfig.ts
src/lib/commandTypes.ts
src/lib/createMachineCommand.ts
src/machines/commandBarMachine.ts

Commands don't need to be part of a state machine.

refactor: Rename ownerMachine to groupId in Command

---

src/components/Stream.tsx
src/hooks/useSetupEngineManager.ts

closes https://github.com/KittyCAD/modeling-app/issues/2995

cleaner hack

---

src/AppState.tsx
src/components/Stream.tsx
src/hooks/useSetupEngineManager.ts
src/index.tsx
src/machines/modelingMachine.ts

Also related to https://github.com/KittyCAD/modeling-app/issues/2995
A bit nicer than https://github.com/KittyCAD/modeling-app/pull/3012

mediaStream

---

package.json
src-tauri/tauri.conf.json

* Critical bugfix for switching between projects by Kurt (#3012)
* More reliable text editing with deferrers by Jess & Marijn (#3006)
* Bugfix to keep extrude button active after sketch by Lee (#2961)
* Fix Creo camera controls to use correct gestures by Jon (#2963)
* Make deleting start of sketch not break line tool by Kurt (#2983)
* Tons of other bugfixes by the whole team
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.24.0...v0.24.1

Cut release v0.24.1

---

src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/benches/digest_benchmark.rs

add in benchmarks for digest code

---

package.json
src-tauri/tauri.conf.json

* pause stream improvements (#3032)
* Initial Fillet UI (not exposed yet) (#2718)
* Fix argument persistence and accidental submission command bar bugs (#3021)
* Show descriptions for generated commands, make them look better and sort better (#3023)
* Save settings between reconnects (#2997)
* Add sketch tools back to the command bar (#3008)
* Add format code to the command palette (#3001)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.24.1...v0.24.2

Cut release v0.24.2

---

README.md

Updater smoke-test instructions

---

src/App.tsx
src/components/ModelingMachineProvider.tsx
src/lang/KclSingleton.ts

Closes #3041 
I think it closes it at least I was able to mostly replicate it though I'm not 100% if it was the same or similar bug, I'll leave a longer comment on the issue.

show default planes bug

---

package.json
src-tauri/tauri.conf.json

* Fix large file import (#3050)
* Show default planes bug (#3047)
* Add a close button to sidebar panes (#3038)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.24.2...v0.24.3

Cut release v0.24.3

---

src/components/Stream.tsx

cc @lf94 @franknoirot but really idk if this will break something sorry for the long winded video here
closes https://github.com/KittyCAD/modeling-app/issues/3070 its not the stream takes long its just i wasnt getting the feedback i needed it was trying to build a large import
https://github.com/user-attachments/assets/1f672d0c-dd70-4a34-a513-502b2d5165b9

setIsLoading false earlier

---

src/components/ModelingSidebar/ModelingPanes/CodeEditor.tsx

Fixed
closes https://github.com/KittyCAD/modeling-app/issues/3077

Fix syntax highlighting on code pane open/close

---

e2e/playwright/flow-tests.spec.ts
packages/codemirror-lsp-client/src/plugin/lsp.ts
src/lang/KclSingleton.ts
src/wasm-lib/kcl/src/lsp/copilot/mod.rs

I have no idea if this is a good idea or not.
fixes https://github.com/KittyCAD/modeling-app/issues/3091

Clear the diagnostics before processing

---

package.json
src-tauri/tauri.conf.json

* Toolbar rewrite with (mostly) static content, rich tooltips, and roadmapped tools by Frank (#3119)
* Unified sidebar, actions in the sidebar like Export by Frank (#3100)
* Clear the diagnostics before processing by Paul (#3118, #3114)
* Add lexical scope and redefining variables in functions by Jon (#3015)
* Fix syntax highlighting on code pane open/close by Lee (#3083)
* Seperate pending messages from artifact map (#3084)
* Typecheck KCL args via generics, not handwritten impls by Adam (#3025)
* Remove sidebar menus in favor of lil' popovers by Frank (#3046)
* Many other bug fixes and testing improvements by the team
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.24.3...v0.24.4

Cut release v0.24.4

---

src-tauri/src/main.rs
src/wasm-lib/Cargo.lock
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/settings/utils.rs

https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html
For the `time` crate, see https://github.com/time-rs/time/issues/681. [Changelog](https://github.com/time-rs/time/blob/main/CHANGELOG.md)

Fix build error on Rust 1.80.0

---

e2e/playwright/flow-tests.spec.ts
src/clientSideScene/CameraControls.ts
src/components/ModelingMachineProvider.tsx
src/components/Tooltip.tsx

reduce camera hacks

---

src/wasm-lib/kcl/src/std/sketch.rs
src/wasm-lib/tests/executor/main.rs

closes https://github.com/KittyCAD/modeling-app/issues/3054

fix arc error

---

src/wasm-lib/kcl/src/std/sketch.rs
src/wasm-lib/tests/executor/main.rs

closes https://github.com/KittyCAD/modeling-app/issues/3109

fix errors for bad angles x/y constrained

---

src/wasm-lib/kcl/src/executor.rs

closes https://github.com/KittyCAD/modeling-app/issues/783

add a test for fn as operand

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs

closes https://github.com/KittyCAD/modeling-app/issues/2569

make a space work parse in fn call, recast well

---

src/wasm-lib/kcl/src/docs.rs

closes https://github.com/KittyCAD/modeling-app/issues/2436

fix autocomplete for ints

---

package.json
src-tauri/tauri.conf.json

* So many bug fixes from the whole team
* KCL: add [polar function](https://zoo.dev/docs/kcl/polar) to standard library by Jess (#3158)
* KCL: add [int function](https://zoo.dev/docs/kcl/int) to standard library by Jon (#3116)
* KCL: add [assert family of functions](https://zoo.dev/docs/kcl/assert) to standard library by Paul
* Tag functions no longer need their sketch as an arg thanks to Jess (#3143)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.24.4...v0.24.5

Cut release v0.24.5

---

e2e/playwright/flow-tests.spec.ts

fix 'Engine disconnect & reconnect in sketch mode' test

---

src/components/Stream.tsx

I think related to https://github.com/KittyCAD/modeling-app/pull/3205
Therefore we want this in before we merge/release https://github.com/KittyCAD/modeling-app/pull/3214

unpause vid in next event loop

---

package.json
src-tauri/tauri.conf.json

* Bug fix: prevent KCL error due to colliding AST execution on project switch (#3205)
* Add a system for badges to appear on pane buttons (#3208)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.24.5...v0.24.6

Cut release v0.24.6

---

src/wasm-lib/Cargo.lock
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/settings/types/file.rs

closes https://github.com/KittyCAD/modeling-app/issues/3227

open file with url encoded space

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/executor.rs

closes https://github.com/KittyCAD/modeling-app/issues/3224

fix cryptic error

---

src/components/ModelingMachineProvider.tsx
src/machines/modelingMachine.ts

Closes #3221.
https://github.com/user-attachments/assets/278f0a17-c52a-4853-87de-b84cd37730c2
_tauri tests electron tests_

Re-get the openPanes from localStorage when navigating between projects

---

e2e/playwright/flow-tests.spec.ts

test for default planes in empty scene

---

src/lang/std/engineConnection.ts

fixes https://github.com/KittyCAD/modeling-app/issues/3203
relevant to https://github.com/KittyCAD/modeling-app/issues/3255

fix bug when engine returns an error on websocket export

---

src/wasm-lib/kcl/src/std/shell.rs
src/wasm-lib/tests/executor/inputs/fillet-and-shell.kcl
src/wasm-lib/tests/executor/main.rs

fixes https://github.com/KittyCAD/modeling-app/issues/3257 but kinda
now it fails with "Shell of non-planar solid3d not available yet" which we know @benjamaan476  is working on

apply fillets before a shell

---

e2e/playwright/flow-tests.spec.ts
e2e/playwright/storageStates.ts
src/components/ModelingSidebar/ModelingPanes/index.ts
src/components/ModelingSidebar/ModelingSidebar.tsx
src/editor/manager.ts

Jump to error code on badge click

---

package.json
src-tauri/tauri.conf.json

* Jump to error code on badge click (#3262)
* Apply fillets before a shell (#3261)
* Editor repaints any errors when rendered (#3260)
* Add print button (#3133)
* Fix bug when engine returns an error on websocket export (#3256)
* Test for default planes in empty scene (#3249)
* Fix computed properties of KCL objects (#3246)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.24.7...v0.24.8

Cut release v0.24.8

---

e2e/playwright/flow-tests.spec.ts
src/lang/std/artifactGraph.ts

Resolves #3251
created https://github.com/KittyCAD/modeling-app/issues/3268 in the process.

Coplanar sketch should have diagnostic error.

---

src/machines/modelingMachine.ts

reset camera on empty scene

---

package.json
src-tauri/tauri.conf.json

This reverts commit 1c778bf3737afd504127867279757062269d8c0a.

Revert "Cut release v0.24.9 (#3284)"

---

package.json
src-tauri/tauri.conf.json

* Reset camera on empty scene (#3293)
* Don't allow edit on sketches with no variable declaration (#3292)
* Add assertEqual function to KCL stdlib (#3279)
* Add "report a bug" mention to user menu onboarding step (#3278)
* Camera breaks on extrude zoom to fit (#3276)
* Jump to error not lint (#3271)
* Coplanar sketch should have diagnostic error. (#3269)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.24.8...v0.24.9

Cut release v0.24.9

---

src/components/Stream.tsx

Switch projects fix

---

src/lib/routeLoaders.ts

Revert the changes to routeLoaders included in https://github.com/KittyCAD/modeling-app/pull/3250

Don't set firstRender from within a routeLoader

---

package.json
src-tauri/tauri.conf.json

Reverts KittyCAD/modeling-app#3309

Revert "Cut release v0.24.10"

---

src/clientSideScene/sceneEntities.ts

Related to https://github.com/KittyCAD/modeling-app/issues/3238#issuecomment-2266193341.
Trying to make the types of our functions more accurate.

Fix type of sketchGroup function

---

package.json
src-tauri/tauri.conf.json

This reverts commit 308a0fb06e2f83db08dab02ef634f3b9a26f7358.

Revert "Revert "Cut release v0.24.10" (#3313)"

---

package.json
src-tauri/tauri.conf.json

This reverts commit eb58507e938eeac8c2eb9854b9fb91996d0a8f67.

Revert "Revert "Revert "Cut release v0.24.10" (#3313)" (#3321)"

---

package.json
src-tauri/tauri.conf.json

* Fix settings derp and app start project theme loading (#3320)
* Fix tanArcTo (#3318)
* Set Playwright actionTimeout to 15 seconds (#3115)
* Increase windows stream ping interval (#3317)
* Fix type of sketchGroup function (#3316)
* Fix test: Basic sketch › code pane open at start (#3188)
* Switch projects fix (#3310)
* Persist theme - Reload everything on a disconnect (#3250)
* Start to rework some of our kcl docs (#3222)
* ArtifactGraph snapshot stability (#3305)
* Badge scale on hover (#3298)
* Add a search bar to the projects/home page (#3301)
* Add a little dropdown arrow menu to gizmo with view settings (#3300)
* Reset camera on empty scene (#3293)
* Don't allow edit on sketches with no variable declaration (#3292)
**Full Changelog**: …

Cut release v0.24.10

---

e2e/playwright/sketch-tests.spec.ts
e2e/playwright/test-utils.ts
e2e/playwright/testing-constraints.spec.ts
e2e/playwright/various.spec.ts
src/test-utils.test.ts

If you have access to our slack, here's a long thread talking about it https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1723200608529019

fix playwright

---

src/components/FileTree.tsx

fix files pane height issue

---

e2e/playwright/regression-tests.spec.ts
e2e/playwright/storageStates.ts
src/components/ModelingMachineProvider.tsx
src/components/ModelingSidebar/ModelingPanes/KclEditorPane.tsx
src/hooks/useSetupEngineManager.ts
src/lang/std/artifactGraph.test.ts
src/lang/std/engineConnection.ts

closes https://github.com/KittyCAD/modeling-app/issues/3395
closes https://github.com/KittyCAD/modeling-app/issues/3255

add a regression test for when engine returns a export fail

---

.github/workflows/playwright.yml
playwright.ci.config.ts

Add ci specific playwright config.  The existing `playwright.config.ts` can function as is, there is no need to change anything locally.

create ci specific playwright config

---

src-tauri/Cargo.lock

This is always changed and causes lots of issues with git.

Fix lock file

---

e2e/playwright/text-to-cad-tests.spec.ts
src/components/ModelingMachineProvider.tsx
src/components/ToastTextToCad.tsx
src/lib/textToCad.ts
src/machines/modelingMachine.ts

closes https://github.com/KittyCAD/modeling-app/issues/3444

remove flakey has no pending logic, let them do whatever they want

---

e2e/playwright/regression-tests.spec.ts
e2e/playwright/text-to-cad-tests.spec.ts
src/components/FileMachineProvider.tsx
src/components/FileTree.tsx
src/components/ModelingMachineProvider.tsx
src/index.tsx
src/lib/constants.ts
src/lib/tauriFS.ts
src/lib/textToCad.ts
src/machines/fileMachine.ts

Closes #3456. Needs tauri tests, electron tests, dna tests, LSATs, etc.
https://github.com/user-attachments/assets/32ab253b-880b-4baf-8be3-b24d8405b83e

Always give new files and dirs a new index if their names are taken

---

src/clientSideScene/sceneEntities.ts
src/components/ModelingSidebar/ModelingPanes/MemoryPane.tsx
src/lang/executor.test.ts
src/lang/modifyAst.ts
src/lang/queryAst.ts
src/lang/std/sketch.ts
src/lang/std/sketchConstraints.test.ts
src/lang/std/sketchcombos.ts
src/lang/wasm.ts
src/machines/modelingMachine.ts

Move error-handling into the getter function

---

package.json
src-tauri/tauri.conf.json

* Remove flakey has no pending logic, let users do whatever they want (#3457)
* Fix sketch groups and extrude groups when used inside objects (#3439)
* Add unique index when creating new files or directories with taken names (#3460)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.24.11...v0.24.12
just will wait on a fix for https://github.com/KittyCAD/modeling-app/issues/3456

Cut release v0.24.12

---

e2e/playwright/projects.spec.ts
src/components/ProjectCard/ProjectCard.tsx

electron delete project tests

---

e2e/playwright/projects.spec.ts

Closes #3367 by renaming te better match this test.

rename for #3367

---

.github/workflows/build-test-web.yml

get unit tests running again

---

.github/workflows/playwright.yml
e2e/playwright/projects.spec.ts
e2e/playwright/test-utils.ts
src/lib/exportSave.ts

Electron export test #3376

---

e2e/playwright/projects.spec.ts
e2e/playwright/test-utils.ts
src/components/FileTree.tsx

Electron test: (regression) you can scroll the file pane when ETOOMANYFILES to view in one view

---

src/.github/workflows/label-issues.yml

Fixes #3541
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/KittyCAD/modeling-app/issues/3541?shareId=03fb2ca3-69b2-4b50-abad-db56b9adf471).

Add GitHub action to label issues opened by ZooSpiritWolf

---

e2e/playwright/projects.spec.ts
src/components/HelpMenu.tsx

test keyboard shortcuts from help menu

---

e2e/playwright/desktop-export.spec.ts
e2e/playwright/machines.spec.ts
e2e/playwright/onboarding-tests.spec.ts
e2e/playwright/projects.spec.ts
e2e/playwright/regression-tests.spec.ts
e2e/playwright/testing-settings.spec.ts

skip failing windows tests

---

src/components/DownloadAppBanner.tsx

Resolves  #3503
I went with 
Where the message about chrome is not there if you're on chrome.

Update the Web Banner

---

package.json
src-tauri/tauri.conf.json

Cut release v0.24.13

---

e2e/playwright/projects.spec.ts
e2e/playwright/test-utils.ts

resolves #3582 by adding a test using the command bar directly, now sidebar button, dropdown menu and this is covered.

Test for 3 export paths

---

src/components/ModelingSidebar/ModelingPanes/MemoryPane.tsx
src/lang/wasm.ts

closes [#3615](https://github.com/KittyCAD/modeling-app/issues/3615)

fix failing tests from chalmers pr

---

e2e/playwright/projects.spec.ts

file in the file tree open with a single click [fix me remove]

---

e2e/playwright/code-pane-and-errors.spec.ts
e2e/playwright/desktop-export.spec.ts
e2e/playwright/machines.spec.ts
e2e/playwright/onboarding-tests.spec.ts
e2e/playwright/projects.spec.ts
e2e/playwright/regression-tests.spec.ts
e2e/playwright/test-utils.ts
e2e/playwright/testing-settings.spec.ts

Covers most of https://github.com/KittyCAD/modeling-app/issues/3557
One test still not passing in CI but does work on my local. I'm trying to reproduce so I can fix but I'll do that in a separate PR.

Enable all disabled win32 tests

---

e2e/playwright/testing-camera-movement.spec.ts

Fix existing: Zoom should be consistent when exiting or entering sketches

---

e2e/playwright/projects.spec.ts

Add test for not creating main.kcl when there are nested directories

---

.codespellrc
.github/workflows/cargo-test.yml
.gitignore
package.json

There's also a section in the readme, but I'm not sure what to update it to.

Remove references to src-tauri

---

src/lang/modifyAst/addFillet.ts

Reverts KittyCAD/modeling-app#3685

Revert "Bug: Fillet Button - selecting edge without tag caused an Error"

---

src/lang/KclSingleton.ts

remove double zoom to fit

---

src/machines/modelingMachine.ts

Fix Stream shows the inside of sketch after extrude

---

src/wasm-lib/tests/executor/main.rs

Want to merge this one quickly for https://github.com/KittyCAD/engine/pull/2532/files.
it won't break tests before or after PR comes in

Fix tests for upcoming PR

---

src/wasm-lib/kcl/src/parser/parser_impl.rs
src/wasm-lib/kcl/src/parser/snapshots/kcl_lib__parser__parser_impl__snapshot_tests__ba.snap

Fixes https://github.com/KittyCAD/modeling-app/issues/3708, ty @mlfarrell for reporting!

Parse multi-line comments in |> expressions

---

e2e/playwright/desktop-export.spec.ts
e2e/playwright/projects.spec.ts
src/lib/exportSave.ts

fix export logic

---

.github/workflows/build-test-publish-apps.yml

Generate download endpoint with linux links

---

src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/extrude.rs
src/wasm-lib/kcl/src/std/sketch.rs

- post-extrude code can be more functional
- impl Copy for Point3d

KCL: small refactors to Extrude

---

src/wasm-lib/kcl/src/std/mod.rs
src/wasm-lib/kcl/src/token/tokeniser.rs
src/wasm-lib/rust-toolchain.toml

https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html

Upgrade to rust 1.81.0

---

package.json
yarn.lock

Reverts KittyCAD/modeling-app#3804

Revert "Update package.json to remove tauri dep"

---

.github/workflows/build-test-web.yml
package.json
packages/codemirror-lsp-client/src/plugin/lsp.ts

Before, this code was only getting linted while running tests, which is weird.

Add linting to codemirror-lsp-client

---

src/clientSideScene/ClientSideSceneComp.tsx
src/clientSideScene/sceneEntities.ts
src/clientSideScene/sceneInfra.ts
src/clientSideScene/segments.ts
src/components/ModelingMachineProvider.tsx
src/components/Toolbar/EqualAngle.tsx
src/components/Toolbar/EqualLength.tsx
src/components/Toolbar/HorzVert.tsx
src/components/Toolbar/Intersect.tsx
src/components/Toolbar/RemoveConstrainingValues.tsx
src/components/Toolbar/SetAbsDistance.tsx
src/components/Toolbar/SetAngleBetween.tsx
src/components/Toolbar/SetHorzVertDistance.tsx
src/components/Toolbar/setAngleLength.tsx
src/lang/langHelpers.ts
src/lang/modifyAst.test.ts
src/lang/modifyAst.ts
src/lang/queryAst.ts
src/lang/std/sketch.test.ts
src/lang/std/sketch.ts
src/lang/std/sketchConstraints.ts
src/lang/std/sketchcombos.ts
src/lang/std/stdTypes.ts
src/lib/selections.ts
src/lib/toolbar.ts

So my plan with this PR was to get a [write up](https://docs.google.com/document/d/16EROjbvGZnBg7Y43yaA36mS4SkC8Cxpm2gpZ1mY2UJo/edit#heading=h.tzt2ezem0mhn) for how much of the client side scene works, Then whoever is reviews this might be able to make more sense of this since the explainer is for the code state after this PR is merged.
But not sure how well that's going to work out, because you might not have context on how it used to be. Anyway would definitely appreciate any feedback, or question to clarify how things are working here.

Refactor clientSide scene

---

src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/array.rs
src/wasm-lib/kcl/src/std/planes.rs

It's a constructor. It doesn't mutate.

Rename UserVal::set to new to be clearer

---

e2e/playwright/testing-settings.spec.ts

Closes #2713 by adding a test step to a pre-existing E2E settings test, which verifies that the default planes are not visible through the background of the settings dialog.

Add a test step to confirm the solid bg of the settings dialog

---

package.json

* Update app to sync with breaking change
* Implement from for unit length (#3932)
* Bump the world (kcl-lib) (#3930)
* Fix edge cut logic (#3928)
* Fix zoom callback on camera controls (#3924)
* zoom level increase when swapping sketch modes (#3854)
* Fix power syntax "4 ^ 2" (#3900)
* Bug fix: make dismiss during export not fire success toast (#3882)
* Fix canExtrudeSelectionItem and getSelectionType for multiple selections (#3884)
* Make light theme borders more contrasting, update sidebar icons (#3883)
* Fix: Opposite adjacent edge selection (#3896)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.25.2...v0.25.3

Cut release v0.25.3

---

e2e/playwright/snapshot-tests.spec.ts

disable failing step export test

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/ast/types/condition.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs
src/wasm-lib/kcl/src/parser/snapshots/kcl_lib__parser__parser_impl__snapshot_tests__bc.snap
src/wasm-lib/kcl/src/parser/snapshots/kcl_lib__parser__parser_impl__snapshot_tests__bd.snap
src/wasm-lib/kcl/src/unparser.rs
src/wasm-lib/kcl/src/walk/ast_node.rs
src/wasm-lib/kcl/src/walk/ast_walk.rs
src/wasm-lib/tests/executor/inputs/no_visuals/if_else.kcl
src/wasm-lib/tests/executor/inputs/no_visuals/if_else_no_expr.kcl
src/wasm-lib/tests/executor/no_visuals.rs

Closes https://github.com/KittyCAD/modeling-app/issues/3677
You can review each commit separately, they're neat commits with logical purpose in each.
Future enhancements:
- https://github.com/KittyCAD/modeling-app/issues/4015
- https://github.com/KittyCAD/modeling-app/issues/4020
- Right now the parser errors are not very good, especially if you forget to put an expression in the end of an if/else block

KCL: If-else expressions

---

.github/workflows/build-test-publish-apps.yml

Invalidate bucket cache on release

---

e2e/playwright/projects.spec.ts
interface.d.ts
src/hooks/useFileSystemWatcher.tsx
src/hooks/useProjectsLoader.tsx
src/lib/commandBarConfigs/homeCommandConfig.ts
src/lib/routeLoaders.ts
src/lib/types.ts
src/machines/homeMachine.ts
src/preload.ts
src/routes/Home.tsx

This is 1 of N PRs to have fs-aware reloading.

Reload projects when there are external changes on the file-system

---

.github/workflows/build-test-publish-apps.yml

Reverts KittyCAD/modeling-app#3921

Revert "Split artifacts per arch and re-enable updater for nightly builds"

---

src/components/ModelingMachineProvider.tsx
src/lang/std/engineConnection.ts
src/lib/constants.ts
src/lib/exportMake.ts

thanks @franknoirot for the help!

fix job name for printers

---

src/wasm-lib/kcl-macros/tests/macro_test.rs
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs
src/wasm-lib/kcl/src/walk/ast_walk.rs
src/wasm-lib/rust-toolchain.toml

https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html

Upgrade to rust toolchain 1.82.0

---

.github/workflows/build-test-publish-apps.yml

Fixes #4246
Two typos that got us for v0.26.0 I believe. Let's try to have this merged before the next one 🙏

Fix release notes in last_download.json

---

src/components/ModelingMachineProvider.tsx

Resolves #4280
lmk if I'm being lazy, but with us not doing the "force perpendicular" soon, not sure if a test is worth it, since this isn't a trust melting bug anyway.

Disable rotate on start new sketch

---

src/components/FileTree.tsx
src/lang/codeManager.ts

Only pinging you jess in case Frank's out for the weekend
It solves the issue coreypdx reported on discord: https://discord.com/channels/915388055236509727/1299168400479748097

Make application aware it saved the buffer and not something else

---

src/wasm-lib/kcl/src/std/extrude.rs

I didn't understand this code at first, I think it's written kinda weird but now I understand what it's doing.
This shouldn't actually change any behaviour.

Fix weirdly specific logic for querying extruded face info

---

.github/dependabot.yml

Daily is too noisy.
See [configuration options](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file).

Change Dependabot PR frequency to weekly

---

.github/workflows/build-test-publish-apps.yml
package.json

* File tree acts more like VS Code's file tree (#4392)
* Creating new projects asks for project name before creating (#4109)
* Snap-to-origin and axis behavior for sketch profile starts and segments (#4344)
* KCL: `polygon` standard library function (Thanks @guptaarnav) (#4300)
* KCL: Add ability to `push` to arrays (Thanks @guptaarnav (#4232)
* Implement a simple startSketchOn / offsetPlane lint rule (#4384)
* KCL: More ways to reference paths (#4387)
* Error if assertEqual's epsilon value is invalid (#4329)
* Show top-level project directory name in file tree pane header (#4165)
* Add ability to open, create, rename, and delete projects from inside one via command bar (#4109)
* Fix KCL source ranges to know which source file they point to (#4418)
* Fixed directory/file selection logic …

Cut release v0.26.3

---

package.json

* Fix bug where accepting an autocompletion would break the code editor (#4476)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.26.4...v0.26.5

Cut release v0.26.5

---

docs/kcl/modules.md

[Rendered](https://github.com/KittyCAD/modeling-app/blob/jtran/doc-import/docs/kcl/modules.md)
Related: #4080.

Add docs for modules and import statements

---

src/wasm-lib/kcl/src/std/patterns.rs

Part of https://github.com/KittyCAD/modeling-app/issues/4543

KCL refactor: implement patternLinear2D as patternTransform

---

src/components/Settings/AllSettingsFields.tsx

Open about section links externally in Settings

---

src/wasm-lib/kcl/src/std/shapes.rs
src/wasm-lib/kcl/src/std/sketch.rs

See https://github.com/KittyCAD/modeling-api/pull/651.

Change to use Angle type's comparison

---

.github/workflows/publish-apps-release.yml

Left over from tests before merging #4530

Fix publish path in release bucket

---

src/wasm-lib/kcl/src/parser/parser_impl.rs

Pure refactor, no behavioural changes.

KCL refactor: break typechecking into its own fn

---

README.md
src/wasm-lib/Cargo.lock
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/engine/conn.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/lib.rs
src/wasm-lib/kcl/src/log.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs

Sample output:
```
Interpretation
time: 1246.773ms
memory:
allocations:          11.89931 MB (130637 blocks)
currently allocated:  243.272 KB
max allocated:        243.272 KB
Parsing
time: 3067.501ms
memory:
allocations:          95.51558 MB (317905 blocks)
currently allocated:  55486.447 KB
max allocated:        55486.447 KB
test simulation_tests::poop_chute::kcl_test_execute ... ok
test simulation_tests::poop_chute::parse ... ok
```

Log simple performance metrics

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/function_param.rs
src/wasm-lib/kcl/src/log.rs
src/wasm-lib/kcl/src/std/shapes.rs
src/wasm-lib/rust-toolchain.toml

Bump to Rust 1.83

---

docs/kcl/types.md
public/kcl-samples-manifest-fallback.json

Update fn syntax in KCL Types doc

---

docs/kcl/modules.md

Update fn syntax in module docs

---

e2e/playwright/secrets.ts

This lets me document for my (future) self.

Add support for line comments in playwright-secrets.env

---

e2e/playwright/projects.spec.ts
src/components/FileTree.tsx
src/components/ModelingSidebar/ModelingPanes/KclEditorMenu.tsx
src/components/ProjectSidebarMenu.tsx
src/lang/KclSingleton.ts
src/lang/std/engineConnection.ts
src/lang/wasm.ts
src/lib/desktopFS.ts
src/lib/kclCommands.ts
src/wasm-lib/kcl/src/parsing/ast/mod.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/src/wasm.rs

remove clearScene from TS side

---

src/wasm-lib/kcl/src/execution/exec_ast.rs
src/wasm-lib/kcl/src/std/args.rs

Pure refactor, no behaviour change.

KCL refactor: combine two fields into one struct

---

src/lang/wasm.test.ts

Fix race condition in wasm test

---

src/components/LowerRightControls.tsx
src/components/Settings/AllSettingsFields.tsx
src/components/ToastUpdate.tsx
src/routes/Settings.tsx

Fixes #4726
Tested locally with regular and nightly (`yarn files:flip-to-nightly`) configs.

More consistent GitHub links

---

src/lang/wasm.ts

Add some comments to some types and functions added in #4677.

Add some comments to new API in wasm.ts

---

e2e/playwright/editor-tests.spec.ts
src/lang/KclSingleton.ts
src/lang/langHelpers.ts
src/lang/modifyAst/addEdgeTreatment.test.ts
src/lang/std/engineConnection.ts
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/test_server.rs
src/wasm-lib/tests/executor/main.rs

Fix ids for kurt so front end re-uses same ones on executions

---

docs/kcl/patternTransform.md
docs/kcl/reduce.md
docs/kcl/segEnd.md
docs/kcl/segStart.md
src/wasm-lib/kcl/src/std/array.rs
src/wasm-lib/kcl/src/std/patterns.rs
src/wasm-lib/kcl/src/std/segment.rs

Stacked on #4819. Part of #4652.

Remove uses of startSketchAt() from the doc tests

---

src/components/ToastTextToCad.tsx

https://kittycadworkspace.slack.com/archives/C061R186RUZ/p1734657077618829

Yeet telemetry to text to cad endpoint

---

e2e/playwright/prompt-to-edit.spec.ts
src/lib/promptToEdit.ts

Makes consistent with the text-to-cad toast message.
Jordan's request

Tweak prompt wording

---

public/announce_release.py

`textwrap.dedent` should remove that whitespace

update discord bot

---

src/wasm-lib/kcl/src/std/helix.rs
src/wasm-lib/kcl/src/std/sketch.rs

closes https://github.com/KittyCAD/modeling-app/issues/3173

remove backwards compatibility for snake case in objects

---

src/clientSideScene/sceneEntities.ts
src/machines/modelingMachine.ts

I recommend checking this over even if you don't want to review; it shows the new pattern we'll use going forward for sketching tools.
We can have a huddle if you guys have many questions lol

Make circle3Point tool an actor

---

e2e/playwright/sketch-tests.spec.ts
src/components/ModelingSidebar/ModelingPanes/KclEditorPane.tsx
src/editor/manager.ts
src/lib/selections.ts

closes https://github.com/KittyCAD/modeling-app/issues/4891
until we do move the artifact graph to rust i think there are still cases where the ranges will be stale but at least now they wont overflow the doc

fix out of range error

---

packages/codemirror-lang-kcl/src/kcl.grammar
packages/codemirror-lang-kcl/test/fn.txt

Remake of https://github.com/KittyCAD/modeling-app/pull/4940 by @mattmundell

CM KCL: = and => are optional in fn declarations

---

interface.d.ts
src/components/ToastUpdate.test.tsx
src/components/ToastUpdate.tsx
src/lib/markdown.ts

Recreated out of #4790 to run the full test suite. Thanks @marc2332!
See the manual testing I did at https://github.com/KittyCAD/modeling-app/pull/4790#issuecomment-2576324919

Open updater toast changelog links externally

---

src/lib/utils.ts

We can see where we're failing from again!

Prevent toSync from clobbering stack traces

---

package.json
src/components/ModelingMachineProvider.tsx
yarn.lock

And update one of our uses of a command which has a new property we hadn't been including.

Bump @kittycad/lib to v2.0.13

---

.github/dependabot.yml

Right now, I believe it's based on when we last updated this file.

Change Dependabot PRs to always be made on Mondays

---

.github/workflows/codemirror-lang-kcl.yml
packages/codemirror-lang-kcl/.gitignore
packages/codemirror-lang-kcl/package.json
packages/codemirror-lang-kcl/postcss.config.js
packages/codemirror-lang-kcl/yarn.lock

Resolves #4935.
The unit tests are fast. We should make it a required check.

ci: Add yarn test of packages/codemirror-lang-kcl

---

src/routes/Onboarding/index.tsx

Fixes #5049
You were right @franknoirot, pretty easy. Can now Return Return Return your way through all steps.

Return key to go through Onboarding steps

---

e2e/playwright/point-click.spec.ts
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/commandTypes.ts

Loft command prompt focus fix

---

.github/workflows/build-apps.yml

Happens sometimes and it's annoying so let's auto retry.
See https://github.com/KittyCAD/modeling-app/actions/runs/12798920384 for instance

Auto retry on yarn install as it sometimes fail on windows

---

e2e/playwright/fixtures/homePageFixture.ts
e2e/playwright/projects.spec.ts
src/components/ProjectsContextProvider.tsx

Bug fix follow-up for create project

---

src/components/CommandComboBox.tsx

Show "No results found" for empty search results in command palette

---

src/lang/KclSingleton.ts
src/lang/codeManager.ts
src/lang/kclSamples.test.ts
src/lang/langHelpers.ts
src/lang/std/fileSystemManager.ts
src/lang/wasm.ts
src/lib/testHelpers.ts
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/simulation_tests.rs
src/wasm-lib/kcl/src/test_server.rs
src/wasm-lib/kcl/tests/import_cycle1/execution_error.snap
src/wasm-lib/src/wasm.rs

Resolves #5043. Resolves #4434.

fix subdirs (opening kcl-samples from kcl-samples dir)

---

.gitignore

This keeps showing up in git status as untracked.

Ignore cloned kcl-samples

---

src/lang/wasm.ts
src/lib/wasm_lib_wrapper.ts
src/wasm-lib/Cargo.lock
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/docs/mod.rs
src/wasm-lib/kcl/src/execution/annotations.rs
src/wasm-lib/kcl/src/execution/exec_ast.rs
src/wasm-lib/kcl/src/execution/import.rs
src/wasm-lib/kcl/src/execution/kcl_value.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/lib.rs
src/wasm-lib/kcl/src/parsing/ast/modify.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/std/math.rs
src/wasm-lib/kcl/src/std/sketch.rs
src/wasm-lib/src/wasm.rs

going to need some help from @nrc 
this is needed for @franknoirot on the ui side

Helper functions for meta settings (get/update)

---

e2e/playwright/file-tree.spec.ts
e2e/playwright/test-utils.ts
interface.d.ts
src/components/FileMachineProvider.tsx
src/components/FileTree.tsx
src/components/ModelingSidebar/ModelingPanes/index.tsx
src/machines/fileMachine.ts
src/preload.ts

Clones files and folders in the file tree.
https://github.com/user-attachments/assets/409c92ba-0920-4923-9ccd-28b3fddd2ade
Resolves https://github.com/KittyCAD/modeling-app/issues/3089

Add 'Clone' feature to file tree

---

.github/workflows/e2e-tests.yml

Fix a quick secret confusion after #5253

Point snapshot bot tokens to the right ones

---

docs/kcl/types.md

A few issues:
- There was no description of how `|>` works
- Need to explain our keyword arguments implementation
- It was using old syntax for `angledLine` which now takes an object as its first parameter, not an array

Update types.md with keyword args data

---

src/wasm-lib/kcl/src/execution/exec_ast.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/std/array.rs
src/wasm-lib/kcl/src/std/patterns.rs
src/wasm-lib/rust-toolchain.toml

https://blog.rust-lang.org/2025/01/09/Rust-1.84.0.html
https://blog.rust-lang.org/2025/01/30/Rust-1.84.1.html

Upgrade rust toolchain to 1.84.1

---

docs/kcl/types/KclValue.md
src/wasm-lib/kcl/src/execution/exec_ast.rs
src/wasm-lib/kcl/src/execution/kcl_value.rs
src/wasm-lib/kcl/src/execution/memory.rs
src/wasm-lib/kcl/src/std/args.rs
src/wasm-lib/kcl/src/std/patterns.rs
src/wasm-lib/kcl/tests/array_range_expr/program_memory.snap
src/wasm-lib/kcl/tests/array_range_negative_expr/program_memory.snap
src/wasm-lib/kcl/tests/double_map_fn/program_memory.snap

Remove KclValue::Int

---

docs/kcl/loft.md
docs/kcl/offsetPlane.md
e2e/playwright/feature-tree-pane.spec.ts
e2e/playwright/point-click.spec.ts
e2e/playwright/sketch-tests.spec.ts
package.json
src/lang/kclSamples.test.ts
src/lang/modifyAst.ts
src/lang/queryAst.test.ts
src/lang/queryAst.ts
src/lib/operations.ts
src/wasm-lib/kcl/src/std/args.rs
src/wasm-lib/kcl/src/std/loft.rs
src/wasm-lib/kcl/src/std/planes.rs
src/wasm-lib/kcl/tests/artifact_graph_example_code_offset_planes/artifact_commands.snap
src/wasm-lib/kcl/tests/artifact_graph_example_code_offset_planes/artifact_graph_flowchart.snap.md
src/wasm-lib/kcl/tests/artifact_graph_example_code_offset_planes/ast.snap
src/wasm-lib/kcl/tests/artifact_graph_example_code_offset_planes/input.kcl
src/wasm-lib/kcl/tests/artifact_graph_example_code_offset_planes/ops.snap
src/wasm-lib/kcl/tests/artifact_graph_example_code_offset_planes/program_memory.snap

Previously: `offsetPlane('XY', 75)`
Now: `offsetPlane('XY', offset = 75)`
Pairs with this KCL-samples PR: https://github.com/KittyCAD/kcl-samples/pull/163

offsetPlane kwargs

---

src/wasm-lib/Cargo.lock
src/wasm-lib/derive-docs/Cargo.toml
src/wasm-lib/kcl-test-server/Cargo.toml
src/wasm-lib/kcl/Cargo.toml

- Fix units not getting set properly with whole module imports ([5418](https://github.com/KittyCAD/modeling-app/pull/5418))

Release KCL 38

---

e2e/playwright/sketch-tests.spec.ts

Fix sketch test

---

public/kcl-samples-manifest-fallback.json

I think this is going away very soon but I don't want it to annoy anyone's work in the meantime.

Bump kcl-samples manifest fallback

---

docs/kcl/startSketchOn.md
docs/kcl/types/BasePath.md
docs/kcl/types/EnvironmentRef.md
docs/kcl/types/ExtrudeSurface.md
docs/kcl/types/Face.md
docs/kcl/types/FaceTag.md
docs/kcl/types/GeoMeta.md
docs/kcl/types/Helix.md
docs/kcl/types/HelixValue.md
docs/kcl/types/KclValue.md
docs/kcl/types/Metadata.md
docs/kcl/types/NumericType.md
docs/kcl/types/Path.md
docs/kcl/types/Plane.md
docs/kcl/types/Sketch.md
docs/kcl/types/SketchData.md
docs/kcl/types/SketchOrSurface.md
docs/kcl/types/SketchSet.md
docs/kcl/types/SketchSurface.md
docs/kcl/types/Solid.md
docs/kcl/types/SolidSet.md
docs/kcl/types/SourceRange.md
docs/kcl/types/SweepPath.md
src/lang/std/engineConnection.ts
src/wasm-lib/kcl/src/docs/gen_std_tests.rs
src/wasm-lib/kcl/src/lsp/tests.rs
src/wasm-lib/kcl/src/std/sketch.rs

random descriptions were wrong and wanted to add stuff for behavior of sketch on face

Fixes to docs

---

src/lang/errors.ts
src/wasm-lib/kcl/src/execution/exec_ast.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/execution/state.rs
src/wasm-lib/kcl/src/modules.rs
src/wasm-lib/kcl/tests/add_lots/ops.snap
src/wasm-lib/kcl/tests/assembly_non_default_units/artifact_commands.snap
src/wasm-lib/kcl/tests/assembly_non_default_units/ops.snap
src/wasm-lib/kcl/tests/basic_fillet_cube_next_adjacent/ops.snap
src/wasm-lib/kcl/tests/fillet-and-shell/ops.snap
src/wasm-lib/kcl/tests/i_shape/ops.snap
src/wasm-lib/kcl/tests/import_function_not_sketch/ops.snap
src/wasm-lib/kcl/tests/import_side_effect/ops.snap
src/wasm-lib/kcl/tests/import_whole/ops.snap

Fix a bug from #5448 which wasn't setting units properly because of the order we setting up the mod-local state (across two methods).
Will be tested by https://github.com/KittyCAD/modeling-app/pull/5460 so no new tests here

Fix a units bug in multi-module projects

---

src/wasm-lib/kcl/src/execution/mod.rs

inner_run used to be recursive i didnt realize it changed, i didnt want this call to be recursive

make code dryer,

---

e2e/playwright/snapshots/prompt-to-edit/prompt-to-edit-snapshot-tests-spec-ts--change-colour.snap.json
src/clientSideScene/sceneEntities.ts
src/lang/std/sketch.ts
src/lang/std/sketchcombos.ts
src/lib/rectangleTool.ts

Fixes https://github.com/KittyCAD/modeling-app/issues/5562

Bugfix: absolute line segment dragging behavior offset was relative

---

.github/workflows/e2e-tests.yml

Quick follow up to incident discussion today.
Out of scope here but laying out some ground work for it: checkout to latest numbered release tag and run that

Scheduled e2e tests on main

---

README.md

Upload public mirror of origin modeling-app slides to README

---

rust/kcl-lib/src/execution/annotations.rs
rust/kcl-lib/src/lsp/kcl/mod.rs
rust/kcl-lib/src/lsp/tests.rs
rust/kcl-lib/src/parsing/ast/types/mod.rs
src/lang/wasm.ts

This is pretty simple and just fills the default values. We could do a proper snippet, but I'm not sure about the value of that?

Code completions for @settings

---

e2e/playwright/feature-tree-pane.spec.ts
src/lang/modifyAst.ts

Closes #5603. Adds an E2E test to verify that sketch profiles are all deleted along with the sketch.
https://github.com/user-attachments/assets/67aed78c-ed71-4a73-b891-47a8f9e99e5c

Allow users to delete sketches on offset planes via feature tree

---

vercel.json

related:
https://github.com/KittyCAD/text-to-cad-ui/pull/164
https://github.com/KittyCAD/website/pull/2766

Block indexing if host is not app.zoo.dev

---

rust/kcl-lib/src/execution/cache.rs
rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/execution/mod.rs

As requested in a previous review

Factor out a struct for the result of parse_execute

---

e2e/playwright/snapshots/prompt-to-edit/prompt-to-edit-snapshot-tests-spec-ts--change-colour.snap.json
rust/Cargo.lock
rust/kcl-bumper/Cargo.toml
rust/kcl-derive-docs/Cargo.toml
rust/kcl-language-server-release/Cargo.toml
rust/kcl-language-server/Cargo.toml
rust/kcl-lib/Cargo.toml
rust/kcl-python-bindings/Cargo.toml
rust/kcl-test-server/Cargo.toml
rust/kcl-to-core/Cargo.toml
rust/kcl-wasm-lib/Cargo.toml

i wanna test the release stuff i did on tag push

bump kcl crate versions

---

rust/kcl-lib/benches/benchmark_kcl_samples.rs

so stuff shows up better in codspeed

change test names kcl-samples

---

src/main.ts

Resolves https://github.com/KittyCAD/modeling-app/issues/5790

Fix window creation failures on Mac (most noteable in CI)

---

rust/kcl-lib/src/execution/mod.rs
src/lang/langHelpers.ts
src/lib/constants.ts

closes https://github.com/KittyCAD/modeling-app/issues/5884

fix unwrap causing panic

---

.github/workflows/update-dev-branch.yml
.github/workflows/update-e2e-branch.yml

Sync the all-e2e branch with main

---

.github/workflows/e2e-tests.yml

Vector install was failing in #5989.

ci: Fix e2e workflow to always use condition

---

e2e/playwright/projects.spec.ts
e2e/playwright/test-utils.test.ts
playwright.electron.config.ts

Amends https://github.com/KittyCAD/modeling-app/pull/5983

Ignore unit tests when running Playwright Electron

---

.github/workflows/update-e2e-branch.yml

This will amend commits from `main` to look like this on the `all-e2e` branch: https://github.com/KittyCAD/modeling-app/commit/0b524c7a92a69787a90aef89de891dd9e08b1667

Set bot user info to amend commits

---

src/lang/std/sketch.ts

Fix error: unknown sketch function circle

---

rust/kcl-lib/tests/kcl_samples/kitt/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/kitt/program_memory.snap

This should have been run.
```shell
just overwrite-sim-test kcl_samples
```

Fix kitt kcl-sample expected output

---

.envrc

Contributes to https://github.com/KittyCAD/modeling-app/issues/3973 by (optionally) letting [direnv](https://direnv.net/) populate environment variables from all _currently_ documented ways of configuring the environment. This is purely additive to what we already do but lets one use `$ env` in their shell to see the union of everything that is set.
This article provides a good overview of the use case: https://shivamarora.medium.com/a-guide-to-manage-your-environment-variables-in-a-better-way-using-direnv-2c1cd475c8e

Populate all environment variables from files

---

.github/workflows/update-e2e-branch.yml

This seems to be better: https://github.com/KittyCAD/modeling-app/commits/all-e2e/

Create a new commit to preserve history from  main

---

rust/kcl-lib/e2e/executor/cache.rs
rust/kcl-lib/src/execution/mod.rs
rust/kcl-lib/src/lib.rs
rust/kcl-wasm-lib/src/context.rs
src/lib/rustContext.ts

this breaks https://github.com/KittyCAD/modeling-app/pull/5975 into smaller chunks so as to get past playwirhgt failures from my huge change to planes

only rust changes reset scene

---

src/routes/SignIn.tsx

As a part of our final appearance tweaks work, this is just some minor cleanup ahead of renaming the app. Bump subheadings, make link buttons primary colored

Minor design tweaks to log in page

---

src/routes/SignIn.tsx

Fix 404 when clicking on the car wheel sample

---

rust/Cargo.lock
rust/Cargo.toml
rust/kcl-lib/src/std/chamfer.rs
rust/kcl-lib/src/std/fillet.rs

last part of https://github.com/KittyCAD/modeling-api/issues/566

fix api for edge cuts

---

e2e/playwright/fixtures/toolbarFixture.ts
e2e/playwright/test-utils.ts

Instead of duplicating the units that we support.
Stacked on #6107.

Change test function to share units with settings

---

rust/kcl-lib/src/docs/gen_std_tests.rs
rust/kcl-lib/src/docs/mod.rs
rust/kcl-lib/src/lsp/kcl/mod.rs
rust/rust-toolchain.toml

https://blog.rust-lang.org/2025/04/03/Rust-1.86.0.html

Upgrade to rust toolchain 1.86

---

docs/kcl/settings.md

Thanks @greg-kcio for reporting

Quick app rename typo fix in settings.md

---

Makefile

This enables `make run` to intelligently reinstall and rebuild whatever is needed when switching branches to start the web and desktop apps on:
- Linux/macOS
- Windows w/ CMD
- Windows w/ PowerShell
- Windows w/ Git Bash

Handle PowerShell vs. Git Bash on Windows

---

src/lib/operations.test.ts
src/lib/operations.ts

Fix to not filter out empty modules from the Feature Tree

---

e2e/playwright/fixtures/sceneFixture.ts
e2e/playwright/named-views.spec.ts
e2e/playwright/native-file-menu.spec.ts

We can't assume GitHub Actions will always have an excellent network connection.

Continue running tests with weak network

---

rust/kcl-lib/src/execution/types.rs

This fixes a bug where numeric coercions leaked though even though they are meant to be turned off.

Don't apply numeric adjustments in arithmetic yet

---

rust/kcl-lib/tests/big_number_angle_to_match_length_y/ast.snap
rust/kcl-lib/tests/big_number_angle_to_match_length_y/unparsed.snap
rust/kcl-lib/tests/kcl_samples/food-service-spatula/ast.snap
rust/kcl-lib/tests/kcl_samples/sheet-metal-bracket/ast.snap

Caused by admin merge in #5803

Fix bad merge with some KCL snapshots

---

e2e/playwright/prompt-to-edit.spec.ts

See: https://kittycadworkspace.slack.com/archives/C061R186RUZ/p1744240464072839

skip unreliable AI tests

---

.github/workflows/e2e-tests.yml
Makefile
e2e/playwright/lib/api-reporter.ts
playwright.config.ts
playwright.electron.config.ts

https://github.com/KittyCAD/test-analysis-bot provides a "firehose" API to collect everything we know about test runs.

Send test results to an API for analysis

---

src/lib/commandBarConfigs/modelingCommandConfig.ts

I can't believe I didn't realize they never got marked as no longer in development!

Release create and edit parameter flows to the public

---

.github/workflows/build-apps.yml

Remove step retries in build-apps after npm transition

---

src/clientSideScene/sceneEntities.ts
src/clientSideScene/segments.ts

#6367 Tangent snapping improvements

---

e2e/playwright/sketch-tests.spec.ts

This is an attempt at fixing the most common error in this unreliable test: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/461
Results from this branch: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/461?branch=increase-sketch-timeouts

Double the timeout in sketch editing test

---

e2e/playwright/onboarding-tests.spec.ts

Reverts KittyCAD/modeling-app#6356

Revert "Update onboarding interactive numbers test to use editor fixture"

---

e2e/playwright/lib/console-error-whitelist.ts
src/lang/errors.ts

Removing `fE` from the error allow list since this should give it a real message. Unfortunately, I haven't been able to observe what the new message should be.

Fix KCLError to have a real message

---

rust/kcl-lib/src/execution/artifact.rs
rust/kcl-lib/tests/intersect_cubes/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/subtract_cylinder_from_cube/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/subtract_doesnt_need_brackets/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/union_cubes/artifact_graph_flowchart.snap.md

Fix CSG commands to be included in the artifact graph

---

e2e/playwright/lib/console-error-whitelist.ts

Fix error message whitelist to use updated message

---

src/lang/KclSingleton.ts

https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1744956246749599

clean up sketch mode cmd

---

rust/Cargo.lock

Fix Cargo.lock

---

rust/kcl-lib/src/std/clone.rs

was fucking up the tests in engine

properly close the context

---

e2e/playwright/fixtures/toolbarFixture.ts
e2e/playwright/sketch-tests.spec.ts
e2e/playwright/snapshot-tests.spec.ts
e2e/playwright/various.spec.ts
src/lib/toolbar.ts

Means it the first option in the menu, want to get this in before tutorials, kinda intended to do this a while ago.

bump three point arc to be the default

---

e2e/playwright/various.spec.ts

Fixes this test: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/389?branch=fix-units-check

Update test to check for the correct units toast message

---

src/Auth.tsx
src/components/EngineStream.tsx
src/components/Loading.tsx
src/routes/Home.tsx

Feature tree loading indicator is too big and requires scroll to see

---

rust/Cargo.lock
rust/kcl-lib/Cargo.toml
rust/kcl-lib/src/execution/exec_ast.rs

This resolves a security issue.

Migrate from unmaintained tempdir to tempfile

---

known-circular.txt
package.json

Fixes: https://github.com/KittyCAD/modeling-app/actions/runs/14677571075/job/41196471368
cc @Irev-Dev

Remove syntax not supported on all platforms

---

src/clientSideScene/ClientSideSceneComp.tsx
src/clientSideScene/sceneEntities.ts
src/lang/modifyAst.ts
src/lang/modifyAst/addEdgeTreatment.test.ts
src/lang/modifyAst/addEdgeTreatment.ts
src/lang/modifyAst/tagManagement.ts
src/lang/std/sketch.test.ts
src/lang/std/sketch.ts
src/lang/std/sketchcombos.ts

Post-kwargs cleanup

---

src/lib/toolbar.ts

From https://kittycadworkspace.slack.com/archives/C07A80B83FS/p1745521355623889

Remove unused Arc button from toolbar

---

e2e/playwright/app-header-tests.spec.ts
e2e/playwright/lib/api-reporter.ts

Closes https://github.com/KittyCAD/test-analysis-bot/issues/26

Notify TAB API to share a summary report on PRs

---

src/components/Providers/SystemIOProviderDesktop.tsx
src/machines/systemIO/systemIOMachine.ts
src/machines/systemIO/utils.ts

Looks like something managed to get in after https://github.com/KittyCAD/modeling-app/pull/6558

Fix lint after #6558

---

rust/Cargo.lock
rust/kcl-bumper/Cargo.toml
rust/kcl-derive-docs/Cargo.toml
rust/kcl-directory-test-macro/Cargo.toml
rust/kcl-language-server-release/Cargo.toml
rust/kcl-language-server/Cargo.toml
rust/kcl-lib/Cargo.toml
rust/kcl-python-bindings/Cargo.toml
rust/kcl-test-server/Cargo.toml
rust/kcl-to-core/Cargo.toml
rust/kcl-wasm-lib/Cargo.toml

i wont publish til before release tomorrow just in case more things merge over night!

bump kcl and friends in prep for release

---

rust/kcl-lib/src/docs/mod.rs
rust/kcl-lib/src/lsp/tests.rs

enhance the signature help

---

flake.lock
packages/codemirror-lsp-client/src/plugin/lsp.ts
rust/Cargo.lock
rust/kcl-lib/Cargo.toml
rust/kcl-lib/src/execution/geometry.rs
rust/kcl-lib/src/lint/checks/default_plane.rs
rust/kcl-lib/src/lsp/kcl/mod.rs
rust/kcl-lib/src/lsp/tests.rs
rust/kcl-lib/src/parsing/ast/types/literal_value.rs
rust/kcl-lib/src/parsing/ast/types/mod.rs

- prepare_rename
- document_color

More lsp endpoints we were missing

---

e2e/playwright/native-file-menu.spec.ts
e2e/playwright/projects.spec.ts
src/routes/Home.tsx

Wrong case in no-projects copy on homepage

---

.github/workflows/generate-website-docs.yml

Account for the changed directories in a previous PR

Fix the generate docs action

---

src/Auth.tsx
src/routes/Home.tsx

This one is to calm my brain while loading the home page, sorry for the untracked work.
https://github.com/user-attachments/assets/39de3227-bdfd-4808-a8c4-9dcf380c7955

Fix layout shift on home page, fix narrow screen layout

---

.gitignore
flake.nix
package-lock.json
package.json
vite.config.ts

docs here for vscode plugin: https://million.dev/docs
thread here for context https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1743813695038529?thread_ts=1743812948.131899&cid=C04KFV6NKL0
i think this will help us find bugs

add million lint in dev mode

---

e2e/playwright/point-click-assemblies.spec.ts
src/lang/modifyAst/setTransform.ts
src/machines/modelingMachine.ts

Fixes #6667 and #6665 
https://github.com/user-attachments/assets/6021dea2-c250-4383-8be1-464f5aa3b683

Catch import scene selection on transforms and point to the feature tree

---

.codespellrc

Add
- ./test-results
- ./playwright-report
- ./kcl-book/book

Update codespell ignore

---

src/hooks/useEngineConnectionSubscriptions.ts

https://kittycadworkspace.slack.com/archives/C07A80B83FS/p1745513007523059?thread_ts=1745512110.779589&cid=C07A80B83FS

Fix "Cannot read properties of undefined (reading '0')" error

---

src/Root.tsx

5s is way too fast, let's try 60s.

Reducing polling interval

---

e2e/playwright/sketch-tests.spec.ts

fix sketch on boolean test

---

e2e/playwright/point-click-assemblies.spec.ts
package-lock.json
src/components/ModelingSidebar/ModelingPanes/FeatureTreePane.tsx

Thanks @jacebrowning for digging this up! https://kittycadworkspace.slack.com/archives/C07A80B83FS/p1746580190774329

Remove fixme on foreign import assembly test

---

e2e/playwright/command-bar-tests.spec.ts
e2e/playwright/share-link.spec.ts

Tests added in #6768 and #6619

Add @web tag to new web-only tests for later CI use

---

CONTRIBUTING.md

Probably some others, but this one seems like an obvious place for folks to look and be mislead.

Remove dev.zoo.dev from contributing

---

.github/ci-cd-scripts/upload-results.sh
.github/workflows/cargo-test.yml
rust/.config/nextest.toml
rust/justfile

This is already implemented on the API: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app?search=nextest&enabled=all

Create JUnit reports from Rust tests

---

rust/kcl-lib/src/execution/types.rs
rust/kcl-lib/src/std/args.rs
rust/kcl-lib/src/std/edge.rs
rust/kcl-lib/tests/panic_repro_cube/execution_error.snap

cc https://github.com/KittyCAD/modeling-app/pull/6825

Proper type-checking where a function requires a tag identifier not just a tag

---

.github/ci-cd-scripts/upload-results.sh
.github/workflows/cargo-test.yml

This updates https://github.com/KittyCAD/modeling-app/pull/6743 to match what we send with Playwright results: https://github.com/KittyCAD/modeling-app/blob/main/e2e/playwright/lib/api-reporter.ts

Include metadata environment variables with results

---

docs/kcl-std/extrude.md
rust/kcl-lib/src/docs/gen_std_tests.rs
rust/kcl-lib/src/docs/mod.rs
rust/kcl-lib/src/std/extrude.rs

Don't truncate extrude arg docs

---

package-lock.json

If you have this, run `npm prune`.

Fix to remove extraneous from package.json

---

src/components/ModelingSidebar/ModelingPanes/index.tsx
src/components/ModelingSidebar/ModelingSidebar.tsx

Fixes #6847
Single digit
Multi digit (not looking that good IMO but better than no growing at all)

Fix kcl errors indicator not scaling with multi-digit count

---

.github/workflows/build-apps.yml
scripts/flip-files-to-nightly.sh
scripts/invalidate-files-bucket.sh
src/main.ts

Follow up to #6871 
Tested locally https://dl.zoo.dev/releases/modeling-app/test/nightly/last_download.json (see commit history)

Clean up Nightly release version & notes

---

src/components/ProjectSearchBar.tsx

dumb little zero-thought bit of polish.

Spell out shortcut in project search bar

---

src/components/ModelingSidebar/ModelingPanes/index.tsx

lol we had a custom bug icon in the codebase, no clue why I didn't update the pane config.

Update bug icon to not use FontAwesome

---

e2e/playwright/regression-tests.spec.ts

Contributes to https://github.com/KittyCAD/modeling-app/issues/2978 by addressing flakiness in this test: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/241?branch=fix-test-order

Fix test by closing code pane after loading the scene

---

.github/workflows/build-apps.yml

https://kittycadworkspace.slack.com/archives/C07A80B83FS/p1747158610743399?thread_ts=1747062892.971869&cid=C07A80B83FS

Prevent concurrent runs of build-apps on main

---

docs/kcl-std/sweep.md
e2e/playwright/desktop-export.spec.ts
rust/Cargo.lock
rust/kcl-lib/src/std/sweep.rs
rust/kcl-lib/tests/kcl_samples/bench/artifact_commands.snap
rust/kcl-lib/tests/kcl_samples/cold-plate/artifact_commands.snap
rust/kcl-lib/tests/kcl_samples/cpu-cooler/artifact_commands.snap
rust/kcl-lib/tests/kcl_samples/exhaust-manifold/artifact_commands.snap
rust/kcl-lib/tests/kcl_samples/utility-sink/artifact_commands.snap
rust/kcl-lib/tests/subtract_regression03/artifact_commands.snap
rust/kcl-lib/tests/subtract_regression05/artifact_commands.snap

Closes https://github.com/KittyCAD/engine/issues/3115

Support new sweep flag

---

rust/kcl-lib/src/parsing/parser.rs

Closes <https://github.com/KittyCAD/modeling-app/issues/6924>

Sensible parser error when using keyword as arg label

---

e2e/playwright/test-utils.ts

Closes #6988 
See the results from this branch here: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/219?branch=remove-sketch-check

Remove check on the Start Sketch button

---

.github/workflows/kcl-language-server.yml
.github/workflows/kcl-python-bindings.yml

Reverts KittyCAD/modeling-app#7027

Revert "stupid paths filtering"

---

src/lib/settings/initialSettings.tsx
src/lib/settings/settingsUtils.ts

Fixes #6432. Looks like this was just referencing the wrong var...
https://github.com/user-attachments/assets/c6e8884a-f2f5-482a-a073-cc5aa80ffb88

Fix reset project dir setting

---

docs/kcl-lang/modules.md
rust/kcl-lib/src/parsing/ast/types/mod.rs
rust/kcl-lib/src/parsing/parser.rs
rust/kcl-lib/tests/nested_windows_main_kcl/ast.snap
rust/kcl-lib/tests/nested_windows_main_kcl/input.kcl
rust/kcl-lib/tests/nested_windows_main_kcl/unparsed.snap

Using the subdirectory name for the variable name. Also updates module docs.

Restrict subdirectory imports to main.kcl

---

.github/workflows/e2e-tests.yml

Amends https://github.com/KittyCAD/modeling-app/pull/7101

Always update snapshots if needed

---

rust/kcl-lib/src/simulation_tests.rs
rust/kcl-lib/tests/import_only_at_top_level/artifact_commands.snap
rust/kcl-lib/tests/import_only_at_top_level/artifact_graph_flowchart.snap
rust/kcl-lib/tests/import_only_at_top_level/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/import_only_at_top_level/ast.snap
rust/kcl-lib/tests/import_only_at_top_level/execution_error.snap
rust/kcl-lib/tests/import_only_at_top_level/input.kcl
rust/kcl-lib/tests/import_only_at_top_level/ops.snap
rust/kcl-lib/tests/import_only_at_top_level/unparsed.snap
rust/kcl-lib/tests/import_only_at_top_level/unparsed@empty.kcl.snap

test: Add regression test for importing only at the top level

---

.github/ci-cd-scripts/upload-results.sh
.github/workflows/cargo-test.yml
.github/workflows/e2e-tests.yml
e2e/playwright/lib/api-reporter.ts

Contributes to https://github.com/KittyCAD/test-analysis-bot/issues/35

Identify distinct test suites

---

e2e/playwright/projects.spec.ts

View the new results here: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/results?search=nested+directory&branch=test-nested-import&platform=&show=all

Test nested imports on all platforms

---

rust/kcl-derive-docs/src/example_tests.rs
rust/kcl-derive-docs/src/lib.rs
rust/kcl-lib/src/docs/kcl_doc.rs

Please forgive me for this gross-ness, but we do run tests one at a time :-)

Run std lib example tests one at a time

---

src/components/DownloadAppToast.tsx

Chrome toast touchup

---

rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/execution/fn_call.rs
rust/kcl-lib/src/execution/types.rs
rust/kcl-lib/src/std/args.rs
rust/kcl-lib/src/std/patterns.rs

Fix ascription to array type to not convert units

---

CONTRIBUTING.md

Clarify release instructions

---

rust/kcl-lib/src/parsing/ast/types/mod.rs

fix symbol rename for unlabeled arg

---

e2e/playwright/test-network-and-connection-issues.spec.ts
e2e/playwright/test-utils.ts
src/App.tsx
src/clientSideScene/sceneEntities.ts
src/components/EngineStream.tsx
src/hooks/useNetworkStatus.tsx
src/lang/std/engineConnection.ts
src/lib/selections.ts
src/machines/engineStreamMachine.ts

https://github.com/user-attachments/assets/98331f27-2d7d-4018-b7c7-b542bb531c50
Need to clean up PR but I wanted to show that it no longer shows the weird black screen ^
Note that this uses the browser's online/offline events, and that **they may not be always accurate, especially for WiFi**.
I've tried for a good few hours to make it use heuristics but it was bad any which way I did it. I'm sure there's a way but it's not worth the weird cases right now. I would have rather developed a full networking code stack with this in mind from scratch.

Fix the black screen of death

---

src/lang/std/sketch.ts

Relates to https://github.com/KittyCAD/modeling-app/pull/7247

Fix to not have infinite console errors editing tangentialArc

---

src/components/ToastUpdate.tsx

Fix whitespace in updater toast

---

rust/Cargo.lock
rust/kcl-lib/Cargo.toml
rust/kcl-lib/src/engine/conn.rs

https://github.com/snapview/tungstenite-rs/blob/master/CHANGELOG.md#0260
This should unblock Dependabot.

Bump tokio-tungstenite from 0.24.0 to 0.26.2

---

rust/Cargo.lock
rust/kcl-lib/Cargo.toml
rust/kcl-lib/benches/benchmark_kcl_samples.rs
rust/kcl-lib/benches/compiler_benchmark_criterion.rs
rust/kcl-lib/benches/lsp_semantic_tokens_benchmark_criterion.rs

https://github.com/bheisler/criterion.rs/blob/master/CHANGELOG.md#060---2025-05-17

Bump criterion from 0.5.1 to 0.6.0

---

rust/kcl-lib/src/engine/conn.rs

bump the client API response timeout 60 -> 300

---

.github/workflows/build-apps.yml
.github/workflows/publish-apps-release.yml

Follow up https://github.com/KittyCAD/modeling-app/pull/7400#discussion_r2132931200

Clean up build-apps upload artifact names

---

src/components/EngineStream.tsx
src/lang/KclSingleton.ts

@JordanNoone has cases of wanting to render models that take way beyond 5 minutes, but this is problematic with the idle timeout.
Additionally, users may have long-executing models, and leave their chair, and come back to export it, only to find that the application went into idle mode, so they need to render again.
The solution is, idle mode timeout is _extended_ to 8 hours on anything that takes longer than 5 minutes to execute. The choice comes from someone who leaves their chair and goes to work for the day, to come back home to their render and do something with the result.

Extend idle threshold to 8 hours if execution takes longer than 5 min.

---

e2e/playwright/command-bar-tests.spec.ts
e2e/playwright/feature-tree-pane.spec.ts
e2e/playwright/fixtures/cmdBarFixture.ts
e2e/playwright/point-click.spec.ts
src/components/CommandBar/CommandBarKclInput.tsx

Fixes #7252
https://github.com/user-attachments/assets/dfaf2442-0238-478c-8753-6b1699be3bbe

Checkbox for variable creation in command bar flows

---

src/components/EngineStream.tsx
src/components/Loading.tsx

https://github.com/user-attachments/assets/ba5d5667-ee61-4774-8e7a-852f7e25fb8d

Show a countdown on reconnect

---

.github/ISSUE_TEMPLATE/release.md

Improve release template regarding updater checks

---

rust/kcl-lib/src/std/csg.rs

Closes #7459
Breaking but a bug fix, so OK

Convert units of tolerance for CSG functions

---

src/lib/commandBarConfigs/modelingCommandConfig.ts

Keep subtract solids selection to one until engine supports multiple

---

rust/kcl-lib/tests/kcl_samples/multi-axis-robot/artifact_commands.snap
rust/kcl-lib/tests/kcl_samples/multi-axis-robot/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/multi-axis-robot/ops.snap

This was failing for me on an unrelated PR. Introduced in #7624. I just regenerated sim test output for the one sample that was failing.
```shell
just overwrite-sim-test-sample multi_axis_robot
```

Update output to match main

---

jest-component-unit-tests/billing.jesttest.tsx
src/components/BillingDialog.tsx
src/routes/Home.tsx

Enterprise plans should not have the upgrade button

---

.envrc
.gitignore

Remove another unused way of setting Playwright sercrets

---

src/lang/modifyAst/sweeps.test.ts
src/lang/modifyAst/sweeps.ts
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/operations.ts
src/machines/modelingMachine.ts

Added the new extrude method to the point-and-click flow, make sure it is populated in the feature tree and add a new test

Add extrude method to point-and-click

---

e2e/playwright/fixtures/fixtureSetup.ts
interface.d.ts
src/components/CommandBar/CommandBarPathInput.tsx
src/lib/desktop.ts
src/lib/exportSave.ts
src/lib/isPlaywright.ts
src/lib/routeLoaders.ts
src/main.ts
src/preload.ts

Contributes to https://github.com/KittyCAD/modeling-app/issues/3973

Prefer builtin NODE_ENV over custom Playwright environment variable

---

rust/kcl-lib/src/parsing/parser.rs

KCL: If expressions can be used with math

---

rust/kcl-lib/src/engine/mod.rs

Resolves #7788.
I used a sim test to find this, but I don't really think we should commit it since hopefully the engine will update it.

Fix to have an error message when the engine gives none

---

src/components/Loading.tsx

Fix https://kittycadworkspace.slack.com/archives/C06L2RHP9SL/p1752853392128269

Loading component links to open externally if desktop app

---

rust/kcl-lib/src/parsing/parser.rs

These aren't needed, but on ARM64 MacOS it didn't make a difference to benchmarks, so I assume it's been optimized out by the compiler.

KCL: Remove clones in parser

---

src/components/SetAngleLengthModal.tsx

https://github.com/user-attachments/assets/ac8cec92-1abf-4520-be50-21cf59e101e1
The disable button did not take into account the checkbox state.
Maybe resolves #7929

[FIX] don't disable angle on non-unique name, if create var checkbox is unchecked

---

rust/Cargo.lock
rust/Cargo.toml
rust/kcl-lib/src/execution/geometry.rs
rust/kcl-lib/src/std/shapes.rs
rust/kcl-lib/src/std/sketch.rs
rust/kcl-lib/std/sketch.kcl
rust/kcl-lib/tests/elliptic_curve_inches_regression/ast.snap
rust/kcl-lib/tests/elliptic_curve_inches_regression/input.kcl
rust/kcl-lib/tests/elliptic_curve_inches_regression/unparsed.snap

This reverts commit f606b9b4d16cd0e8a79d51e22125532b36eef6be.
Shouldn't have been merged as the relevant engine PR isn't ready

Revert "Major axis of ellipse (#7953)"

---

src/components/MlEphantConversation.tsx
src/components/PromptCard.tsx
src/index.css
src/lib/promptToEdit.tsx
src/routes/Home.tsx

Just a few CSS tweaks for dark/light theming, a bit of adjustment to the tabs on the home page, the prompt card action button, and the prompt pane within the modeling view. Following up on #7542.

CSS tweaks follow to TTC UI

---

src/components/CommandBarOpenButton.tsx
src/routes/Onboarding/BrowserOnboardingRoutes.tsx
src/routes/Onboarding/DesktopOnboardingRoutes.tsx

Update onboarding with new conversational ttc ui

---

rust/Cargo.lock
rust/Cargo.toml
rust/ezpz/Cargo.toml
rust/justfile
rust/kcl-api/Cargo.toml
rust/kcl-lib/src/execution/types.rs
rust/kcl-lib/src/lib.rs
rust/kcl-lib/src/lsp/kcl/custom_notifications.rs
rust/kcl-lib/src/settings/types/mod.rs
rust/kcl-lib/src/settings/types/project.rs
rust/kcl-python-bindings/kcl.pyi
rust/kcl-python-bindings/pyproject.toml
rust/kcl-python-bindings/src/lib.rs
rust/kcl-python-bindings/tests/tests.py

Reverts KittyCAD/modeling-app#8199

Revert "expose relevant file types to python "

---

docs/kcl-lang/settings/user.md
rust/kcl-lib/src/settings/types/mod.rs
src/lib/settings/initialSettings.tsx
src/lib/settings/settingsUtils.ts

See: https://kittycadworkspace.slack.com/archives/C061R186RUZ/p1756592997086649?thread_ts=1756316209.654749&cid=C061R186RUZ
remove some unrelated cases of "dev-only" trying to call this pre-production.

setting for copilot (pre-production)

---

docs/kcl-lang/settings/user.md
rust/kcl-lib/src/settings/types/mod.rs
src/lib/settings/initialSettings.tsx
src/lib/settings/settingsUtils.ts

Reverts KittyCAD/modeling-app#8187 because of this issue: [Slack thread](https://kittycadworkspace.slack.com/archives/C07A80B83FS/p1756934087440939?thread_ts=1756929519.302229&cid=C07A80B83FS)

Revert "setting for copilot (pre-production)"

---

src/components/MlEphantConversation.tsx
src/components/ModelingSidebar/ModelingPanes/MlEphantConversationPane.tsx
src/machines/mlEphantManagerMachine.ts

Resolves:
* Spamming prompts will overwrite the project as the responses are received
* Mousing over the prompt submit button removes the color (in light and dark theme)
* Closing the app while a prompt is running can get the TTC pane stuck on “Processing…”

Lee at zoo corp/queue up queued prompts

---

package-lock.json
package.json
src/components/StatusBar/defaultStatusBarItems.tsx
src/machines/billingMachine.ts

Fixes #8300
Needs https://github.com/KittyCAD/react-shared/pull/18 and https://github.com/KittyCAD/react-shared/pull/19

No tooltip if billing error and fix billing error typing in machine

---

.github/workflows/flakehub.yml

Update flakehub.yml (org name is zoo)

---

.github/workflows/build-and-store-wasm.yml
.github/workflows/build-apps.yml

https://kittycadworkspace.slack.com/archives/C06P9L5MCUD/p1758297499193809
Similar to #8343

Update two more build:wasm jobs to 8 cores

---

rust/Cargo.lock
rust/Cargo.toml
rust/kcl-api/Cargo.toml
rust/kcl-bumper/Cargo.toml
rust/kcl-derive-docs/Cargo.toml
rust/kcl-directory-test-macro/Cargo.toml
rust/kcl-error/Cargo.toml
rust/kcl-language-server-release/Cargo.toml
rust/kcl-language-server/Cargo.toml
rust/kcl-lib/Cargo.toml
rust/kcl-lib/src/std/shapes.rs
rust/kcl-lib/src/std/sketch.rs
rust/kcl-python-bindings/Cargo.toml
rust/kcl-test-server/Cargo.toml
rust/kcl-to-core/Cargo.toml
rust/kcl-to-core/src/conn_mock_core.rs
rust/kcl-wasm-lib/Cargo.toml

this is needed to bump kittycad.rs in https://github.com/KittyCAD/cli/pull/1344 i forgot modeling-cmds imports kittycad.rs as well

bump modeling-cmds and friends

---

Makefile
src/components/CustomIcon.tsx
src/components/MlEphantConversation2.tsx
src/components/ModelingSidebar/ModelingPanes/MlEphantConversationPane2.tsx
src/machines/mlEphantManagerMachine2.ts

https://github.com/user-attachments/assets/c1e1c099-5e83-4850-917b-57e73c8eb210

Add ability to force tools

---

package-lock.json
package.json

prereq for https://github.com/KittyCAD/modeling-app/pull/8457

chore: bumping package to 3.2.4
