src/Toolbar.tsx

Previously the toolbar would not scroll when a vertical mouse wheel event occurred - which forced the user to drag the scroll bar horizontally to scroll, or use a horizontal scroll wheel (if their mouse has one).
This PR allows vertical scrolling to affect the horizontal scroll of the toolbar. Since there is no vertical scrolling space available here, the default vertical scrolling behaviour can be used as horizontal scrolling for a better UX.
Demo vid:
https://github.com/KittyCAD/modeling-app/assets/9722062/3981dcbb-8fa4-4ec2-af52-515d549ddf65

Allow Vertical Scroll Wheel to affect Horizontal Scroll for Toolbar

---

src/App.test.tsx
src/Router.tsx
src/components/ErrorPage.tsx
src/components/UserSidebarMenu.test.tsx
src/components/UserSidebarMenu.tsx
src/hooks/useAbsoluteFilePath.ts
src/routes/Onboarding/index.tsx

Fixes #774 by using absolute paths to get to the `/file/:id/settings` page, making it possible to click the Settings button in the sidebar from anywhere—whether in a normal file view (`/file/:id`), or deep in the onboarding (`/file/:id/onboarding/cmd-bar`).
Had to start reworking how we wrap UI tests now that we use what react-router calls its "[v6.4 Data APIs](https://reactrouter.com/en/6.16.0/routers/picking-a-router#using-v64-data-apis)" within components that we have tests for.
1. Open a project in the Tauri or browser app versions
2. Restart onboarding from the `/settings` page
3. Go through the onboarding until you can access the menus (I believe the Cmd + K bar step is the earliest)
4. Open the right side user menu, then click on the Settings button
5. The app should no longer …

Use absolute URLs to settings to avoid relative URL edge cases

---

src/components/UserSidebarMenu.tsx
src/routes/Onboarding/Introduction.tsx
src/routes/Onboarding/index.tsx
src/routes/Settings.tsx

Resolves #728.
- If the user clicks the button from `/home/settings`, a new file with the title "Tutorial Project 00" (number auto-increments) is created and opened to the onboarding.
- If the user clicks from within a file's settings, they are taken through the usual flow depending on if their file has changed content or not.
https://github.com/KittyCAD/modeling-app/assets/23481541/03dc6f16-f896-48ed-9bea-317731637496

Make "Replay Onboarding" button available on home settings page

---

src/lang/KclSinglton.tsx

We added a [KclSinglton](https://github.com/kittycad/modeling-app/blob/fix-code-loader-race/src/lang/KclSinglton.tsx) singleton to prepare for migration of all source code management to Rust. When we instantiate this, we weren't respecting the new code provided to the modeling app via [the loader on the `/file/:id` route](https://github.com/kittycad/modeling-app/blob/fix-code-loader-race/src/Router.tsx#L155-L202), which reads from the file system.
This resulted in multiple updates to the value of `code`, leading to a mismatch that left the CodeMirror component with an empty value, but only when navigating between projects via client-side navigation.
This small change remedies that by instantiating the KclSinglton's `code` value with the route loader data, ensuring everything loads on the …

Use route loader data to instantiate the kcl code

---

package.json
src/lang/KclSinglton.tsx
src/lang/abstractSyntaxTree.test.ts
src/lang/modifyAst.test.ts
src/lang/modifyAst.ts
src/lang/recast.test.ts
src/lang/std/sketch.test.ts
src/useStore.ts
src/wasm-lib/kcl/benches/compiler_benchmark.rs
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/errors.rs
src/wasm-lib/kcl/src/parser.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs
src/wasm-lib/kcl/src/parser/parser_impl/error.rs
src/wasm-lib/kcl/src/token.rs
src/wasm-lib/tests/executor/inputs/cube.kcl
src/wasm-lib/tests/executor/main.rs

This new parser uses [winnow](docs.rs/winnow) to replace the handwritten recursive parser.
I think the Winnow parser is more readable than handwritten one, due to reusing standard combinators. If you have a parsre like `p` or `q` you can combine them with standard functions like `repeat(0..4, p)`, `opt(p)`, `alt((p, q))` and `separated1(p, ", ")`. This IMO makes it more readable once you know what those standard functions do.
It's also more accurate now -- e.g. the parser no longer swallows whitespace between comments, or inserts it where there was none before. It no longer changes // comments to /* comments depending on the surrounding whitespace. 
Primary form of testing was running the same KCL program through both the old and new parsers and asserting that both parsers produce the …

New parser built in Winnow

---

src/components/ModelingMachineProvider.tsx
src/lang/std/engineConnection.ts

Fixes part of #843 
The creating new sketch goes via the `Sketch no face state`, and triggers `Select default plane` event which has a few actions. The last of which creates the path, we just needed to hold onto that path id, and that's what this diff is.

save path id on path create

---

src/Router.tsx
src/components/AppHeader.tsx
src/components/FileMachineProvider.tsx
src/components/ProjectSidebarMenu.tsx
src/hooks/useAbsoluteFilePath.ts
src/lib/tauriFS.ts
src/routes/Home.tsx
src/routes/Onboarding/Export.tsx
src/routes/Onboarding/FutureWork.tsx
src/routes/Onboarding/Introduction.tsx
src/routes/Onboarding/Sketching.tsx
src/routes/Settings.tsx

Fixes #881 by replacing all instances of `/` with [the Tauri `sep` utility](https://tauri.app/v1/api/js/path/#sep) wherever we are constructing paths meant for reading from and writing to the file system.
The Windows builds were broken because in the refactor to reference specific files instead of just the project path, I was manually building the path to the file with a `/` character, which of course led to files not reading correctly on Windows systems.
Here is a working Windows build after the changes in this PR:
https://github.com/KittyCAD/modeling-app/assets/23481541/7fa6f526-b559-4cdb-afc9-d2f31c3f91b2

Use platform-agnostic file separators

---

src/components/ModelingMachineProvider.tsx
src/lang/std/sketch.test.ts
src/lang/std/sketch.ts
src/lang/std/stdTypes.ts

Ostensibly this was to fix a bug where if create a second sketch, only the first segment would trigger code gen, the rest would fail.
But with this, we're actually hitting into an issue of us moving away from execute-everytime, to not. And basically, we need to stop querying programMemory, and get that information from elsewhere, namely the engine.
I've added a TODO for removing programMemory from `SketchLineHelper`/`ModifyAstBase`. Full write up here https://github.com/KittyCAD/modeling-app/issues/896

don't query program memory for add sketch line

---

src/components/ModelingMachineProvider.tsx
src/components/TextEditor.tsx
src/lang/KclSinglton.tsx
src/machines/modelingMachine.ts
src/machines/modelingMachine.typegen.ts

Nice quality of life fix (all of these kinds of bugs are so much easier to solve with XState 🎉 because its so easy to figure out where the solution needs to go in the diagram)
Implemented a on-execute call back that triggers an XState action so that we can put the engine back into edit/sketch mode for the new ids that are generated from a fresh execute
https://github.com/KittyCAD/modeling-app/assets/29681384/868c6609-d912-444f-a2a7-d8f855e8dfac
@franknoirot one thing I'm curious about is I had to add the same event with the same three actions in three places for sketchId, line tool and move tool, because the event needs to be available in all three of these states. I think that's the correct way to do that but not 100% sure?

honour sketch mode after execute

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/ast/types/literal_value.rs
src/wasm-lib/kcl/src/parser.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs

WASM still sends the KCL literal values back to the JS side as JSON values. But within WASM, our code tracks KCL literal values as an enum with several different variants.
This slows parser down by 4.5% to 8.5% depending on the benchmark, but IMO it's worth it.

KCL literals are typed, not JSON values

---

.github/workflows/ci.yml

Release builds are very slow and should only be used for actual releases. Fast debug builds should be used for CI on PRs.

Build tauri app in debug mode on PRs, release mode on releases

---

src/hooks/useSetupEngineManager.ts

We should not use react listeners like this for executing because we are handling files opening and closing while keeping the stream open and so that open close logic should handle re-executes. Since the x-state migration and moving kcl state inte the kcl-singleton, react listeners should not be involved with triggering re-executions.
Continues some of the work from #897.
Related to #959

stop double execute on project open

---

src/routes/Onboarding/Introduction.tsx

#862 was resolved by #897 
however I did find a bug when double checking that this PR fixes so I'll say
Resolves #862 
The bug was that when you clicked "make a new project" as part of the onboarding replay, it would overwrite the user's current file with the bracket code.

don't overwrite current file on onboarding-replay

---

src/components/Stream.tsx
src/lang/KclSinglton.tsx

added a safeParse method to the `kclSingleton` that adds errors correctly.
There are still uses of `parse` as there are situations where we're parsing code out side of the user's ux loop
resolves https://github.com/KittyCAD/modeling-app/issues/994

safe parse

---

src/wasm-lib/kcl/src/parser/parser_impl.rs

@jessfraz I made a unit test for the invalid program in https://github.com/KittyCAD/modeling-app/issues/995. The test checks that this invalid program fails. And it _does_ fail -- so I'm not sure what was going on with your issue?
Closes #995

Test Jess's KCL error

---

src/hooks/useEngineConnectionSubscriptions.ts

I can't say I understand why, but when the frontend sent a bad `path_get_curve_uuids_for_vertices` request to the backend, it would break the selections stuff 🤷

fix selections

---

package.json
src-tauri/tauri.conf.json

Cutting a release for a regression I introduced in #1013 
PRs in this release:
- selections fix follow up (#1019)
- Neaten up stdlib code (#1017)

Cut release v0.11.3

---

src/wasm-lib/.config/nextest.toml
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs
src/wasm-lib/kcl/src/parser/snapshots/kcl_lib__parser__parser_impl__snapshot_tests__au.snap
src/wasm-lib/kcl/src/std/kcl_stdlib.rs
src/wasm-lib/kcl/src/std/mod.rs
src/wasm-lib/kcl/src/std/shapes.rs
src/wasm-lib/tests/executor/inputs/cylinder.kcl

Allows stdlib functions to be written as KCL, not as Rust. Rust stdlib functions will hereafter be referred to as "core" not "std".
https://github.com/KittyCAD/modeling-app/assets/5407457/4310b604-2666-43ec-b7d2-5947e8ec0a7e
Right now the only stdlib function I implemented is a circle function (it's a wrapper around the core `arc` function which sets the arc's start/end to 0 and 360 respectively). I know I want to change this function as soon as KCL has enums, which is my next task. So, I don't want users to start using this right away. To that end, I've named this function "unstable_stdlib_circle" not "circle". Once the function is ready to be stabilized, I can rename it to just "circle".
Note that this PR modifies the [existing "sketch and extrude a cylinder" KCL …

KCL stdlib and circle function

---

src/wasm-lib/Cargo.lock
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/ast/types/literal_value.rs

Databake doesn't have any derive for HashMap, so for NonCodeMeta I decided to skip serializing the non_code_nodes. This should be OK for now.
See <https://github.com/unicode-org/icu4x/issues/4266> for the Databake hashmap issue.

Impl databake for all AST node types

---

src/lang/std/engineConnection.ts

This is purely cosmetic right now, but I want to try and make it easier to tell when the browser is unable to communicate with the ICE server by writing it to the console.
I want to add some Sentry logging in the future, but for now, when we see a stream failing to start, we can at least see what I suspect is the most common trigger in the console.

Add a console.error when ICE fails

---

src-tauri/Cargo.lock
src/hooks/useSetupEngineManager.ts
src/lang/std/engineConnection.ts
src/lib/utils.ts

I put in limits on the API side to prevent huge resolutions. But, we still have a few cases where modeling app will request a bigger resolution, like full screen on my biggest monitor.
An unfortunate side-effect of this is that we'll also need to scale the resolution of all mouse events, but I'll do some testing to be sure.

Fit resolutions to less than 2k x 2k

---

package.json
src-tauri/tauri.conf.json

```
- Add first KCL stdlib and circle function (#1029)
- Fit resolutions to less than 2k x 2k (#1065)
- Add a console.error when ICE fails (#1067)
- Disable eslint rule `react-hooks/exhaustive-deps` (#1055)
- Macro for parsing KCL at Rust compile-time (#1049)
- Implement databake for all AST node types (#1047)
- Add top level expressions fix (#1046)
- Describe Rust version for devs (#1044)
- AST function nodes no longer have stdlib function members (#1031)
- Test with a circle function (#1030)
- Refactor the call_fn fn to be more readable (#1028)
- Fix auto-version in nightly builds (#1026)
- Fix epsilon bug (#1025)
```

Cut release v0.12.0

---

src/lang/abstractSyntaxTree.test.ts
src/lang/getNodePathFromSourceRange.test.ts
src/lang/queryAst.ts
src/lang/wasm.ts
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs
src/wasm-lib/kcl/src/parser/snapshots/kcl_lib__parser__parser_impl__snapshot_tests__ae.snap
src/wasm-lib/kcl/src/parser/snapshots/kcl_lib__parser__parser_impl__snapshot_tests__av.snap
src/wasm-lib/kcl/src/token.rs
src/wasm-lib/kcl/src/token/tokeniser.rs

Part of https://github.com/KittyCAD/modeling-app/issues/1006#issuecomment-1816978586
This adds support for optional parameters to the AST. They are declared with a ? suffix, e.g. `(x, tag?) => {...}`.
This PR does not actually _use_ these optional parameters anywhere. In particular, it does not change the KCL stdlib or any existing function definitions. That will happen in a follow-up PR.

KCL optional parameters

---

e2e/playwright/flow-tests.spec.ts
e2e/playwright/secrets.ts
package.json
yarn.lock

Uses [wait-on](https://www.npmjs.com/package/wait-on) to wait for a TCP connection on port `3000` before running any Playwright tests. This solves a persistent issue I was seeing where the first flow test would always fail with a `ERR_CONNECTION_REFUSED` before Vite had even started up, following [this guidance from a Playwright maintainer](https://github.com/vitejs/vite/issues/12883#issuecomment-1511571837).
Also solves a tiny issue I ran into when getting started, where I introduced an additional newline character into my `playwright-secrets.env` file, quietly breaking the function where we assembled the secrets object.

Ensure Vite preview server is running before running any Playwright tests

---

e2e/playwright/flow-tests.spec.ts
src/routes/Onboarding/Export.tsx
src/routes/Onboarding/Sketching.tsx
src/routes/Onboarding/index.tsx

Resolves #1110, adds a test for onboarding that tests the following:
- The app redirects users with valid onboarding state in localStorage get redirected to that page in onboarding
- Reloading the page keeps them at the same URL
- The onboarding content loads properly
- Advancing to the "Sketching" step clears that code
- Advancing to the "Next Steps" step resets the code to be non-empty.

Add Playwright tests for onboarding

---

e2e/playwright/flow-tests.spec.ts
e2e/playwright/snapshot-tests.spec.ts
e2e/playwright/test-utils.ts
playwright.config.ts
src/components/EngineCommands.tsx
src/editor/highlightextension.ts
src/lang/std/engineConnection.ts
tsconfig.json

related to https://github.com/KittyCAD/modeling-app/issues/833
The tests mapping works on fresh sketch and edited sketch, tests using hovers which is the same as selections, because if source ranges are wrong, hovers won't work.
Also fixed an issue caused by auto-complete for the test `if you write invalid kcl you get inlined errors` that only appeared in CI in the macos runner.

selections e2e test

---

e2e/playwright/export-snapshots/gltf-standard-2.gltf
e2e/playwright/snapshot-tests.spec.ts
src/lib/browserSaveFile.ts
src/lib/exportSave.ts

Related to #833 
More fixes to export tests, and exports
Note that the export e2e tests can't test file picker-related problems, of which there are some fixes in here for.
Outstanding is what to do about gltf-standard exports as they are two files
https://github.com/KittyCAD/modeling-app/issues/1151

more e2e export fixes

---

src/wasm-lib/execution-plan/src/in_memory.rs
src/wasm-lib/execution-plan/src/lib.rs
src/wasm-lib/execution-plan/src/tests.rs

KCEP's memory model stores 'values', which can be either numbers or strings. But we'll need to support storing complex objects like points, lines, sketchgroups, etc in memory too.
This PR adds a trait for KCEP composite types, which are laid out in KCEP memory as a consecutive series of values, one for each field.
Part of https://github.com/KittyCAD/modeling-app/issues/993

Read/write composite values to KCEP memory

---

package.json
src-tauri/tauri.conf.json

```
- update e2e tests after grid update (#1171)
- expand lsp test (#1167)
- Rename mod in_memory to composite (#1169)
- Read/write composite values to KCEP memory (#1164)
- EP instructions must be serializable (#1163)
- Start execution plans (#1155)
- Sort constraint buttons (#1161)
- side quest for screenshot diffs (#1160)
- Select axis and relevant constraints (#1154)
- more e2e export fixes (#1150)
- Add tauri e2e test for auth on Linux (#1040)
- fix ply and stl exports (#1141)
- test exports (#1139)
- ensure import files always sent as bson (#1138)
- selections e2e test (#1136)
- Add Playwright tests for onboarding (#1125)
- make error not so long (#1129)
- readme (#1119)
- initial playwright setup and test (#1039)
- Cargo.lock updates (#1108)
- remove the buffer we were using for …
```

Cut release v0.13.0

---

src/wasm-lib/execution-plan/src/composite.rs
src/wasm-lib/execution-plan/src/composite/impls.rs
src/wasm-lib/execution-plan/src/lib.rs
src/wasm-lib/execution-plan/src/tests.rs

- Change memory from HashMap<address, value> to Vec<Value>
- Reading a composite value from its parts out of memory now takes a slice of memory, not a vec of memory values. 
- This way, types like Vec<Point3d> can be laid out in memory as [size, elem0, elem1, ..., elemSize]

Execution plans should allow dynamic sized types

---

.github/workflows/ci.yml

A failed `build-test-apps` job on a specific OS should cancel all the other jobs

---

.codespellrc
src/wasm-lib/Cargo.lock
src/wasm-lib/Cargo.toml
src/wasm-lib/grackle/Cargo.toml
src/wasm-lib/grackle/src/kcl_value_group.rs
src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/native_functions.rs
src/wasm-lib/grackle/src/tests.rs
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/sketch.rs

This begins work on a second, different executor. The old executor is a tree-walk interpreter, this executor compiles the KCL programs into the Execution Plan virtual machine defined in its [own crate](https://github.com/KittyCAD/modeling-api/tree/main/execution-plan). This executor is called "Grackle", after an Austin bird, and it's got its own module in wasm-lib so that I can keep merging small PRs and developing incrementally, rather than building a complete executor which replaces the old executor in one PR.
Grackle's "Planner" walks the AST, like the tree-walk executor. But it doesn't actually execute code. Instead, as it walks each AST node, it outputs a sequence of Execution Plan instructions which, when run, can compute that node's value. It also notes which Execution Plan virtual …

Grackle (KCL to EP compiler)

---

src/wasm-lib/grackle/src/binding_scope.rs
src/wasm-lib/grackle/src/lib.rs

- Move bindings into their own scope
- Remove visitor type

Tiny refactors to Grackle

---

src/wasm-lib/Cargo.lock
src/wasm-lib/grackle/src/binding_scope.rs
src/wasm-lib/grackle/src/kcl_value_group.rs
src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/tests.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs

Member expressions like "obj.property" just look up "property" under the binding for "obj".

Grackle: Compile member expressions

---

src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/tests.rs

These tests don't pass, because Grackle doesn't support computed properties yet. But they're worth committing anyway, so I put "#[ignore]" on them.

Grackle: Tests for computed properties

---

src/wasm-lib/grackle/src/binding_scope.rs
src/wasm-lib/grackle/src/kcl_value_group.rs
src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/native_functions.rs
src/wasm-lib/grackle/src/tests.rs
src/wasm-lib/kcl/src/ast/types.rs

Now Grackle can compile programs that define and use KCL functions, like
```
fn triple = (x) => { return x*3 }
let x = triple(1)
```
This also works for higher-order functions (functions which accept other functions as parameters, or return other functions).
This PR is broken into several small commits, it might be easier to review one-by-one. Each commit has a meaningful commit message and does one thing.

Grackle: compile and execute user-defined KCL functions

---

src/wasm-lib/grackle/src/kcl_value_group.rs
src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/tests.rs

Grackle can now compile |> pipelines. This means that these two programs compile to identical execution plans:
```kcl
fn double = (x) => { return x * 2 }
fn triple = (x) => { return x * 3 }
let x = 1 |> double(%) |> triple(%) // should be 6
```
```kcl
fn double = (x) => { return x * 2 }
fn triple = (x) => { return x * 3 }
let x = triple(double(1)) // should be 6
```
This required adding passing "what should % actually resolve to" through the program. This required modifying every call site of `plan_to_bind` and `plan_to_compute` to pass the data. To avoid doing this again, I wrapped that data into a struct called `Context` so that when we have more data like it, we can just add a new field and won't need to change every call site.

Grackle: pipeline expressions

---

src/wasm-lib/grackle/src/binding_scope.rs
src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/tests.rs

This will make it possible to look up array elements at runtime.

Grackle: Write array length before array

---

src/wasm-lib/Cargo.lock
src/wasm-lib/Cargo.toml
src/wasm-lib/grackle/Cargo.toml
src/wasm-lib/grackle/src/kcl_value_group.rs
src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/tests.rs

This PR:
* Adds support for computed array indices, like `let i = 1+1; let x = myArray[i]` -- previously Grackle could only resolve array indices at compiletime, but now it can emit instructions that calculate and loom up indices at runtime
* As a result, arrays can be moved into the SingleValue enum.
The next PR will do something similar for objects, at which point we can delete the KclValueGroup enum.

Grackle: Runtime computed array indices

---

src/App.tsx
src/components/AvailableVarsHelpers.tsx
src/components/ExportButton.tsx
src/components/GlobalStateProvider.tsx
src/components/ModelingMachineProvider.tsx
src/components/Stream.tsx
src/components/TextEditor.tsx
src/editor/lsp/index.ts
src/editor/lsp/plugin.ts
src/hooks/useToolbarGuards.ts
src/lang/KclSinglton.tsx
src/machines/modelingMachine.ts
src/reportWebVitals.ts
src/routes/Settings.tsx
src/routes/SignIn.tsx
yarn.lock

Fixes #1014 (og issue was about React hooks but this is the same intent, cleaning up the Github Actions threads on PRs)
Mostly just adding the `void` keyword to all the non-awaited promises we have with KclSingleton and other parts as I didn't want to change the current behavior. When it made sense to just add `await` I did so.
`vite build` also had a log about an update needed to caniuse, hence the yarn.lock change.
I'll try to fix the playwright tests in another PR

Clean up vite build warnings

---

.github/workflows/ci.yml
src-tauri/Cargo.toml

Fixes #1343
Looks like it's due to 0.1.4 (not sure why yet).
Specifying the dependency in a cleaner way, this way we should get dependabots PRs and not have it randomly upgrade and break.

Fix tauri e2e tests (tauri-driver = 0.1.3)

---

src/components/CommandBar/CommandBarHeader.tsx
src/components/CommandBar/CommandBarSelectionInput.tsx
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/commandTypes.ts
src/lib/createMachineCommand.ts
src/machines/commandBarMachine.ts
src/machines/modelingMachine.typegen.ts
src/machines/settingsMachine.typegen.ts

1. Adds logic and types to support command bar arguments to be skippable
2. Implements our first skippable argument, the "selection" arg of the Extrude modeling command.
Shows the `selection` argument being skipped by the user, then shows how the `distance` argument can be configured to be skippable as well.
https://github.com/KittyCAD/modeling-app/assets/23481541/cfaac091-8417-4a6f-bf94-5cfcbe36bc4d

Make command bar arguments skippable, configure Extrude selection to be skippable

---

src/clientSideScene/ClientSideSceneComp.tsx
src/clientSideScene/sceneEntities.ts
src/clientSideScene/sceneInfra.test.ts
src/clientSideScene/sceneInfra.ts
src/clientSideScene/segments.ts
src/components/CamToggle.tsx
src/components/DebugPanel.tsx
src/components/ModelingMachineProvider.tsx
src/components/Stream.tsx
src/components/TextEditor.tsx
src/lang/KclSingleton.tsx
src/lang/modifyAst.ts
src/lang/std/engineConnection.ts
src/lib/selections.ts
src/machines/modelingMachine.ts

Dose three things in a nutshell.
Renames `setupSingleton` to `sceneInfra` with this comment at the top
```
// This singleton class is responsible for all of the under the hood setup for the client side scene.
// That is the cameras and switching between them, raycasters for click mouse events and their abstractions (onClick etc), setting up controls.
// Anything that added the the scene for the user to interact with is probably in SceneEntities.ts
```
Renames `clientSideScene` to `sceneEntitiesManager` with the following comment
```
// This singleton Class is responsible for all of the things the user sees and interacts with.
// That mostly mean sketch elements.
// Cameras, controls, raycasters, etc are handled by sceneInfra
```
And moves react components out of setup/sceneInfra

rename scene classes for clarity

---

package.json
src/clientSideScene/sceneInfra.ts
src/lang/std/engineConnection.ts
yarn.lock

Got circular patterns and imports cleaned up on re-execute.
Also upgraded the client lib to remove a few `any`s
The import object doesn't use the same id that it's given when we hit the end point, which means we have to do special clean up logic for this one object. Maybe there's a good reason for this, but annoying that we don't seem to be able to stick to the convention.

Clean up new artifact types

---

src/clientSideScene/sceneInfra.ts

When going between sketch mode and not sketch mode we switch between an orthographic and perspective camera.
When doing so we were getting position, target etc all synced up, but zoom was a problem to make look right when switching, particularly from ortho to persp, because zoom in ortho is the size of the window, where as it's the position of the camera for perspective.
This has been resolved in this PR by factoring in the orthographic-camera's zoom before the switch, the FOV of the camera we're switching to and a little fudge constant.

fix zoom cam change

---

src/lang/KclSingleton.tsx
src/routes/Home.tsx

https://github.com/KittyCAD/modeling-app/assets/29681384/ecc33977-d7bc-4acd-9b7f-4765c6eba1cf
<details>
<summary>
transcript
</summary>
0:00
So this one, I could at least replicate easily.
0:02
So if I open this project, it's yours.
0:05
But with some extra stuff, basically me trying to make sure that the execution takes a while because that helps with replicating.
0:11
So I go ahead and make a small change and immediately go home new file, open that file.
0:17
Then you know, when I try and do stuff, it's like that, that code is still there, right?
0:23
So it is, it is successfully adding sketches in this case, like it's down the bottom here, but obviously, the code appeared when we didn't want it to.
0:32
So basically what's happening is when we re execute at the end of the end of the …

cancel execution on file change

---

src/wasm-lib/Cargo.lock

Specifically, i'm hitting https://github.com/tkaitchuck/aHash/issues/200 ahash FTBFS because of https://github.com/rust-lang/rust/pull/117372 which is fixed in 0.8.7.
This rolls us forward which should fix future builds.

bump ahash to fix the nightly builds

---

src/components/ModelingMachineProvider.tsx
src/hooks/useStateMachineCommands.ts

Should finish off the last of @Irev-Dev's checklist. Allows new state machines to flag themselves as requiring the network to be good to be available, the n updates the modelingMachine to use that option.

Disable modeling commands when network is bad

---

package.json
src-tauri/tauri.conf.json

- [bump kittcad/lib version](https://github.com/KittyCAD/modeling-app/pull/1565)
- [Grackle: implement StartSketchAt stdlib function](https://github.com/KittyCAD/modeling-app/pull/1535)
- [add issue template](https://github.com/KittyCAD/modeling-app/pull/1547)
- [short term cam fix](https://github.com/KittyCAD/modeling-app/pull/1543)
- [improve export test logs](https://github.com/KittyCAD/modeling-app/pull/1536)
- [Sketch on face of face](https://github.com/KittyCAD/modeling-app/pull/1524)
- [update cli to reestablish export test](https://github.com/KittyCAD/modeling-app/pull/1523)
- [Disable actions when stream disconnected](https://github.com/KittyCAD/modeling-app/pull/1483)
- [solve a couple of scene scale bugs](https://github.com/KittyCAD/modeling-app/pull/1496)
- [Some cam …

Cut release v0.15.3

---

package.json
src-tauri/tauri.conf.json

- [client side sketch scene not respecting base-unit-scale](https://github.com/KittyCAD/modeling-app/pull/1576)
- [Bump serde_json from 1.0.113 to 1.0.114 in /src-tauri](https://github.com/KittyCAD/modeling-app/pull/1463)
- [Bump serde from 1.0.196 to 1.0.197 in /src-tauri](https://github.com/KittyCAD/modeling-app/pull/1462)
- [Bump anyhow from 1.0.79 to 1.0.80 in /src-tauri](https://github.com/KittyCAD/modeling-app/pull/1465)
- [Vector for tracking cargo tests](https://github.com/KittyCAD/modeling-app/pull/1580)
- [Fix autocomplete in comment](https://github.com/KittyCAD/modeling-app/pull/1575)
- [Bump clap from 4.5.0 to 4.5.1 in /src/wasm-lib](https://github.com/KittyCAD/modeling-app/pull/1448)
- [Bump google-github-actions/auth from 2.1.1 to …

Cut release v0.15.4

---

src/wasm-lib/grackle/src/error.rs
src/wasm-lib/grackle/src/native_functions/sketch/helpers.rs
src/wasm-lib/grackle/src/native_functions/sketch/stdlib_functions.rs

This will be reused in future stdlib functions.
Also, add a field for argument number to the "invalid argument type" error message.

Refactor: move point-parsing into its own function

---

e2e/playwright/flow-tests.spec.ts
src/editor/plugins/lsp/kcl/index.ts
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/lsp/kcl/mod.rs

CC @jessfraz this fails locally even after pulling latest main and rebuilding the wasm, So I'll see if it's different in CI,
Here's what it looks like when the test runs
https://github.com/KittyCAD/modeling-app/assets/29681384/fb7b6714-2985-4516-aab8-09cff74b2b23
And here's the still frame from the test where it's auto completing the comment

failing auto complete test

---

src/wasm-lib/Cargo.lock
src/wasm-lib/grackle/src/binding_scope.rs
src/wasm-lib/grackle/src/error.rs
src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/native_functions.rs
src/wasm-lib/grackle/src/native_functions/sketch/helpers.rs
src/wasm-lib/grackle/src/native_functions/sketch/stdlib_functions.rs
src/wasm-lib/grackle/src/tests.rs

Now the SketchGroup is written by `startSketchAt`, read and then written by each subsequent `lineTo`. This means `lineTo` can be chained properly.

Update SketchGroup when calling lineTo

---

src/wasm-lib/Cargo.lock
src/wasm-lib/grackle/src/binding_scope.rs
src/wasm-lib/grackle/src/lib.rs
src/wasm-lib/grackle/src/native_functions/sketch.rs
src/wasm-lib/grackle/src/native_functions/sketch/stdlib_functions.rs
src/wasm-lib/grackle/src/tests.rs

With these implemented, Grackle can now finally render a cube.

Grackle: Extrude/ClosePath stdlib functions

---

.github/workflows/cargo-clippy.yml

It's now a required job before merge is allowed. Unfortunately GitHub now blocks any non-Rust PR, because they require cargo clippy but don't trigger it to run.
Solution is simple, just always run cargo clippy, so it can pass, so that merge is allowed.

Always run cargo clippy in CI

---

src/clientSideScene/sceneEntities.ts
src/machines/modelingMachine.ts

The setupSketch method in `src/clientSideScene/sceneEntities.ts` baked in quite a few assumptions
- it assumed that a draft segment (segment drawn with dashes) would only ever be the last segment
- because of the above it would also make the AST mod for you to add that last segment
- It would also setup scene callbacks within the function
It been changed to take an already modified ast, and the indices of the draft lines are specified as an input, and then and callback setup is done after setup is called.
This should unblock Frank who's going add a rectangle tool, it needs to add 4 draft segments, and no doubt will need a custom onMove callback.
@franknoirot I have a feeling that this change will be 95% of what you needed, but there might be one or two things remaining, but obviously we …

make setupSketch more composable instead of a monster function

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs
src/wasm-lib/kcl/src/parser/snapshots/kcl_lib__parser__parser_impl__snapshot_tests__ai.snap

Closes https://github.com/KittyCAD/modeling-app/issues/1411.
Several of the unit tests broke this rule (i.e. were using a pipe expression where one child expression didn't have a `%` as an arg). So those tests have been updated and now use `%` properly.

Parser ensures that pipe expressions have a % arg

---

src/lang/KclSingleton.ts
src/lang/std/engineConnection.ts

The nuke all endpoint of course also removes the default planes so they need to be re-initialised.

nuke all follow up

---

src/wasm-lib/.config/nextest.toml

Running two modeling sessions simultaneously will:
- Speed up unit testing
- Stress test our API/engine better

Allow two 'serial_test_' to run simultaneously

---

src/lib/routeLoaders.ts

Fixes #2002. The logo link leads to `/home` which redirects in the browser version, but the redirect was just missing a leading `%2F` in the project path. Now when you click it you land back on the same page via the redirects, so apparently nothing happens, which is the point.

Fix home redirect in browser

---

src/components/ProjectSidebarMenu.tsx
src/machines/commandBarMachine.ts

Fixes #1991 by not assuming we have a command to initialize the args for when we fire the "Find and select command" XState event, and failing more gracefully if we don't find one.
Furthermore, adds logic so that the Export button is disabled if the corresponding command isn't found in the available commands, since in circumstances such as a network outage all modeling commands are filtered out of the command bar anyway.

Don't assume a command is found in "Find and select command" command bar action

---

src/components/TextEditor.tsx

Theres an order of operations thing here I'm trying to be explicit about as a way of fixing snippets
part of https://github.com/KittyCAD/modeling-app/issues/2097

explicitly set default codemirror plugins

---

.github/workflows/ci.yml

Follow up to #1890 
https://github.com/KittyCAD/modeling-app/actions/runs/8683295685 worked after the GCP side was turned back on, but lead to .json files that pointed to non-existing non-nightly URLs. This fixes it.

Fix nightly jsons

---

src/machines/authMachine.ts

the whole getting an api key thing is shitty because likely many users have never generated one, plus its another api call, this attempts to get the cookie from cookie store, if it works in vercel it will work on main

attempt to fix cookie token bullshit in another way

---

src/lib/tauriFS.ts

[`sep` is now a function in Tauri V2 ](https://beta.tauri.app/references/v2/js/core/namespacepath/#sep)and we missed one use (or reverted it after @pierremtb did a good job cleaning them all up.

Fix one missing use of sep without parens after Tauri V2 migration

---

src/components/FileTree.tsx
src/components/ModelingSidebar/ModelingPanes/index.ts
src/components/ModelingSidebar/ModelingSidebar.tsx
src/useStore.ts

Reworks the FileTree component to be able to work as a pane in the ModelingSidebar if the user is in the desktop app. This will be duplicate with the sidebar version of the FileTree for a short while, but it is a step forward to getting rid of that sidebar menu because it's not very intuitive to find.

Make FileTree a pane (desktop only)

---

src/components/ModelingMachineProvider.tsx
src/hooks/useSetupEngineManager.ts
src/lang/std/engineConnection.ts
src/lib/coredump.ts
src/wasm-lib/kcl/src/coredump/local.rs
src/wasm-lib/kcl/src/coredump/mod.rs
src/wasm-lib/kcl/src/coredump/wasm.rs

This will slice off the ?pool= param and pass it to the WebSocket
request, which requests that the Zoo API use a particular pool of
engines. This isn't something any users of the zoo api require; but it's
needed for the internal engine Zoo development workflow. This may be
used in the future, but for now this'll be always enabled. Passing any
value in the production servers will result in a "no backend" error for
now.

Pass the ?pool query param through to the backend.

---

package.json
src-tauri/tauri.conf.json

* Pass the ?pool query param through to the backend. (#2246)
* Fix the updater (#2250)
* Download-wasm if there's no rust changes (#2234)
* Filter files and folders that start with a `.` (#2249)
* Better rust parsing of route uris for files (#2248)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.19.2...v0.19.3

Cut release v0.19.3

---

e2e/playwright/flow-tests.spec.ts
e2e/playwright/storageStates.ts
src/components/ModelingSidebar/ModelingPane.tsx
src/components/ModelingSidebar/ModelingSidebar.tsx
src/routes/Onboarding/CodeEditor.tsx
src/routes/Onboarding/InteractiveNumbers.tsx
src/routes/Onboarding/ParametricModeling.tsx

Adds a test so that a regression like the one found yesterday with #2259 should be caught before a PR can merge with it, then fixes the issue with the regression. Tests pass if you check out the first commit, fail if you check out the second, then pass again with the final commit.

Add an E2E test for clicking all the way through the onboarding, restore code pane highlighting in onboarding

---

src/lang/std/engineConnection.ts

It's not permissible to transition the bundle policy during runtime, so we need to maintain max-bundle, even if we know there's no ICE and it won't matter any.

Set max-bundle for local engine

---

.github/workflows/create-release.yml

Needs `context.sha` not `context.repo.sha`, seen in https://github.com/KittyCAD/modeling-app/actions/runs/8932384784

Fix Create Release commit sha

---

.github/workflows/ci.yml

Just like Playwright tests, shouldn't be enabled on release or nightly release pipelines.
The tests on nightly builds were failing because in this stage, the driver was looking for `zoo-modeling-app` instead of `zoo-modeling-app-(nightly)`, would have been an easy fix but this seems better. We don't want a flaky test to stop a release pipeline, as those aren't started without proper testing in the `Cut release v` PR.

Disable tauri e2e tests on release

---

src/components/CommandBar/CommandBarSelectionInput.tsx

Fixes #2302
https://github.com/KittyCAD/modeling-app/assets/23481541/22ca4d7e-26c3-47bd-b738-d178800b20c8

Exit edit mode when selection input is up, re-enter when it's not.

---

e2e/playwright/flow-tests.spec.ts

Test update follow-up to #2306. Our extrude command end-to-end (E2E) test selected a face to extrude by selecting a line of code in the text editor, which is not the most common way users will select faces. This updates the test to do what most users will do, click in the 3D scene.

Make "Extrude from command bar" test selection via 3D scene, not code

---

src-tauri/Cargo.lock
src/routes/Settings.tsx

Pointed out by @jessfraz at some point on Slack I can't find the reference, but this fixes a layout bug where the bottom of the Settings scroll area wouldn't be reachable on Mac Desktop. Because we weren't setting an explicit `grid-template-rows` value, it seemed to be creating implicit CSS grid rows in the native Webkit browser. If we just give it a `1fr` value it explicitly has just one row.

Fix settings overflow by setting grid-template-rows

---

src/wasm-lib/kcl/src/std/fillet.rs
src/wasm-lib/kcl/src/std/patterns.rs
src/wasm-lib/kcl/src/std/revolve.rs

Resolves https://github.com/KittyCAD/modeling-app/issues/2301 and technically resolves https://github.com/KittyCAD/modeling-app/issues/2208 too, but there's going to be more stdlib functions to make mock safe.
But there's impetus to merge this soon since it currently is broken for when users are trying to sketch with the broker code open.

make edge helpers + more mock safe

---

src/components/ProjectCard.tsx

only occurring in the desktop app, on Windows machines, that have an out-of-date system browser or something. oy vey

Fix CSS bug causing ProjectCard links to flicker

---

src/components/ModelingSidebar/ModelingPanes/MemoryPane.tsx
src/components/ModelingSidebar/ModelingPanes/index.ts

Adds a button to the top right area of the Variables pane to copy out the current KCL program memory to your clipboard.
https://github.com/KittyCAD/modeling-app/assets/23481541/6dedb6cf-9d91-4380-a1b1-bf60323694e1

Add "copy to clipboard" button to Variables pane

---

src/wasm-lib/kcl/src/std/math.rs

Related to #2384 But really we should probably add a bunch of unit tests for the math stdlib functions too.

fix max std lib

---

src/lang/std/engineConnection.ts

Reset inSequence back to 1 every time we connect to the Engine, otherwise we'll continue to think the current sequence is a high number (while the engine has no memory of the last session -- and may even be a new engine instance!) and ignore messages until we pass that counter again.

Reset data channel seq every connect (closes #336)

---

e2e/playwright/flow-tests.spec.ts
src/lib/tauri.ts

closes https://github.com/KittyCAD/modeling-app/issues/2433
one thing that is curious that I dont know how to fix is reset settings I kinda expected to reset just the user settings or just the project settings without effecting the other, cc @franknoirot if thats the intent we need a new issue for that bug, as I don't know how to fix that, but when it gets fixed it should be easy to update my test since i kinda had assumed thats how it worked so most of the checks are there just with the wrong values haha

fix reset settings in browser

---

src/wasm-lib/Cargo.lock
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/std/import.rs
src/wasm-lib/kcl/src/std/patterns.rs

something to be cognizant of but leaving around printlns in the executor/parser/tokenizer will break the vscode version of the lsp sincce it communicates over stdin and stdout
we likely want some sort of longer term test here for these

remove printlns from stdlib

---

package.json
src-tauri/tauri.conf.json

* Add basic keyboard shortcuts for sketch and modeling tools (#2419)
* First `esc` now unequips sketch tools, second exits sketch (#2419)
* Fix xz-plane (#2376)
* Add more rust file tests (#2452)
* Fix rename project directory (#2451)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.21.6...v0.21.7

Cut release v0.21.7

---

src/wasm-lib/kcl/fuzz/Cargo.lock
src/wasm-lib/kcl/fuzz/fuzz_targets/parser.rs

I had this handy from the PR I just closed -- I took a look at the existing code and it was basically the same code -- except this is a bit smaller because we'll offload the string parsing to the fuzz lib, and inline the `if Ok(v)` - also bump the lockfile

Fix the fuzzer to work with the changed API

---

src-tauri/Cargo.lock
src/components/ModelingMachineProvider.tsx

Fixes #1497 logging an error and presenting the user with a toast error message if they try to export an empty scene.
Since there was already a condition for this that was unhandled, I attached this behavior to that condition. The condition also addressed handling an attempt to export bad kcl.
NOTE: the error event is triggered after submitting the export request.
https://github.com/KittyCAD/modeling-app/assets/4322/19e0be7a-350f-42cf-9e64-c26793b64f5a

Handle export errors with empty scene or KCL errors

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/tests/executor/inputs/pipe_as_arg.kcl

Relaxes an arbitrary restriction. Previously KCL pipelines couldn't start with a number, e.g. `2 |> double(%)`. Now they can.

Allow any value to start a pipe expression

---

e2e/playwright/flow-tests.spec.ts
e2e/playwright/snapshot-tests.spec.ts
e2e/playwright/test-utils.ts
src-tauri/Cargo.lock
src/components/ModelingMachineProvider.tsx
src/lang/std/engineConnection.ts

Resolves #2305. Uses the [react-hot-toast toast.promise() method](https://react-hot-toast.com/docs/toast) to show a loading and then success/error toast based on the outcome of the engine exportSave() function. Adds Playwright tests for the loading and success states being notified in the toasts.
@Irev-Dev let me know if this is too naive of an implementation. I think it could benefit from a timeout handler so that if we never hear back from the engine to even call exportSave we can fail the command, but I'm not sure.
https://github.com/KittyCAD/modeling-app/assets/23481541/1be2fd93-ef74-4168-bf35-920c072ca408

Add a promise-based toast when exporting

---

.github/workflows/ci.yml

Still got to clean up how the windows tests get started versus linux, but I would say let's enable them as-is for now!

Enable Windows Tauri e2e tests in CI

---

e2e/tauri/specs/auth.e2e.ts

Timer before sign out, ubuntu test passed three times in a row. Would be better to understand why but I believe this should help people now.

Timeout ahead of flaky sign out

---

e2e/playwright/flow-tests.spec.ts

Shuffled some tests around too, to organise them, only `Testing selections (and hovers) work on sketches when NOT in sketch mode` is new.

More selection verification

---

src/lang/std/engineConnection.ts

Should resolve @Irev-Dev and @dshaw 's reported issue of the app restarting more frequently lately.
The issue is, `mute` event on a video track doubles as a signal about the network https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack#events
Before my last PR which overhauled the connection logic, we never did anything when receiving this signal, except report it. I decided in my PR that we should handle such a signal, and restart the connection, since it's erroneous. 
On further investigation (@paultag helped me out), we discovered **any PLI will cause this event to fire**. This effectively means Kurt and Dshaw *actually do have flaky streams*. The difference is, the flakiness is so incredibly minor, that we should basically ignore it.
This PR simply reverts this …

Do not aggressively disconnect when video stream goes down

---

src/lang/std/engineConnection.ts

Left console.log('connectionstatechange: ' + event.target?.connectionState) intentionally

Remove debug logging from Engine Connection

---

.github/workflows/cargo-clippy.yml

Sometimes the `src-tauri/` project gets out of date Cargo.lock. This adds a CI check to prevent it.
This can happen because `src-tauri` is a separate Cargo project from `src/wasm-lib`, but the former includes the latter as a dependency. So, when wasm-lib updates a dep (e.g. bump databake from 1.7 to 1.8), the former will, upon recompilation, pull in the newer databake dep. But programmers in the wasm-lib repo don't usually work in the src-tauri repo and so the src-tauri repo doesn't get updated.
If the check fails, it prints a helpful message explaining how to resolve it.

Prevent stale Cargo.lock

---

src/components/SettingsAuthProvider.tsx
src/lib/paths.ts
src/machines/settingsMachine.ts
src/routes/Onboarding/index.tsx

Resolves #2500 by converting "persistSettings" from an XState action to a service that is invoked in a new "Persisting settings" state. Now our dismiss hook only sends the event but doesn't immediately navigate. Instead, we handle navigation in a useEffect which navigates when it sees the onboarding state get set to "dismiss" _and_ the XState state is "idle", meaning we've already persisted the settings and can safely navigate.
Gonna try to write a Tauri test for this after #2659 gets merged and we have a framework for adding them.
https://github.com/KittyCAD/modeling-app/assets/23481541/0ef2dbaf-aac3-4ed6-9c17-b53d4b94de56

Ensure settings are persisted before we navigate for onboarding dismissal

---

src/wasm-lib/Cargo.lock
src/wasm-lib/Cargo.toml
src/wasm-lib/kcl-test-server/Cargo.toml
src/wasm-lib/kcl-test-server/src/lib.rs
src/wasm-lib/kcl/src/engine/conn.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/lib.rs
src/wasm-lib/kcl/src/test_server.rs

Adds a new library, the `kcl-test-server`. It lets you easily start a HTTP server with one endpoint, which accepts JSON. The JSON body contains a KCL program and a test name. The server has a pool of active engine sessions, and when it gets a KCL program, it executes it on one of those engine sessions.
This addresses part of https://github.com/KittyCAD/modeling-app/issues/2580 but currently the sketch-on-face tests don't pass with this new test server yet.
This is a library, not a binary, because I want to use it in both the wasm-lib unit tests and in the zoo CLI.

KCL execution server

---

src/wasm-lib/Cargo.lock
src/wasm-lib/kcl/Cargo.toml

Reverts KittyCAD/modeling-app#2704 because it looks like the dashmap team has yanked their 6.0.0 release for the time being https://crates.io/crates/dashmap/versions

Revert "Bump dashmap from 5.5.3 to 6.0.0 in /src/wasm-lib"

---

src/lib/settings/initialSettings.tsx

We're getting buggy behavior from SSAO while trying to manually set near and far values for FOV when entering and exiting sketches, so this is a quick temporary fix that makes the default value for the hidden setting `enableSSAO` to be `false`, turning it off for the vast majority of users, while we get things sorted.

Disable SSAO temporarily

---

e2e/playwright/flow-tests.spec.ts
src/lang/codeManager.ts

In the new user, new sign-in case we were not setting the code in the KCL code editor, because we checked if a value was `null` before doing that, but just above had made the value coerce to `""` if it was found to be null. Annoying little JS behavior. This fixes that issue and adds a Playwright test to verify the "fresh user" case always sees the onboarding code in their editor.

Fix onboarding example code loading

---

.github/workflows/cargo-clippy.yml
.github/workflows/playwright.yml
e2e/playwright/flow-tests.spec.ts
e2e/playwright/storageStates.ts
src/lang/codeManager.ts
src/routes/Onboarding/CodeEditor.tsx
src/routes/Onboarding/FutureWork.tsx
src/routes/Onboarding/InteractiveNumbers.tsx
src/routes/Onboarding/Introduction.tsx
src/routes/Onboarding/ParametricModeling.tsx
src/routes/Onboarding/index.tsx

There are several points in the onboarding where we want users to reference specific lines of code in our demo example of a bracket. To ensure they are always seeing the demo code, we now have a new custom hook that will overwrite the user's code no matter what when they enter an onboarding step that invokes it. To let users know that we'll do this, we also add a warning to the onboarding introduction that we will reset their code.
Fixes #2719 by making a state where you enter that step and don't have the onboarding code impossible, and adds a Playwright test to verify it.
https://github.com/KittyCAD/modeling-app/assets/23481541/02932b9c-8ad9-41c3-8728-ab263be81e58

Reset code on critical onboarding steps

---

e2e/playwright/flow-tests.spec.ts
src/components/ModelingMachineProvider.tsx
src/lang/queryAst.test.ts
src/lang/queryAst.ts
src/lib/selections.ts

Resolves #2722
When the user has no selection we enable the extrude button to allow the user to select their sketch through the cmdbar interface, however we'd allow this even when there's was nothing extrudable to select.
Now fixed, also fixed an issue where you could select to extrude a sketch that had already been extruded, this would generate code with an error.

Disable extrude button if there is no extrudable geometry

---

src/lang/queryAst.test.ts
src/lang/queryAst.ts

gives pathToNode for each of the enter callbacks.
Tested against `getNodePathFromSourceRange` as the two should agree.

Improve traverse

---

src/wasm-lib/derive-docs/src/lib.rs
src/wasm-lib/derive-docs/src/tests.rs
src/wasm-lib/derive-docs/tests/args_with_lifetime.gen
src/wasm-lib/derive-docs/tests/args_with_refs.gen

Previously these functions could not be used with `#[stdlib]` proc-macro:
```rust
fn someFn(data: &'a str) {}
fn someFn<'a>(data: Foo<'a>) {}
```
But now they can.

Allow lifetime refs in KCL stdlib parameters

---

e2e/playwright/flow-tests.spec.ts

anecdotal, but first run for macos on another PR
And took 41 minutes
On this one
Only took 21 minutes, I think heaps of the time is being eaten up with the retries.
And then all pass on the next retry after that. still more work to do, but going to merge the progress.

playw tweaks

---

.github/workflows/ci.yml

This reverts commit 6123ed6a8297c8ba40ebd9154245728fc7adbe9a and replaces tauri-action steps with calls to `tauri build` directly, which is less of a black-box environment with little to no cons as this point.

Revert "Workaround to fix tauri tests (#2772)" and remove tauri-action

---

src/App.tsx
src/AppState.tsx
src/Router.tsx
src/components/RefreshButton.tsx
src/lib/coredump.ts
src/lib/screenshot.ts
src/routes/Home.tsx

Working again.
I broke this with the zustand migration, but honestly setting htmlref ever really made sense since we're interacting with it passively to take a screen shot, `document.documentElement` is fine, and makes the code much simpler
It would also fail if the screenshot failed which I think is bad, the screen shot is a nice to have, and we want the core dump regardless.

fix core dump screenshot

---

.github/workflows/ci.yml
package.json
src-tauri/tauri.conf.json

* Fix an updater issue found in v0.22.7 and v0.23.0 Windows builds. If you're stuck here please head over to [the website](https://zoo.dev/modeling-app/download) upgrade manually. Sorry for the inconvenience! (#2914)
* Add message "click plane to sketch on" to toolbar after clicking start sketch (#2591)
* Fix core dump screenshot (#2911)
* Pause stream when exiting sketch or extruding (#2900)
* Hide the view until the scene is initially built (#2894)
* Zoom out on extruded object (#2819)
* More codemirror enhancements (#2912)
* Remove react-codemirror and update all the codemirror libs (#2901)
* Cleanup annotations, makes it easier to read (#2905)
* Update release docs (#2906)
* Small codemirror changes (#2898)
**Full Changelog**: …

Cut release v0.23.1

---

src/clientSideScene/CameraControls.ts
src/clientSideScene/ClientSideSceneComp.tsx

Steps to reproduce:
1. Open the debug pane
2. Click "perspective cam" checkbox to change camera to orthographic. Scene view should update immediately.
3. Click same checkbox again to change camera back to perspective
I expected the 3D scene view to update immediately back to a perspective camera, but it doesn't. You need to adjust the FOV slider for it to register that you're back in perspective mode.

Fix perspective camera toggle in debug pane to update immediately

---

e2e/playwright/flow-tests.spec.ts
src/routes/Home.tsx

A Tauri-side remnant of the issue resolved for the modeling screen with #1367. Closes #2460. Adds a playwright test for the behavior added in #1367, but does not yet add tauri tests for the behavior I'm adding now.

Don't navigate when Backspace/Delete is pressed on the home screen

---

.github/workflows/ci.yml

Forgot that `env.CUT_RELEASE_PR` resolves to a `'false'` string and not a boolean...
Updater tests are firing up on all commits now instead of just Cut release PRs

Fix CUT_RELEASE_PR eval in ci.yml

---

src/wasm-lib/kcl/src/executor.rs

Seems to be unused since #2941.

Remove unused function ProgramMemory::get_tags

---

README.md
src/wasm-lib/kcl/src/engine/conn.rs

We use the WebSocket connection to send binary data (in the form of shapefiles) from the engine to the client. These can very easily get larger than the default 16MB limit on the max_frame_size. I don't understand why it won't stich multiple frames together - but given what I can see when this crashes, the max_message_size isn't the LIMFAC, max_frame_size is.
That's an issue for future-us.

Bump max_frame_size

---

src/clientSideScene/sceneEntities.ts
src/components/AvailableVarsHelpers.tsx
src/components/ModelingSidebar/ModelingPanes/MemoryPane.test.tsx
src/components/ModelingSidebar/ModelingPanes/MemoryPane.tsx
src/lang/KclSingleton.ts
src/lang/artifact.test.ts
src/lang/executor.test.ts
src/lang/langHelpers.ts
src/lang/modifyAst.ts
src/lang/queryAst.ts
src/lang/std/sketch.ts
src/lang/std/sketchConstraints.test.ts
src/lang/std/sketchcombos.ts
src/lang/std/std.test.ts
src/lang/wasm.ts
src/lib/testHelpers.ts
src/lib/useCalculateKclExpression.ts
src/machines/modelingMachine.ts
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/mod.rs
src/wasm-lib/kcl/src/std/patterns.rs
src/wasm-lib/tests/executor/main.rs
src/wasm-lib/tests/modify/main.rs

Fixes #1285.
Prior to this, KCL implemented dynamic scope. With dynamic scope, in order to determine whether a variable is defined at a given point and what its type is, you needed to execute the program to follow its flow. This becomes harder and harder for anyone reading KCL code, especially when we start adding loops, recursion, etc.
```kcl
// With dynamic scope, this works.
fn returnX = () => {
// What does x refer to?
return x
}
const x = 2
const answer = returnX()
```
This PR changes KCL to use [lexical scope](https://en.wikipedia.org/wiki/Scope_(computer_science)). This generally makes it easier to reason about a snippet of code because you can find an identifier's definition above it in the source to determine its type. The runtime call stack cannot affect it. This also opens the …

Add lexical scope and redefining variables in functions

---

packages/codemirror-lsp-client/src/client/server-capability-registration.ts
src/clientSideScene/sceneEntities.ts
src/components/ModelingMachineProvider.tsx
src/components/Toolbar/Intersect.tsx
src/components/Toolbar/SetAbsDistance.tsx
src/components/Toolbar/SetAngleBetween.tsx
src/components/Toolbar/SetHorzVertDistance.tsx
src/components/Toolbar/setAngleLength.tsx
src/lang/modifyAst.ts
src/lang/modifyAst/addFillet.ts
src/lang/queryAst.test.ts
src/lang/queryAst.ts
src/lang/std/sketch.ts
src/lang/std/sketchcombos.ts
src/lang/util.ts
src/lang/wasm.ts
src/lib/coredump.ts

Instead of cloning objects by serializing through JSON, use the built-in [`structuredClone()`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) function. The benefit is that the return value preserves the type of the input value, avoiding the dreaded `any` type which disables the TS type-checker.
**Important:** Similar to going through JSON, it still only works with plain JS objects using literal syntax like `{ foo: 123 }`. If an object is an instance of a class or has any other prototype, that won't be preserved, and the type will be incorrect. For example, methods won't be present.

Fix to preserve types using structuredClone

---

src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/tests/executor/main.rs

closes https://github.com/KittyCAD/modeling-app/issues/3141
actually really glad you called that out @paultag because the problem was we werent using the execute function where we should but it is literally the line i put in the issue that allows this :)

fix source code ranges for function calls

---

e2e/playwright/flow-tests.spec.ts
src/routes/Onboarding/index.tsx

Adds a Playwright test for the two scenarios fixed in #3151. Note that because our method for seeding the browser local storage with code (`page` or `context.addInitScript`) runs before any browser-level navigation, including `page.reload()`, the only way I could find to test persistence was to open the black box a little bit and look at the localStorage to confirm it was written to. I would love to just look at the code pane after a normal reload.

Add a test for onboarding code reset confirmation and persistence

---

src/lang/queryAst.ts

Fixes #3134.
I'd like to make a follow-up PR that makes the types more accurate, which would have prevented this issue.

Fix to not crash when there's no var declaration

---

src/wasm-lib/kcl-test-server/src/lib.rs
src/wasm-lib/kcl/src/executor.rs

Allow the KCL execution server to choose a local engine, instead of just the remote engine.
Technically this was already possible, via the $LOCAL_ENGINE_ADDR environment variable. But it was hard to discover this.

KCL execution server can use a local engine

---

src/wasm-lib/kcl-test-server/src/lib.rs
src/wasm-lib/kcl/src/engine/mod.rs
src/wasm-lib/kcl/src/executor.rs

Problem: My KCL test server was clearing the scene before starting each KCL program, but that meant the default sketch planes were gone.
Solution: There was already a Reset Scene method which properly cleaned up the 3D modeling scene. I didn't know about it, so I wrote my own. But my own one didn't call the necessary post-clear hooks, so it didn't recreate the default planes.
This PR calls the right Reset Scene method, so the default planes get recreated after the scene is cleared.

bugfix: KCL Test Server should clear scene properly

---

src/wasm-lib/tests/executor/inputs/basic_fillet_cube_close_opposite.kcl
src/wasm-lib/tests/executor/inputs/basic_fillet_cube_end.kcl
src/wasm-lib/tests/executor/inputs/basic_fillet_cube_next_adjacent.kcl
src/wasm-lib/tests/executor/inputs/basic_fillet_cube_previous_adjacent.kcl
src/wasm-lib/tests/executor/inputs/basic_fillet_cube_start.kcl
src/wasm-lib/tests/executor/inputs/function_sketch.kcl
src/wasm-lib/tests/executor/inputs/function_sketch_with_position.kcl
src/wasm-lib/tests/executor/main.rs

These two lines are equivalent:
`kcl_input!("foo")`
`include_str!("inputs/foo.kcl")`

Use kcl_input! macro

---

src-tauri/Cargo.lock
src/wasm-lib/.config/nextest.toml
src/wasm-lib/Cargo.lock
src/wasm-lib/tests/executor/main.rs

'serial_test' isn't actually accurate. Two of these tests run in parallel now. So I renamed it 'kcl_test' as that's what it's actually doing.
In the nextest config, I changed the label from 'serial-integration' to 'uses-engine' because the former isn't true, and also doesn't explain _why_ it's being limited. The new name explains why we're limiting the number of tests that can run in parallel.
Also bump the phone number dep.

Use better names for engine/KCL tests

---

src-tauri/Cargo.lock
src/wasm-lib/derive-docs/src/lib.rs
src/wasm-lib/derive-docs/tests/args_with_lifetime.gen
src/wasm-lib/derive-docs/tests/args_with_refs.gen
src/wasm-lib/derive-docs/tests/array.gen
src/wasm-lib/derive-docs/tests/box.gen
src/wasm-lib/derive-docs/tests/doc_comment_with_code.gen
src/wasm-lib/derive-docs/tests/lineTo.gen
src/wasm-lib/derive-docs/tests/min.gen
src/wasm-lib/derive-docs/tests/option.gen
src/wasm-lib/derive-docs/tests/option_input_format.gen
src/wasm-lib/derive-docs/tests/return_vec_box_sketch_group.gen
src/wasm-lib/derive-docs/tests/return_vec_sketch_group.gen
src/wasm-lib/derive-docs/tests/show.gen
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/lib.rs
src/wasm-lib/kcl/src/test_server.rs
src/wasm-lib/tests/executor/main.rs

This will ensure that the KCL snapshot tests all use the same logic, whether they're in `tests/executor/main.rs` or in the KCL stdlib modules.

Simplify the KCL stdlib test codegen

---

e2e/playwright/flow-tests.spec.ts
src/components/ModelingSidebar/ModelingPanes/index.ts
src/components/ModelingSidebar/ModelingSidebar.tsx

Closes #2794.
1. Adds a system by which panes can register `showBadge` callbacks that (so far) are only given `kclContext` to work with and return a boolean or number value with which to show a badge on their button. This button also has a screen reader-only description that says "has X notifications", which we can check for in Playwright tests.
2. Uses this system to add a badge to the KCL Errors pane button that appears if the number of KCL errors changes to be greater than 0.

Add a system for badges to appear on pane buttons

---

e2e/playwright/test-utils.ts

When the bounding box can't be found the test timeouts at 2 minutes, this help the tests fail faster.

make test fail fast

---

src-tauri/Cargo.lock

We were getting an error that looks like this:
```
error: failed to select a version for `clap`.
... required by package `tauri-plugin-cli v2.0.0-beta.7`
... which satisfies dependency `tauri-plugin-cli = "^2.0.0-beta.7"` (locked to 2.0.0-beta.7) of package `app v0.1.0 (/Users/user/code/modeling-app/src-tauri)`
versions that meet the requirements `^4` (locked to 4.5.11) are: 4.5.11
all possible versions conflict with previously selected packages.
previously selected package `clap v4.5.13`
... which satisfies dependency `clap = "^4.5.13"` of package `kcl-lib v0.2.3 (/Users/user/code/modeling-app/src/wasm-lib/kcl)`
... which satisfies path dependency `kcl-lib` (locked to 0.2.3) of package `app v0.1.0 (/Users/user/code/modeling-app/src-tauri)`
failed to select a version for `clap` which …
```

Upgrade to clap 4.5.13 to fix build error

---

src/components/HelpMenu.tsx

This one wasn't too bad to solve once I got my windows machine running a Tauri dev build.
The problem had something to do with how relative URI paths are processed by `react-router`'s `navigate()` function, specifically how it processes the _current pathname_. In this HelpMenu component, we used a relative path because it needs to work on the Home route and in the File route. We can circumvent the issue by navigating with absolute file paths, like we do for the links to the settings panes in the popover menus.

Fix link to keybindings tab in help menu on Windows

---

package.json
src-tauri/tauri.conf.json

* Show default planes on empty scene (#3237)
* Re-get the openPanes from localStorage when navigating between projects (#3241)
* Have links clickable within tooltips without clicking content below them (#3204)
* Fix link to keybindings tab in help menu on Windows (#3236)
* Fix cryptic error (#3234)
* Rm error pane show badge on code (#3233)
* Open file with url encoded space (#3231)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.24.6...v0.24.7

Cut release v0.24.7

---

e2e/playwright/flow-tests.spec.ts
src-tauri/Cargo.lock
src/components/ModelingSidebar/ModelingPanes/KclEditorPane.tsx
src/lang/KclSingleton.ts

fixes https://github.com/KittyCAD/modeling-app/issues/3209
fixes https://github.com/KittyCAD/modeling-app/issues/3258
this adds a test for code pane open close, but after switch to electron we will want playwright tests, saying tauri tests just for findability in github search

editor repaints any errors when rendered

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/tests/executor/inputs/no_visuals/array_index_oob.kcl
src/wasm-lib/tests/executor/inputs/no_visuals/index_of_array.kcl
src/wasm-lib/tests/executor/inputs/no_visuals/invalid_index_fractional.kcl
src/wasm-lib/tests/executor/inputs/no_visuals/invalid_index_negative.kcl
src/wasm-lib/tests/executor/inputs/no_visuals/invalid_index_str.kcl
src/wasm-lib/tests/executor/inputs/no_visuals/invalid_member_object.kcl
src/wasm-lib/tests/executor/inputs/no_visuals/invalid_member_object_prop.kcl
src/wasm-lib/tests/executor/inputs/no_visuals/non_string_key_of_object.kcl
src/wasm-lib/tests/executor/inputs/no_visuals/object_prop_not_found.kcl
src/wasm-lib/tests/executor/inputs/no_visuals/property_of_object.kcl
src/wasm-lib/tests/executor/main.rs
src/wasm-lib/tests/executor/no_visuals.rs

This new test framework, `no_visuals`, is for testing KCL programs via asserts, not via twenty-twenty visual tests. This is useful for unit-testing small fragments of KCL.
It's easy! All you need to do is:
- Write a KCL file
- Save it under `tests/executor/inputs/no_visuals/foo.kcl`
- Open `no_visuals.rs` and add `gen_test!(foo);`

Easy KCL tests with no engine/visuals

---

e2e/playwright/flow-tests.spec.ts
src/components/Gizmo.tsx

That right-click menu on the gizmo is completely undiscoverable. This adds a little dropdown above and right of the gizmo with exactly the same menu attached to it, so users can get to the menu either way. Adds to our context menu playwright test to ensure the popover works. 
https://github.com/user-attachments/assets/d3040d02-29a0-4bb5-b962-964a0dfa666e

Add a little dropdown arrow menu to gizmo with view settings

---

src/components/ModelingSidebar/ModelingSidebar.tsx

After the badge was added, I tried to use it to scroll to the error, and it wasn't obvious to me I had to click the badge itself, I thought the codePane button would scroll, trying to make it more obvious to users.
https://github.com/user-attachments/assets/1fe23b45-371b-40a4-8552-a691a72d8f9b

badge scale on hover

---

playwright.config.ts

I'm seeing an increased `"Test timeout of 30000ms"` related failures in axiom
In the original `e2e/playwright/flow-tests.spec.ts`
Tucked away in this file, we specify the global test timeout here ...
https://github.com/KittyCAD/modeling-app/blob/3f082c82222ab810ffb5f87daf1dc6c31ab1bfff/e2e/playwright/flow-tests.spec.ts#L97
This was removed by this PR
https://github.com/KittyCAD/modeling-app/pull/3297/
This pr re-instates the 2 minute test timeout via the Playwright config

set global test timeout using the Playwright config

---

src/App.tsx
src/Router.tsx
src/components/ActionButton.tsx
src/components/FileMachineProvider.tsx
src/components/FileTree.tsx
src/components/HelpMenu.tsx
src/components/LowerRightControls.tsx
src/components/LspProvider.tsx
src/components/ProjectCard/ProjectCard.tsx
src/components/ProjectSidebarMenu.tsx
src/components/Settings/AllSettingsFields.tsx
src/components/SettingsAuthProvider.tsx
src/components/UserSidebarMenu.tsx
src/hooks/useAbsoluteFilePath.ts
src/hooks/useRefreshSettings.ts
src/lib/paths.ts
src/lib/routeLoaders.ts
src/lib/tauriFS.ts
src/routes/Home.tsx
src/routes/Onboarding/Introduction.tsx
src/routes/Onboarding/index.tsx
src/routes/Settings.tsx
src/routes/SignIn.tsx

Fulfills a helpful suggestion by @adamchalmers to use named constants for the query parameters to open the settings to specific tabs. Let me know if there's a better or more elegant way to do this!
Also takes the opportunity to rename `paths` to `PATHS` which is more proper JS constants naming convention.

Use named constants for settings URL query params

---

src/lang/wasm.ts
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/function_param.rs
src/wasm-lib/kcl/src/std/patterns.rs

`ProgramReturn::Arguments` variant is never instantiated and should go away. This would make `ProgramReturn` an unnecessary wrapper around `KclValue`, so the whole type should go away.
Part of https://github.com/KittyCAD/modeling-app/issues/3379

Remove ProgramReturn

---

src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/tests/executor/inputs/no_visuals/sketch_group_in_object.kcl
src/wasm-lib/tests/executor/no_visuals.rs

Fixes #3338.
Putting them inside an object and using them later should work now.
```kcl
fn buildSketch = () => {
return {
thing: startSketchOn('XY')
|> startProfileAt([0, 0], %)
|> line([0, 1], %)
|> line([1, 0], %)
|> line([0, -1], %)
|> close(%)
}
}
let x = buildSketch()
x.thing
|> extrude(10, %)
```

Fix sketch groups and extrude groups when used inside objects

---

e2e/playwright/various.spec.ts

It's still got flakes in it but this should make it pass more reliably on Webkit, and make it more readable for anyone looking to improve it.

Make `Basic default modeling and sketch hotkeys work` E2E test more reliable

---

.gitignore
e2e/playwright/projects.spec.ts
e2e/playwright/test-utils.ts
flake.nix
playwright.config.ts
src/routes/Home.tsx

Closes https://github.com/KittyCAD/modeling-app/issues/3369
This is my first playwright test for modeling-app so please nitpick! Just copy-pasta from other tests and some digging on the weird hoop for handling file chooser. I added a new testid as well as it made it much easier to select the right thing in the DOM.
The rest of the changes are necessary to support Nixos. I'm happy to tweak them if desired but I do need to be able to point to specific executables and not the stuff playwright & electron both download.

Adding projects folder change test

---

e2e/playwright/projects.spec.ts
e2e/playwright/test-utils.ts
e2e/playwright/testing-selections.spec.ts

Pretty straightforward. Had to modify the setup to allow me to disable project dir cleaning.
Closes https://github.com/KittyCAD/modeling-app/issues/3371.

Test: restart electron with settings intact

---

e2e/playwright/text-to-cad-tests.spec.ts

Closes #3490. There should be no web Playwright test failures related to text-to-cad to merge this.

Get existing web text-to-cad playwright tests back to green

---

.github/workflows/playwright.yml

I want to see if this changes the order that things show up in github actions so that it's
```
playwright-chrome, (windows, 1, 4)
playwright-chrome, (windows, 2, 4)
playwright-chrome, (windows, 3, 4)
playwright-chrome, (windows, 4, 4)
play....
```
Instead of 
```
playwright-chrome, (windows, 1, 4)
playwright-chrome, (ubuntu, 1, 4)
playwright-chrome, (windows, 2, 4)
playwright-chrome, (ubuntu, 2, 4)
play....
```

playwright order in github actions

---

e2e/playwright/regression-tests.spec.ts

Fix existing: when engine fails export we handle the failure and alert the user

---

e2e/playwright/code-pane-and-errors.spec.ts
e2e/playwright/editor-tests.spec.ts
e2e/playwright/regression-tests.spec.ts
src/lang/abstractSyntaxTree.test.ts
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs
src/wasm-lib/kcl/src/parser/parser_impl/error.rs

Before, when there was a syntax error, it would say, `Unexpected token`.
Now, it will include the token that was unexpected, as in, `Unexpected token: )`.
This is helpful during development where there's nothing to underline or point at the problem in the editor.
Addresses #784 (doesn't close it)

Add the unexpected token to the error message

---

.eslintrc
e2e/playwright/snapshot-tests.spec.ts
src/components/LowerRightControls.tsx

failing test to go along side https://github.com/KittyCAD/modeling-app/issues/3265
Related to https://github.com/KittyCAD/modeling-app/pull/3250

Test for reconnect and theme

---

src/clientSideScene/sceneEntities.ts
src/components/ModelingSidebar/ModelingPanes/MemoryPane.tsx
src/lang/artifact.test.ts
src/lang/executor.test.ts
src/lang/modifyAst.ts
src/lang/queryAst.ts
src/lang/std/sketch.ts
src/lang/std/sketchConstraints.test.ts
src/lang/std/sketchcombos.ts
src/lang/wasm.ts
src/machines/modelingMachine.ts
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/args.rs
src/wasm-lib/kcl/src/std/extrude.rs
src/wasm-lib/kcl/src/std/revolve.rs
src/wasm-lib/kcl/src/std/segment.rs
src/wasm-lib/kcl/src/std/shapes.rs
src/wasm-lib/kcl/src/std/sketch.rs
src/wasm-lib/tests/modify/main.rs

We can store Rust types like `SketchGroup` as their own variant of `KclValue`, or as `KclValue::UserVal`. Sometimes we store in one and try to read from the other, which fails. This causes bugs, like #3338.
Instead, we should use either ::SketchGroup or ::UserVal, and stop using the other. If we stopped using ::UserVal, we'd need a new variant for every Rust type we wanted to build, including user-defined types. So I don't think that's practical.
Instead, we should store every KCL value by de/serializing it into UserVal. This is a first step along that path, removing just the SketchGroup variants. If it goes well, we can remove the other specialized variants too.
My only concern is there might be performance implications from how frequently we convert between serde_json::Value and Rust …

Remove KclValue::SketchGroup variant

---

src/lang/modifyAst.test.ts
src/lang/modifyAst.ts
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/parser/parser_impl.rs
src/wasm-lib/kcl/src/parser/snapshots/kcl_lib__parser__parser_impl__snapshot_tests__ay.snap
src/wasm-lib/kcl/src/parser/snapshots/kcl_lib__parser__parser_impl__snapshot_tests__az.snap

Like my previous PR to array expressions (https://github.com/KittyCAD/modeling-app/pull/3539), but for object expressions. Closes https://github.com/KittyCAD/modeling-app/issues/1528

KCL parser: Allow comments in multi-line object expression

---

src/wasm-lib/rust-toolchain.toml

This has several benefits:
- Rust [occasionally makes](https://internals.rust-lang.org/t/type-inference-breakage-in-1-80-has-not-been-handled-well/21374) breaking changes, and locking allows us to easily git bisect. #3128 is an example.
- Consistent, reproducible builds for a given commit instead of the exact toolchain changing over time
- New toolchain versions can introduce new, non-trivial warnings which block CI until fixed. Locking prevents a rust release at an arbitrary time from block our team.
- Documents what version an arbitrary commit was intended to build on
The drawbacks are:
- We need to manually update. Dependabot doesn't currently do this. https://github.com/dependabot/dependabot-core/issues/1702
- You need to manually …

Lock the rust toolchain version

---

e2e/playwright/command-bar-tests.spec.ts
e2e/playwright/copilot-ghost-test.spec.ts
e2e/playwright/editor-tests.spec.ts
e2e/playwright/projects.spec.ts
e2e/playwright/test-utils.ts
e2e/playwright/testing-settings.spec.ts
e2e/playwright/text-to-cad-tests.spec.ts
e2e/playwright/various.spec.ts
src/Router.tsx
src/components/FileTree.tsx
src/hooks/usePlatform.ts
src/lib/hotkeyWrapper.ts
src/lib/settings/initialKeybindings.ts
src/lib/utils.ts

...instead of Meta. Meta is typically the Windows key on Windows and Linux, and we generally shouldn't be using this.
This also fixes the display in Keybindings to use "Command" or "Control" instead of "Meta".
Note: [Meta](https://en.wikipedia.org/wiki/Meta_key) is not Control, ever. If anything, the Alt key is synonymous with Meta because of Emacs.
In my opinion, browsers are wrong for using Meta to refer to Command on Mac and Windows key on Windows. It should be [Super](https://en.wikipedia.org/wiki/Super_key_(keyboard_button)).
As far as I know, there's no standard term for Command on Mac and Control on Windows and Linux. Sometimes it's called the [primary](https://www.sublimetext.com/docs/key_bindings.html) key modifier.
Related (there's no existing issue for this PR to close):
- …

Fix keyboard shortcuts to use Control on Windows and Linux

---

src/lib/coredump.ts
src/wasm-lib/kcl/src/coredump/mod.rs

closes [#3623](https://github.com/KittyCAD/modeling-app/issues/3623)

fix coredump home page

---

e2e/playwright/projects.spec.ts
e2e/playwright/test-utils.ts

Closes #3587
So the last test I couldn't get to pass locally, I would see the following when the test opened the project, it's a little concerning, this has nothing to do with my change so going to see if this passes, but I'll ask about it in slack. just worried it could be real.

tests for file manager the stuff that should happen on disk

---

src/wasm-lib/Cargo.lock
src/wasm-lib/Cargo.toml
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/engine/conn.rs
src/wasm-lib/kcl/src/engine/mod.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/test_server.rs

Part of https://github.com/KittyCAD/engine/issues/2504:
The engine accepts this 'replay' flag now, so, accept it too and send it up to the engine.
Part of https://github.com/KittyCAD/cli/issues/847
The engine sends 'session data' now (like the API Call ID). The CLI executes KCL using this executor, and would like to get the session data after execution.

KCL executor: accept and send 'replay' flag, track session data

---

e2e/playwright/text-to-cad-tests.spec.ts

closes https://github.com/KittyCAD/modeling-app/issues/3495
Created a `lego 2x4` in the Text-to-CAD prompt to test file creation, file navigation, and file deletion.

chore: implemented e2e tests for text-to-cad file workflows

---

src/clientSideScene/CameraControls.ts
src/lib/cameraControls.ts

Resolves #3095.
No functionality change, just different UI labels.
- OS &rarr; Win/Super/Cmd
- Alt &rarr; Alt/Option
- Scroll wheel &rarr; Scroll
"Right-click drag" is a single gesture to me, so I find it easier to read "{modifier} + {gesture}". Using a mouse, first, the non-dominant hand presses the modifier key(s), and then the dominant hand does the dragging gesture.
Contrast this with "Right click + {modifier} + drag". I need to mentally combine "Reft click" and "drag", and re-order the modifier press first. Then drag with the Right button.
---
Windows
---
Linux
---
macOS

Change mouse controls display to be easier to understand

---

e2e/playwright/text-to-cad-tests.spec.ts

Adds a quick check to make sure that the file ended up on disk and is not just a phantom in the files pane.
Resolves #3651

more conclusive text to cad playwright tests

---

package.json

Merge this PR if the tests on this PR are good.
https://github.com/KittyCAD/modeling-app/pull/3675
Why? because PR's without any rust changes skip `yarn build:wasm` and so can't be sure if the build command is windows safe.

make wasm-build windows safe

---

src/lang/modifyAst/addFillet.ts

This PR addresses an issue where selecting an edge without a tag caused an error in the fillet button state. The fix adds a condition to check the tag name only for segments that are tagged, preventing the function from attempting to process untagged edges

Bug: Fillet Button - selecting edge without tag caused an Error

---

src/lib/utils.ts

I noticed that I was getting console.error logs running `yarn test` locally.

Fix platform detection in Vite

---

src/lang/modifyAst/addFillet.ts

This PR addresses an issue where selecting an edge without a tag caused an error in the fillet button state. The fix adds a condition to check the tag name only for segments that are tagged, preventing the function from attempting to process untagged edges

Bug: Fillet Button - selecting edge without tag caused an Error rev2

---

src/App.tsx
src/components/AppHeader.module.css
src/components/AppHeader.tsx
src/components/UserSidebarMenu.tsx
src/index.css

Resolves https://github.com/KittyCAD/modeling-app/issues/3712
I guess at one point in the past we had command bar be draggable and we forgot to remove it.

Fix extrude button

---

src/wasm-lib/kcl/src/ast/types/none.rs
src/wasm-lib/kcl/src/executor.rs

Previously, many KCL values could be deserialized as KCL None values. This isn't good -- the only thing you should be able to possibly deserialize as KCL None is KCL None.
Solution was to add a private field in KCL None, serialize it with a special magic number value, and then check for that magic number when deserializing

KCL None needs more specific serialization

---

src/index.css
src/main.ts

If user has dark mode set on their OS, they still see a flash of white whenever the app is opened or refreshed. This fixes that by setting the Electron window background to a theme-appropriate value.
1. [Electron docs](https://www.electronjs.org/docs/latest/tutorial/dark-mode)
2. [This Replit issue](https://github.com/replit/desktop/pull/101)
https://github.com/user-attachments/assets/8dee5126-05c9-4132-b390-f5729f36cce3

Fix flash of white background in electron dark mode

---

src/App.tsx
src/components/AppHeader.module.css
src/components/AppHeader.tsx
src/routes/SignIn.tsx

@JordanNoone pointed out that users cannot drag the app window while on the sign-in page. This fixes that.
It also reduces developer noise in the console while view the web app, which complained of "unsupported style properites" due to the app drag region, by only setting those styles in the desktop app.

Add an Electron app drag handle to sign-in page

---

src/Toolbar.tsx
src/components/Tooltip.tsx

Fixes #3781
Can be verified by running the desktop app as a local build (either dev or production build), and verifying you can click the docs links in the Toolbar's tooltips, and that they open in your default browser.

Add `no-drag` to Toolbar tooltips in Desktop, open links in default browser

---

.env.development
interface.d.ts
src/lib/desktop.ts
src/preload.ts

Using the device access token oauth flow now works on dev. Our current utility we set at in preload.ts doesn't actually affect any change on the BASE_URL, at least that the kittycad lib is able to see in node. So, we just set it for the entire process in the `.env.development` file. This means for local dev we can fully test the oauth flow ourselves!

Set BASE_URL so auth works against dev

---

src/lib/toolbar.ts

We recently enabled an initial version of Lofts in KCL, so our Toolbar should show that.
closes https://github.com/KittyCAD/modeling-app/issues/3785

Mark Loft as "KCL only" in toolbar, add a link to docs

---

.github/workflows/build-test-publish-apps.yml
electron-builder.yml

The electron-builder updater on 0.25.0 is pointing to the wrong directory

---

e2e/playwright/text-to-cad-tests.spec.ts

Expected good behavior is this test not failing in CI anymore, no other tests matter for this to be merge-ready.

Fix double locator issue with text-to-cad test

---

src/wasm-lib/kcl/benches/executor_benchmark_criterion.rs
src/wasm-lib/kcl/src/std/extrude.rs
src/wasm-lib/kcl/src/std/loft.rs
src/wasm-lib/kcl/src/std/revolve.rs
src/wasm-lib/tests/executor/inputs/slow_lego.kcl.tmpl

Adds a new KCL executor benchmark which builds a `10` wide by `n` tall lego, with varying `n`. The benchmark runs a n = 1, 2, 3 etc build, so we can get an idea of how the speed changes with size. 
This change improves execution speed by 25-36% depending on how many bumps there are. Tested by:
* Rust unit tests
* Open up modeling app, sketch a square, use the command palette to extrude it
* Open up the Bambu printer "poop chute" model, it all extrudes and works fine

Batch extrudes

---

e2e/playwright/testing-settings.spec.ts

This test has until now created a project from scratch, and created two files within that project, filling their contents by pasting it into the KCL editor. However, this pasting operation is immediately followed by navigating to the next file, without waiting to verify that we have persisted the code to the file system. This created a race; if the code persistence was fast enough it will pass (this is nearly always the case locally), but if not it would fail, showing an "empty code pane".
Since we already have tests for creating a project and files manually, I think any other tests should forego that and instead use the convenience `setupFolderFn`, so we're less likely to include races in the setup.

Don't paste in code for "Closing settings modal should..." test

---

src/index.css

Reverts part of #3794 which was ultimately unnecessary and caused regressions in theme application when the OS theme and the app/project theme were opposites.
The "flash" on window open problem was fixed in that PR without these lines, which you can verify by testing the electron app and noting that the window still matches the OS theme even with them removed.
However, with these lines removed you will no longer experience the strange half-application of the theme present before.

Remove ill-advised CSS added during #3794

---

e2e/playwright/testing-settings.spec.ts
src/clientSideScene/sceneEntities.ts
src/components/SettingsAuthProvider.tsx

Fixes #2564. We were calling something that attempted to update the client-side scene's colors, but upon investigation it wasn't doing so properly or thoroughly. This ensures it does so, and adds an E2E test to verify it.

Bugfix: update sketch mode colors on theme change

---

.github/workflows/build-test-publish-apps.yml

Closes #3817 (last PR). v0.25.1 is pointing to the standard location in the bucket, ahead of the next release.

Remove double upload workaround for 0.25.1 release

---

e2e/playwright/testing-settings.spec.ts
src/components/ModelingSidebar/ModelingPanes/index.ts
src/components/ModelingSidebar/ModelingSidebar.tsx

Fixes #3779 by adding a useEffect that watches the settings and clears out any IDs from our `openPanes` persisted state that should be hidden according to the latest settings. Adds an E2E test for it.

Bug fix: make "phantom side panes" get properly cleared

---

.github/workflows/build-test-publish-apps.yml
electron-builder.yml
package.json

Fixes #3871
Process: on a Cut release PR, go to Checks > build-publish-apps and scroll at the bottom to get the special updater-test artifacts. These points to an updater-test bucket that contains a 0.255.255 version and should always trigger an auto update on all three platforms

Add updater-test back after electron migration

---

e2e/playwright/test-utils.ts
e2e/playwright/testing-selections.spec.ts
src/lib/selections.ts

I'm pretty sure I got this working with https://github.com/KittyCAD/modeling-app/pull/3675 but the test for hover and clicks was not particularly good so that's been much improved now as well.
CCing Max and Kevin in particular, Max has worked close to this because selections of edges will affect fillet stuff and Kevin had already noticed this didn't work as it was supposed to.

Fix: Opposite adjacent edge selection

---

src/lib/selections.ts

This pr closes: #3834
It is a part of bigger project: #2606
This PR addresses and fixes two key issues within the selection logic in the `canExtrudeSelectionItem` and `getSelectionType` functions. The previous implementation had limitations when handling multiple selections, resulting in incorrect selection typing and behavior for mixed sets of selections:
**Example:**
it would return: `['extrude-wall', 1]` for a selection of single edge, which is correct
but for 2 edges it would return `['other', 2]`, which is incorrect and expected to be `['extrude-wall', 2]`
**Data Flow:**
1. `getSelectionType` uses `canExtrudeSelectionItem` to determine whether a selection is an `extrude-wall` or not, and passes the whole `selection` with all currently selected ranges stored in the …

Fix canExtrudeSelectionItem and getSelectionType for multiple selections

---

src/wasm-lib/Cargo.lock
src/wasm-lib/Cargo.toml
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/ast/modify.rs
src/wasm-lib/kcl/src/engine/conn.rs
src/wasm-lib/kcl/src/engine/conn_mock.rs
src/wasm-lib/kcl/src/engine/conn_wasm.rs
src/wasm-lib/kcl/src/engine/mod.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/args.rs
src/wasm-lib/kcl/src/std/chamfer.rs
src/wasm-lib/kcl/src/std/extrude.rs
src/wasm-lib/kcl/src/std/fillet.rs
src/wasm-lib/kcl/src/std/helix.rs
src/wasm-lib/kcl/src/std/import.rs
src/wasm-lib/kcl/src/std/loft.rs
src/wasm-lib/kcl/src/std/patterns.rs
src/wasm-lib/kcl/src/std/revolve.rs
src/wasm-lib/kcl/src/std/segment.rs
src/wasm-lib/kcl/src/std/shell.rs
src/wasm-lib/kcl/src/std/sketch.rs
src/wasm-lib/kcl/src/std/utils.rs
src/wasm-lib/tests/modify/main.rs

lib.rs/kittycad-modeling-cmds is the source of our Modeling API. It gets included in our backend APIs, and those APIs generate OpenAPI specs which are read by `openapitor` which generates the lib.rs/kittycad crate. So basically, our modeling app is using the _generated code_ instead of the _handwritten code_.
This sucks -- if you add a new field to the modeling-api crate, you have to merge PRs to the engine, api-deux, and kittycad.rs before finally you can get the new field into the modeling-app. I was pretty embarrased when @mlfarrell asked how to get a new field into the modeling app and had to explain this whole bullshit cycle. Let's fix it.
Switching to use the kittycad-modeling-cmds (aka kcmc) crate directly should speed up our dev cycle.

Replace kittycad crate with kittycad-modeling-cmds

---

src/clientSideScene/CameraControls.ts
src/components/Stream.tsx
src/lib/cameraControls.ts

`zoom.scrollCallback` was dead code. This PR now actually uses it and fixes some types to be more precise.
I wish I didn't have to choose between `MouseEvent` and `React.MouseEvent`.

Fix zoom callback on camera controls

---

src/lang/KclSingleton.ts
src/lang/modifyAst/addFillet.ts
src/machines/modelingMachine.ts

closes #3943
this PR is part of #2606 project
The current implementation of `focusPath` only supports single selections. When handling multiple selections, it fails to set focus on the new variables in the KCL code editor after operations such as `addFillet`.
1. **Updated `focusPath`**: 
Previously, `focusPath` was defined as `focusPath?: PathToNode`, which only supported a single selection. This has now been replaced with `focusPath?: Array<PathToNode>` to handle multiple selections.
2. **Loop through selections**: 
In the original implementation, `getNodeFromPath` was called for a single selection. I updated this to loop through the provided array of selections, ensuring each selection is properly processed and focused.
Additionally, there have been a couple calls to `focusPath` …

add multiple selections support for focusPath

---

package.json

* KCL Breaking change: Circle function arguments have changed from`circle([yourCenterX, yourCenterY], yourRadius, sketch, tag?)` to `circle({ center: [yourCenterX, yourCenterY], radius: yourRadius }, sketch, tag?)`  (#3860)
* Circle now has a point-and-click tool while sketching! (#3860)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.25.3...v0.25.4

Cut release v0.25.4

---

src/components/ActionButton.test.tsx
src/components/ActionButton.tsx

Fixes #3965. Adds a set of 4 little component tests to `ActionButton` to ensure I don't break this logic again. I had two branches of a ternary swapped.

UI bug fix: padding-inline logic regression

---

src/lib/selections.ts
src/lib/utils.ts

In another branch, I added a field to `Selection`, and this broke the TS type-check in this function due to how inference is done. I thought it'd be a good small fix to merge in case someone else runs into the problem before I get my big branch merged.
While I was in there, I removed some `any`s, which revealed an unhandled error case.
I learned how to type narrow with `array.filter()`. You need to use a type guard predicate. See `isNonNullable`.

Fix type-check error due to field addition

---

package.json

* Add a user-level projection setting, command, and toggle (#3983)
* Opening KCL sample now overwrites units (#3970)
* Add in min max data (#4029)
* More recursive docs types (#4028)
* One more pass of docs (#4026)
* Recusive docs (#4023)
*  preserve order of struct in autocomplete (#4018)
* Renames sketch group/extrude group (#4016)
* Updates path docs for website (#4019)
* KCL: Global rotation is fixed (#4017)
* Make engine stream react to `prefers-color-scheme` media query change (#4008)
* Kcl std lib docs use handlebars now so making changes should be better (1st pass) (#4007)
* Fix type-check error due to field addition (#4010)
* Add max-min to schemars (#4005)
* KCL: Better docs for patternTransform and int (#4002)
* Fix once cell version (#4004)
* KCL: 'rem' fn in stdlib (#3999)
* …

Cut release v0.25.5

---

src/wasm-lib/Cargo.lock
src/wasm-lib/Cargo.toml
src/wasm-lib/kcl-test-server/Cargo.toml
src/wasm-lib/kcl/Cargo.toml

does not bump hyper since it was a big change to kcl-test-server

bump reqwests and http and kittycad.rs

---

src/wasm-lib/tests/executor/main.rs

I must have missed this amongst all the "websocket closed early" noise, sorry.

Fix broken test from 'no const/let' PR

---

src/wasm-lib/tests/executor/main.rs

This file accidentally got left behind in #4063. We have an issue where this test file isn't getting run.
`wasm-lib::executor` tests pass locally, except for `visuals::kcl_test_lego` which times out.

Fix wasm executor tests to use no const keyword

---

electron-builder.yml

Fixes #4083
> Both installers https://zoo.dev/modeling-app/download and updaters https://dl.zoo.dev/releases/modeling-app/latest.yml use NSIS (.exe) at the moment. We're building and uploading .msi files, which doubles the size of the windows artifacts for no reason. Let's comment it out for now.

Disable msi builds for now

---

package.json

* KCL: No 'let' or 'const' keyword required when declaring vars (#4063)
* KCL: new standard library 'map' function (#4054)
* KCL: If-else expressions (#4022)
* Add menu item and hotkey to center view on current selection (#4068)
* KCL: Reduce can take and return any KCL values (#4094)
* File tree and projects now reload when there are external changes on the file system (#4077)
* and many more bug fixes and improvements
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.25.5...v0.25.6

Cut release v0.25.6

---

e2e/playwright/projects.spec.ts

I've been having trouble with tests on Windows that make more than one back-to-back call to our [`createProjectAndRenameIt`](https://github.com/KittyCAD/modeling-app/blob/main/e2e/playwright/test-utils.ts#L957) utility, because [the success toast on repeat file creations fails to appear for some reason](https://github.com/KittyCAD/modeling-app/actions/runs/11270794626/job/31347507518?pr=3995#step:20:1156). Just want to give a heads up that repeat calls appear to be troublesome, and I'm going to change those two tests to use the `folderSetupFn` electron test utility since the utility is used to just scaffold out the initial conditions of the test anyway.

Remove a few E2E workflows for test setup that have proven flaky on Windows

---

src/lang/std/sketchcombos.test.ts
src/lang/std/sketchcombos.ts

Fixes #2776. Updates the logic so that we sort selections in order of appearance before applying `transformSecondarySketchLinesTagFirst`. This helper function is used in the following constraints:
1. Equal length
2. Equal angle
3. Horizontal/Vertical distance
4. Angle between
5. Intersect
Adds an integration test for the utility function which selects two lines of a sketch in different orders and expects the same AST mod output.
https://github.com/user-attachments/assets/bd5a809f-51ab-4797-a66f-73104b44c230

Fix bug with selection order on multi-select constraints

---

src/lang/std/sketchcombos.ts

@jtran pointed out that mutating the user's selections could have impacts on as-yet-untested user flows, so the more responsible way to implement the fix for #2667 would be to create a separate sorted array of the `codeBasedSelections` to operate on.

Don't mutate the user's `codeBasedSelections` when they apply a multi-selection constraint

---

docs/kcl/patternCircular2d.md
docs/kcl/patternCircular3d.md
docs/kcl/patternLinear2d.md
docs/kcl/patternLinear3d.md
docs/kcl/types/CircularPattern2dData.md
docs/kcl/types/CircularPattern3dData.md
docs/kcl/types/LinearPattern2dData.md
docs/kcl/types/LinearPattern3dData.md
src/wasm-lib/kcl/src/docs/mod.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/patterns.rs
src/wasm-lib/tests/executor/inputs/focusrite_scarlett_mounting_braket.kcl
src/wasm-lib/tests/executor/inputs/global-tags.kcl
src/wasm-lib/tests/executor/inputs/lego.kcl
src/wasm-lib/tests/executor/inputs/server-rack-heavy.kcl
src/wasm-lib/tests/executor/inputs/server-rack-lite.kcl
src/wasm-lib/tests/executor/inputs/slow_lego.kcl.tmpl
src/wasm-lib/tests/executor/main.rs

@jgomez720 requests pattern calculations take the total number of instances, not the number of extra repetitions to do. This is how we designed the patternTransform API, but we didn't do that for patternLinear/Circular.
Also enforced that the number of instances must be >= 1.
This is a **breaking change**.

KCL: Pattern repetitions now pattern instances

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/lsp/kcl/mod.rs

Continue more renames after #3360. Extracted from #4149.

Rename things to be clearer about expression vs. value

---

src/wasm-lib/kcl/src/std/array.rs
src/wasm-lib/tests/executor/inputs/no_visuals/double_map.kcl
src/wasm-lib/tests/executor/no_visuals.rs

Previously running `map` would change the output of the array, it would go from array of numbers to an array of objects that contain numbers. Fixed now.
We should do https://github.com/KittyCAD/modeling-app/issues/1130 to make this impossible in the future.

Bugfix: double map

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/ast/types/execute.rs
src/wasm-lib/kcl/src/std/args.rs

`types.rs` is really, really big. I've moved executing AST nodes into their own file.

KCL refactor: Move execution into its own file

---

src/wasm-lib/kcl/src/ast/types.rs

I broke the typescript bindings in https://github.com/KittyCAD/modeling-app/pull/4193 -- basically the `digest: Option<Digest>` fields previously allowed Typescript to not set a value for the `digest` key at all, but somehow my change made it required in the Typescript.
Fix is to apply `#[ts(optional)]`, see docs at https://docs.rs/ts-rs/latest/ts_rs/trait.TS.html#struct-field-attributes

Fix broken digest code

---

make-release.sh

This adds a pattern to match modeling-app `v{major}.{minor}.{patch}` tags, and not `kcl-*` tags or others

Fix auto changelog in make-release.sh

---

e2e/playwright/file-tree.spec.ts
src/components/FileTree.tsx
src/lang/codeManager.ts

Writing to kcl files on per-key press (very old behavior that has existed even when the app was in Tauri) is causing the file system reload routines to "thrash" hard when users are (rightfully) mashing their keyboards. This fixes that, and fixes the issues coreypdx was talking about on Discord, losing their focused file.
I'm taking Monday, Tuesday off but I'd like to push this over the line and release as soon as we're able to because losing work = trust melting

Buffer file writes, because writing to file after every keypress has bad consequences

---

src/wasm-lib/kcl/src/ast/types/execute.rs
src/wasm-lib/tests/executor/inputs/no_visuals/array_range_negative_expr.kcl
src/wasm-lib/tests/executor/no_visuals.rs

Follow-up to https://github.com/KittyCAD/modeling-app/pull/4151. Allows negative start and end in range expressions.

Support negative start and end in ranges

---

docs/kcl/types/Sketch.md
docs/kcl/types/SketchSet.md
src/clientSideScene/sceneEntities.ts
src/clientSideScene/segments.ts
src/components/ModelingSidebar/ModelingPanes/MemoryPane.tsx
src/lang/artifact.test.ts
src/lang/executor.test.ts
src/lang/queryAst.ts
src/lang/std/sketch.ts
src/lang/std/sketchConstraints.ts
src/lang/std/sketchcombos.ts
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/extrude.rs
src/wasm-lib/kcl/src/std/segment.rs
src/wasm-lib/kcl/src/std/shapes.rs
src/wasm-lib/kcl/src/std/sketch.rs
src/wasm-lib/tests/executor/inputs/member_expression_sketch.kcl

Rename Sketch.value to Sketch.paths

---

.github/workflows/build-test-publish-apps.yml

Separate debug/release electron-builder to help mac job

---

package.json

* Disable rotate on start new sketch (#4287)
* Stop propagation of camera clicks after drags (#4257)
* Rename Sketch.value to Sketch.paths (#4272)
* Fix engine connection break when starting onboarding from a fresh install (#4263)
* Support negative start and end in ranges (#4249)
* Remove setInterval implementations from camera controls (#4255)
* Fix job name for printers (#4234)
* Buffer file writes, because writing to file after every keypress has bad consequences (#4242)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.26.0...v0.26.1

Cut release v0.26.1

---

docs/kcl/types/TagEngineInfo.md
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/segment.rs
src/wasm-lib/kcl/src/std/sketch.rs

See "Problem 2" in https://github.com/KittyCAD/modeling-app/issues/4297
This is a pure refactor, it should not change any behaviour at all.
It adds more information into the tag system, but nothing reads that
extra information yet. It will be used to address problem 3 of the above
issue.

Tags should refer to full paths, not just base paths.

---

src/clientSideScene/sceneEntities.ts
src/clientSideScene/sceneInfra.ts
src/clientSideScene/segments.ts

Currently the console gets spammed with errors when creating draft lines, making for noisy development. This was because draft segments were receiving the normal segment onMouseEnter and onMouseLeave listeners, and were being provided constraint overlays, even though they aren't yet in the AST. This marks those segments as draft so they can be excluded from receiving the listeners or the overlay components.
No new tests because this removes console.log only behavior. All the existing tests passing should verify no behavior has changed.
https://github.com/user-attachments/assets/54ede2b0-8646-47c4-bdfd-73f7685b9fbd

Chore: Don't let draft lines receive mouseEnter/Leave events, or create invalid overlays

---

.github/workflows/cargo-test.yml
docs/kcl/types/Path.md
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/extrude.rs
src/wasm-lib/kcl/src/std/sketch.rs
src/wasm-lib/kcl/src/std/utils.rs

Problem 1 of https://github.com/KittyCAD/modeling-app/issues/4297

Bugfix: arc paths were stored as straight line paths

---

docs/kcl/types/TagEngineInfo.md
src/wasm-lib/kcl/src/ast/types/execute.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/args.rs
src/wasm-lib/kcl/src/std/segment.rs
src/wasm-lib/kcl/src/std/sketch.rs

Tags can refer to either a surface, or a path. Tags track what they're tagging with two fields: `Option<Path>` and `Option<Surface>`. This means as more things can be tagged, we'll have a bunch of options and only one can be Some at a given time. This should be an enum instead, so the compiler can enforce that only one thing is being tagged.
Also I want to allow tags to refer to points, so I'd like to make this enum before I add a new possible variant.

Track tagged geometry with an enum, not options

---

docs/kcl/types/TagEngineInfo.md
src/wasm-lib/kcl/src/ast/types/execute.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/args.rs
src/wasm-lib/kcl/src/std/segment.rs
src/wasm-lib/kcl/src/std/sketch.rs

This reverts commit 4a62862ca002d705d95b18eda94586346473ab58.
The commit had a false assumption: that a tag could refer to a path XOR surface. In reality, when a sketch is extruded into a solid, its tags which pointed to paths now also point to the new surface made from that path. 
Perhaps tags _shouldn't_ be able to refer to both, but that is a breaking change. In fact, it broke the [poop chute model](https://github.com/KittyCAD/jdn_designs/blob/main/bambu%20chute.kcl), which @mlfarrell was debugging for unrelated reasons.
While we think about the desired behaviour, let's revert this.

Revert "Track tagged geometry with an enum, not options (#4333)"

---

src/wasm-lib/kcl/src/std/assert.rs

Without this, you can get a funny error message, such as:
assert failed because 42 != 42: number is not 42
I'm assuming an epsilon of zero is never useful because we're dealing with floating point.

Error if assertEqual's epsilon value is invalid

---

src/wasm-lib/justfile
src/wasm-lib/kcl/src/std/assert.rs

@franknoirot admin merged #4329 without verifying that CI was green (outside contributor PRs do not run our CI for security reasons). This fixes the clippy lint fix and docs generation issue present in that PR, causing a real red on main.

Fix CI docs generation after #4329

---

.github/workflows/cargo-check.yml
package.json
src/wasm-lib/justfile
src/wasm-lib/kcl/README.md

Prior to this change, our commands didn't actually lint everything.

Fix lint scripts to check all targets

---

src/wasm-lib/tests/executor/inputs/no_visuals/array_elem_push_fail.kcl
src/wasm-lib/tests/executor/no_visuals.rs

Adding test requested by @jtran in https://github.com/KittyCAD/modeling-app/pull/4232#discussion_r1819885258
Ensures that when an element is pushed to an array, that element is not available on the original array.

Added test to ensure array push is immutable

---

src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/token.rs
src/wasm-lib/kcl/tests/add_lots/tokens.snap
src/wasm-lib/kcl/tests/array_elem_push/tokens.snap
src/wasm-lib/kcl/tests/array_range_expr/tokens.snap
src/wasm-lib/kcl/tests/array_range_negative_expr/tokens.snap
src/wasm-lib/kcl/tests/comparisons/tokens.snap
src/wasm-lib/kcl/tests/cube/tokens.snap
src/wasm-lib/kcl/tests/double_map_fn/tokens.snap
src/wasm-lib/kcl/tests/helix_ccw/tokens.snap
src/wasm-lib/kcl/tests/if_else/tokens.snap
src/wasm-lib/kcl/tests/index_of_array/tokens.snap
src/wasm-lib/kcl/tests/property_of_object/tokens.snap
src/wasm-lib/kcl/tests/sketch_in_object/tokens.snap

Just like in AST nodes.
Also I think "is_top_level" communicates intention better than is_default

Proposal: module ID = 0 gets skipped when serializing tokens too

---

e2e/playwright/testing-settings.spec.ts
src/components/FileTree.tsx
src/components/SettingsAuthProvider.tsx
src/editor/plugins/lsp/kcl/index.ts
src/hooks/useRefreshSettings.ts
src/lang/KclSingleton.ts
src/lang/codeManager.ts
src/lib/settings/settingsUtils.ts

This reverts commit ad1cd56891bc78c4554129350416e092b8c452c8.

Revert "Deflake project settings override on desktop (#4370)"

---

e2e/playwright/testing-settings.spec.ts
package.json

* New performance metrics window available from lower-right corner button (#4145)
* Reverted issue that caused major slowdown while using app (#4450)
* <kbd>Alt</kbd> / <kbd>Option</kbd> + drag on numbers in code editor is more precise (#3997)
**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.26.3...v0.26.4

Cut release v0.26.4

---

Makefile
README.md

WASM dev builds are so slow that they trigger race conditions, and the UI breaks. We've accidentally released dev builds before. No one should be using dev builds, unless you absolutely know what you're doing. Many of us have stopped using this for dev a long time ago.

Remove references to wasm-dev build

---

e2e/playwright/editor-tests.spec.ts
src/editor/manager.ts

The function `overrideTreeHighlighterUpdateForPerformanceTracking` is somehow causing an editor lock-up if a user applies an autocompletion suggestion.
This removes the only call to it, and adds an E2E test expectation which ensures that using autocomplete does not result in any diagnostic errors.

Bug fix: fix autocompletion regression

---

src/editor/manager.test.ts
src/editor/manager.ts
src/lang/KclSingleton.ts

Jon, Lee, and myself came across this block of code when debugging a codemirror issue. I wanted to make this code quicker and more straight forward. I also added unit tests.

chore: implemented a O(n) unique and added unit tests

---

src/wasm-lib/kcl/src/std/args.rs
src/wasm-lib/kcl/src/std/patterns.rs

Two changes:
- Rename `FromKclValue::from_mem_item` to `FromKclValue::from_kcl_val`. "memory item" is what we used to call KCL value.
- Simplify the macros I use in args.rs to simplify KCL parsing. The macros `fields!`, `fields_recurse!`, `fields_recurse_opt!` etc have all been rolled into one macro, `let_field_of!`

Refactor: Clean up FromKclValue code

---

src/lang/queryAst.test.ts
src/lang/queryAst.ts

Before, moving the cursor to either an import statement or an if-else dumped an error in the console. This PR makes it so that we can properly find the paths into those node types.
Related:
- #4080
- #4022

Fix finding path to node for import and if-else

---

src/clientSideScene/sceneEntities.ts

When using the center rectangle tool it would not write code to the editor when the workflow finished.
Added the explicit line to update the AST and Code Mirror since this is a new pattern. Similar to the corner rectangle tool.

fix: center rectangle code writing bug

---

src/wasm-lib/kcl/src/parser/parser_impl.rs
src/wasm-lib/kcl/src/parser/snapshots/kcl_lib__parser__parser_impl__snapshot_tests__bi.snap

If the key and value in an object literal use the same identifier, allow abbreviating it.
Basically these two are now equivalent:
```
x = 2
obj = { x: x, y: 3}
```
```diff
x = 2
- obj = { x: x, y: 3}
+ obj = { x, y: 3}
```
This syntax is used in JS, Rust and probably elsewhere too.
Here's a more realistic example. Before:
```
radius = 10
startSketchAt([0, 0])
|> circle({center: [0, 0], radius: radius}, %)
```
After:
```diff
radius = 10
startSketchAt([0, 0])
- |> circle({center: [0, 0], radius: radius}, %)
+ |> circle({center: [0, 0], radius}, %)
```

KCL: Object literals like {x} as shorthand for {x: x}

---

src/wasm-lib/kcl/src/std/patterns.rs

Part of https://github.com/KittyCAD/modeling-app/issues/4543
Changes patternLinear3D's implementation so it just calls into patternTransform instead of needing all its own logic and API calls.

KCL refactor: implement patternLinear3D as patternTransform

---

src/wasm-lib/kcl-test-server/src/lib.rs
src/wasm-lib/kcl/src/errors.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/lib.rs
src/wasm-lib/kcl/src/test_server.rs

Some clients (e.g. the simulation tests) want to know why a KCL program failed. Was it because of a network error? Or because the client wasn't authorized properly? Or was it a KCL runtime type error?
It's difficult for clients to ask these questions, because the interpreter just returns Anyhow error, basically just a string.
Instead, we should return different variants of an Error enum for different kinds of errors.
This lets us render nice Cargo-style error messages that show the exact KCL line where an error occurred, instead of just printing off a source range. We have that in the CLI, but I'd like it for running normal KCL unit tests.
This is a pure refactor, it doesn't change any behaviour, it just stops hiding the specific error types via anyhow. No testing needed. If it compiles, …

KCL: Executor returns specific errors, not anyhow

---

packages/codemirror-lsp-client/package.json
packages/codemirror-lsp-client/yarn.lock

This makes `@codemirror/autocomplete` match the version in the root directory.

Fix yarn tsc in codemirror-lsp-client

---

package.json
packages/codemirror-lsp-client/package.json
packages/codemirror-lsp-client/src/client/codec/demuxer.ts
packages/codemirror-lsp-client/src/client/codec/queue.ts
packages/codemirror-lsp-client/yarn.lock
yarn.lock

We were running into `yarn tsc` errors in the root directory. Upgrading typescript fixed them.
Related #4568.

Upgrade to typescript 5.7.2

---

src/wasm-lib/kcl/src/kcl_value.rs
src/wasm-lib/kcl/src/std/args.rs
src/wasm-lib/kcl/src/std/patterns.rs

This way, if we want to change our key-value representation later (e.g. using a tree map instead of a hash map) we can, easily, in just one place.

KCL refactor: Type alias for KCL object fields

---

src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/kcl_value.rs

- Named constant for empty metadata
- Combine two `impl KclValue` blocks into one.

KCL: Two tiny refactors

---

docs/kcl/types.md

Follow up to #4519 and other recent changes to KCL:
- Record initialization uses `=` instead of `:`
- Fix formatting when using pipe expression
- `segLen` and `segAng`  no longer take `%` (typo in commit msg, sorry)

Update KCL Types doc

---

.github/workflows/build-apps.yml
.github/workflows/publish-apps-release.yml
README.md

Fixes #4586
Not sure how else to work around the limit we hit during #4581 with the publish-apps-release workflow not triggered as the draft release had originally been created by github-actions and not a user. This should get us going for now with minimal user input still. README process updated too.

Remove auto creation of the draft release

---

src/wasm-lib/Cargo.lock

https://github.com/rustls/rustls/releases
https://github.com/rustls/pki-types/releases/tag/v%2F1.10.0

Bump rustls from 0.23.13 to 0.23.19 and rustls-pki-types

---

src/wasm-lib/kcl/src/ast/modify.rs
src/wasm-lib/kcl/src/ast/types.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/lint/rule.rs
src/wasm-lib/kcl/src/source_range.rs
src/wasm-lib/kcl/src/token.rs

I've tested locally that kcl.py still builds (annoyingly I ran nightly rustfmt, so there is some reordering of imports included here too, sorry).

Reduce Python API surface area to what is necessary for kcl.py

---

package.json
yarn.lock

https://github.com/rustwasm/wasm-pack/releases/tag/v0.13.1
Not sure why Dependabot hasn't upgraded this in a while.

Bump wasm-pack from 0.13.0 to 0.13.1

---

src/wasm-lib/Cargo.lock

https://github.com/rust-lang/hashbrown/blob/master/CHANGELOG.md
Addresses this security advisory:
https://github.com/advisories/GHSA-wwq9-3cpr-mm53

Bump hashbrown from 0.15.0 to 0.15.2

---

src/clientSideScene/CameraControls.ts

The axis for sketch mode can have a rotation applied when entering the sketch mode which is wrong.
Do not look perpendicular to your sketch plane then enter the sketch mode on that plane. Some rotation will be applied 
Set the orientation from the cam settings directly to the camera instead of recomputing a new up vector.
Turns out we can use the up vector from the camera settings that is returned instead of hard coding it to `<0,1,0>`. 
https://github.com/user-attachments/assets/6bc8725d-42bb-45e4-bc40-07991b5575c7

fix: upon entering sketch mode, axis do not rotate.

---

src/wasm-lib/Cargo.toml
src/wasm-lib/derive-docs/Cargo.toml
src/wasm-lib/kcl-test-server/Cargo.toml
src/wasm-lib/kcl-to-core/Cargo.toml
src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/fuzz/Cargo.toml
src/wasm-lib/kcl/src/docs/gen_std_tests.rs
src/wasm-lib/kcl/src/engine/conn.rs
src/wasm-lib/kcl/src/engine/mod.rs
src/wasm-lib/kcl/src/executor.rs
src/wasm-lib/kcl/src/std/mod.rs
src/wasm-lib/kcl/src/std/sketch.rs

Here is the lint: https://rust-lang.github.io/rust-clippy/stable/index.html#/iter_over_hash_type
Now all crates inherit the lints from the workspace.

Fix to never have undefined iteration order and lint against it

---

.github/workflows/build-apps.yml
scripts/flip-files-to-nightly.sh

Follow up to #4654. 
- Fixing the lack of pulling tags that caused the original bump https://github.com/KittyCAD/modeling-app/actions/runs/12173028479/job/33968763493
- Make things more consistent with the way we do things for release, changing the notes at publish times, reusing the `yarn files:set-notes` script. Successful in the manual push of 24.12.5 I did at https://github.com/KittyCAD/modeling-app/actions/runs/12179515583

Cleaner nightly release notes

---

src/wasm-lib/justfile
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/parsing/snapshots/kcl_lib__parsing__parser__snapshot_tests__kw_function_decl_all_labeled.snap
src/wasm-lib/kcl/src/parsing/snapshots/kcl_lib__parsing__parser__snapshot_tests__kw_function_decl_first_unlabeled.snap
src/wasm-lib/kcl/src/simulation_tests.rs
src/wasm-lib/kcl/src/unparser.rs
src/wasm-lib/kcl/tests/kw_fn/ast.snap
src/wasm-lib/kcl/tests/kw_fn/input.kcl
src/wasm-lib/kcl/tests/kw_fn/program_memory.snap

When declaring a function, its first parameter is allowed to be prefixed with `@`. This means that when users call this function, they don't have to label this argument.
Only the first parameter is allowed this prefix, no others.

AST: Allow unlabeled kw args

---

src/wasm-lib/src/wasm.rs

Does not change behaviour. It just clarifies whether JS is passing a string containing KCL source code, or containing a JSON-stringified KCL AST.

KCL refactor: Fix argument names

---

INSTALL.md

Fixes #4511
For now this is a new INSTALL.md file, we need to see if we should get it pulled and displayed by the download page on the website. Or at least just point to it

Add installation instructions for all platforms

---

src/components/Settings/AllKeybindingsFields.tsx
src/components/Settings/KeybindingsSectionsList.tsx
src/lib/settings/initialKeybindings.ts

Recreation of #4601 in an authorized branch, @TomPridham is the author of this code.
Here is his original PR description (thanks for writing it Tom!):
I couldn't find an existing issue. I noticed the scrollto behavior didn't work for keybind settings that included whitespace because they were generating invalid ids, e.g. `id="categoryCommand Palette"`. It isn't a problem for the User settings because the display strings were `decamelized` object properties
before:
[Screencast from 2024-11-27 13-30-48.webm](https://github.com/user-attachments/assets/8c993a31-6a36-4aa4-80ae-88416405848f)
after:
[Screencast from 2024-11-27 13-32-29.webm](https://github.com/user-attachments/assets/d624ed67-c29d-416c-a15a-ba3b0c5baa42)

fix: replace whitespace with a `-` so that ids are valid and scroll to works

---

src/wasm-lib/kcl/src/execution/exec_ast.rs
src/wasm-lib/kcl/src/execution/kcl_value.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/simulation_tests.rs
src/wasm-lib/kcl/src/std/args.rs
src/wasm-lib/kcl/tests/kw_fn/ast.snap
src/wasm-lib/kcl/tests/kw_fn/input.kcl
src/wasm-lib/kcl/tests/kw_fn/program_memory.snap
src/wasm-lib/kcl/tests/kw_fn_too_few_args/ast.snap
src/wasm-lib/kcl/tests/kw_fn_too_few_args/execution_error.snap
src/wasm-lib/kcl/tests/kw_fn_too_few_args/input.kcl
src/wasm-lib/kcl/tests/kw_fn_unlabeled_but_has_label/ast.snap
src/wasm-lib/kcl/tests/kw_fn_unlabeled_but_has_label/execution_error.snap
src/wasm-lib/kcl/tests/kw_fn_unlabeled_but_has_label/input.kcl

Part of https://github.com/KittyCAD/modeling-app/issues/4600
You can now call a user-defined function via keyword args. E.g.
```
fn increment(@x) {
return x + 1
}
fn add(@x, delta) {
return x + delta
}
two = increment(1)
three = add(1, delta: 2)
```

KCL keyword args: calling user-defined functions

---

src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/parsing/snapshots/kcl_lib__parsing__parser__snapshot_tests__kw_function_decl_with_default_and_type.snap
src/wasm-lib/kcl/src/parsing/snapshots/kcl_lib__parsing__parser__snapshot_tests__kw_function_decl_with_default_no_type.snap
src/wasm-lib/kcl/src/simulation_tests.rs
src/wasm-lib/kcl/src/unparser.rs
src/wasm-lib/kcl/tests/kw_fn_with_defaults/ast.snap
src/wasm-lib/kcl/tests/kw_fn_with_defaults/input.kcl
src/wasm-lib/kcl/tests/kw_fn_with_defaults/program_memory.snap

KCL parser: fns with optional keyword args can set defaults

---

src/main.ts

closes https://github.com/KittyCAD/modeling-app/issues/4262
documentation https://www.electronjs.org/docs/latest/api/app
When booting multiple applications the N+1 applications take 7-8s seconds to boot because of some lock not being released. We are booting multiple electron applications instead of booting multiple BrowserWindows
Using the `app` API from electron and a suggestion [here](https://github.com/electron/electron/issues/13163) this will allow us to boot multiple electron BrowserWindows and track them. This speeds up the boot time. This is all using the native `app` API. 
One thing I don't exactly know is if this is the most graceful way to exit the application that should not boot? This still allows the second instance to be kicked off since `app.requestSingleInstanceLock` was …

chore: implemented multiple instances instead of multiple appications?

---

src/index.css

Fixes #4715
Changed the color to `primary` so it's consistently contrasting with the background in dark and light modes, see below.

Change diagnostic action button to primary color

---

src/wasm-lib/kcl/src/execution/exec_ast.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/parsing/ast/digest.rs
src/wasm-lib/kcl/src/parsing/ast/mod.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/unparser.rs
src/wasm-lib/kcl/src/walk/ast_node.rs
src/wasm-lib/kcl/src/walk/ast_visitor.rs
src/wasm-lib/kcl/tests/sketch_on_face_start/ast.snap
src/wasm-lib/kcl/tests/sketch_on_face_start/input.kcl
src/wasm-lib/kcl/tests/sketch_on_face_start/program_memory.snap

This lets you write `sub-expr as foo` in most places we'd expect an expression and this is mostly equivalent to writing `foo = sub-expr` and replacing the sub-expr with foo (i.e., it introduces a reference to the variable). The work isn't finished because you can't currently use these variables as tags since we don't apply the magic to update the reference when e.g., extruding.

Implement `as` aliases for sub-expressions

---

src/lang/wasm.ts

See `__wbg_init()` in `src/wasm-lib/pkg/wasm_lib.js`.

Fix wasm init deprecation warning

---

src/main.ts

Reverts KittyCAD/modeling-app#4733
@nadr0 I believe we missed a few corner cases here. Jordan reported "if I switch to another program and switch back, whole app goes white and it resets to the directory screen". And if I grab the latest nightly (v24.12.11) I also have weird behaviours that I didn't catch in my testing of #4733, including getting new instances anytime I'm clicking on the dock icon in macOS or spotlight search for the app already open to re focus it, aka we're too aggressive on creating new windows. Think we should revert and recreate this branch and do a whole lot more testing this week before merging again. Gut feeling is we need more checks in the `on('activate')` event handler.

Revert "chore: implemented multiple instances instead of multiple appications?"

---

.github/workflows/build-apps.yml

Safety flags we needed to enable when we were building signed release candidates in Cut release PRs, which was considered unsafe by electron-builder. We don't need that anymore with the new workflow (see https://github.com/KittyCAD/modeling-app/tree/ec49b0752ecf6a63758048c0ed6352b6a592fc30?tab=readme-ov-file#release-a-new-version)

Remove flags we had for code sign on Cut Release PRs

---

src/lang/std/artifactGraph.ts
src/lib/commandBarConfigs/validators.ts

I noticed this post the revolve merge and it triggered me haha, we should not be forcing types like this with `as`.
Really these util functions should be defined like
```ts
export function isSolid2D(artifact: Artifact): artifact is Solid2DArtifact {
return artifact.type === 'solid2D'
}
export function isSegment(artifact: Artifact): artifact is SegmentArtifact {
return artifact.type === 'segment'
}
export function isSweep(artifact: Artifact): artifact is SweepArtifact {
return artifact.type === 'sweep'
}
```
But when I looked at how they were used, it was evident, they simply were not needed anyway.

Remove type coercion

---

docs/kcl/reduce.md
src/wasm-lib/kcl/src/std/array.rs
src/wasm-lib/kcl/src/std/assert.rs
src/wasm-lib/kcl/src/std/chamfer.rs
src/wasm-lib/kcl/src/std/convert.rs
src/wasm-lib/kcl/src/std/extrude.rs
src/wasm-lib/kcl/src/std/fillet.rs
src/wasm-lib/kcl/src/std/helix.rs
src/wasm-lib/kcl/src/std/import.rs
src/wasm-lib/kcl/src/std/loft.rs
src/wasm-lib/kcl/src/std/math.rs
src/wasm-lib/kcl/src/std/mirror.rs
src/wasm-lib/kcl/src/std/patterns.rs
src/wasm-lib/kcl/src/std/planes.rs
src/wasm-lib/kcl/src/std/polar.rs
src/wasm-lib/kcl/src/std/revolve.rs
src/wasm-lib/kcl/src/std/segment.rs
src/wasm-lib/kcl/src/std/shapes.rs
src/wasm-lib/kcl/src/std/shell.rs
src/wasm-lib/kcl/src/std/sketch.rs
src/wasm-lib/kcl/src/std/units.rs

I removed `let` in pseudocode in reduce docs. Could go either way.

Fix KCL warnings in doc comments from let, const, and new fn syntax

---

.codespellrc
src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/parsing/token/mod.rs
src/wasm-lib/kcl/src/parsing/token/tokeniser.rs

This reverts commit 4b6bbbe2c5e4b3ed50329ca3c2aac812f98d6dce (PR #4769) because these tests are failing:
FAIL [   0.013s] kcl-lib parsing::parser::tests::assign_brackets
FAIL [   0.012s] kcl-lib parsing::parser::tests::test_arg

Revert "warn on unneccessary brackets (#4769)"

---

src/lang/std/__snapshots__/artifactGraph.test.ts.snap
src/lang/std/artifactGraph.test.ts
src/lang/std/engineConnection.ts
src/lang/wasm.ts

Follow up to #4603 to make the values of `SourceRange`s in `OrderedCommands` match the TS type. When sending engine commands in Rust/WASM, it calls the TS with Rust source ranges where the value is a `number`. We need to convert that to `boolean` before storing it in our data structures.
The proxying through JSON erases the type. When JSON parsing, we need to manually say what we believe the type to be. So this slipped through.
@nrc, FYI.

Fix SourceRange values in OrderedCommands to match the TS type

---

.github/workflows/cargo-test.yml

We've had lots of problems with people merging red CI resulting from `cargo test` not being required. Auto-merge ignores it.

Always run cargo test in CI so that it can be required

---

src/wasm-lib/kcl/src/docs/mod.rs

Since using the old syntax is a warning now, we need to start using the new syntax.

Change KCL completion to use new object/record syntax

---

src/wasm-lib/kcl/src/errors.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/parsing/token/mod.rs
src/wasm-lib/kcl/src/parsing/token/tokeniser.rs
src/wasm-lib/tests/executor/inputs/lsystem.kcl

This PR parses but not does not store in the AST a variety of syntax which I think is enough to implement unit of measure types. I don't have a full design, but this reservation does not commit us, it just ensures we have space. (It was also useful to think through the design). The syntax which is parsed is:
- numeric literal suffixes, both `42mm` and `42_mm` (I'm not sure if we want one or the other or both) and `42_` to assert no unit (i.e., a counting number). To this end, this PR makes leading underscores have non-referencing semantics, i.e., they can be used to declare unused constants.
- UoM-generic types, e.g., `number(mm)` (note I'm using `()` deliberately so we could if we want use `<>` purely for type generics).
- type ascription, i.e., `e: T` this is not directly related to …

Reserve syntax for units of measure

---

src/wasm-lib/kcl/src/lsp/kcl/mod.rs
src/wasm-lib/kcl/src/lsp/tests.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs

Closes #4752.
Needs #4767 to land and then this needs a rebase since this exposes a bug fixed in that PR.

Support completions from import statements

---

src/wasm-lib/kcl/src/execution/annotations.rs
src/wasm-lib/kcl/src/execution/kcl_value.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/parsing/token/mod.rs
src/wasm-lib/kcl/src/unparser.rs

To complete the per-file units work, the following is required:
- probably some tests for the units annotations
- actually use the units settings from the exec state in the std lib functions
- decide on the units names: we've previously used `units`. In this PR I've used `defaultLengthUnit` and `defaultAngleUnit` which is more self-explanatory, but more verbose. Not sure what we should actually go with.
- remove units from the project settings in Rust and the frontend, and (I think) from the CLI or engine API or anywhere else they are used. Not sure if we need to do this gently or if we should just make a breaking change.
- any frontend/UI support
- maybe and non-blocking, track units for values (I've done a little work on this already)

Annotations syntax and per-file default units preparatory work

---

src/wasm-lib/kcl/src/execution/exec_ast.rs
src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/std/args.rs

Part of #4600
KCL functions can declare one special argument that doesn't require a label on its parameter when called.
This PR will default that arg to % (the current pipeline) if not given.

KCL: Unlabeled first param defaults to %

---

docs/kcl/index.md
docs/kcl/patternTransform.md
docs/kcl/reduce.md
docs/kcl/segEnd.md
docs/kcl/segStart.md
docs/kcl/startSketchAt.md
src/wasm-lib/kcl/src/std/array.rs
src/wasm-lib/kcl/src/std/patterns.rs
src/wasm-lib/kcl/src/std/segment.rs
src/wasm-lib/kcl/src/std/sketch.rs

Part of #4652.
Instead of `startSketchAt([1, 2])` where the XY plane is implicit, use:
```kcl
startSketchOn('XY')
|> startProfileAt([1, 2], %)
```

Deprecate startSketchAt() stdlib function

---

src/components/ModelingSidebar/ModelingPanes/FeatureTreePane.tsx
src/lib/operations.test.ts
src/lib/operations.ts

I made a few fixes to the operations filters.
I changed the signature of filter functions because they needed to consume an entire list of operations at once. Filtering out stdlib calls inside user-defined functions needed this. It needs to track the call depth by traversing the entire list. It can't work only looking locally at or around a single index.

Feature tree filter tests

---

src/lang/KclSingleton.ts
src/lang/std/__snapshots__/artifactGraph.test.ts.snap
src/lang/std/artifactGraph.test.ts
src/lang/std/artifactGraph.ts
src/lang/std/engineConnection.ts
src/lang/wasm.ts
src/wasm-lib/kcl/src/execution/artifact.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/std/sketch.rs

Stacked on #4828.
Addresses https://github.com/KittyCAD/modeling-app/pull/4828#discussion_r1889345877.
See the console.log in `KclSingleton.ts`. Note there's 2 cases: plane and face.

Add Rust side artifacts for startSketchOn face or plane

---

src/components/FileTree.tsx
src/lang/codeManager.ts

Writing to disk is too slow, it has a `setTimeout` to prevent an issue with the `useFileSystemWatcher` when you externally edit a source file and it writes back into the code pane.
I am disabling the feature that allows externally editing the KCL source code. This only works when your file tree is opened which is a gotcha anyway. Once we implement a better file writing system we can fix this watcher.
```
// Only write our buffer contents to file once per second. Any faster
// and file-system watchers which read, will receive empty data during
// writes.
```
- 1000ms to 10ms to keep this same workflow for the comment about `React`.
- Disable the `useFileSystemWatcher` that writes to the code pane
- Implement better file writing system
- Implement a file watcher that works when you have …

chore: disabled file watcher which prevents faster file write

---

.github/workflows/e2e-tests.yml
e2e/playwright/basic-sketch.spec.ts

Part of the list of follow-ups after #4484, see #4838

Re-enable test 'code pane closed at start' after electron migration

---

src/clientSideScene/sceneEntities.ts
src/clientSideScene/sceneInfra.ts
src/lib/toolbar.ts
src/machines/modelingMachine.ts

This adds a 1st pass for the 3-point circle tool.
There is disabled code to drag around the 3 points and redraw the circle and
a triangle created by those points. It will be enabled in a follow-up PR
when we have circle3Point in the stdlib.
For now, all it does is after the 3rd click, will insert circle center-radius
KCL code for users to modify.

Add 3-point circle tool

---

src/wasm-lib/src/wasm.rs

Replaces/closes #4798. Fixes #4739.
We no longer propagate the error. Log and ignore it instead.
@TomPridham

fix: don't error on failure to fetch privacy settings

---

package.json

Use `MIT` in package.json.
Matches the `LICENSE` file. Consistent with `packages/codemirror-lsp-client/package.json`.
Field was set to `none` in 6ba050727a0e424d04b74a6cd3c0e41d55c078c3 in /pull/3315.
I guess that was just done in a rush, because there was already an MIT LICENCE file present (/pull/765).

Match package license to LICENSE file

---

src/lib/toolbar.ts

Now that it's available, it shouldn't be there anymore.
Before:
After:

Remove the old Loft GitHub issue link in the toolbar

---

src/wasm-lib/kcl/fuzz/Cargo.lock
src/wasm-lib/kcl/fuzz/Cargo.toml
src/wasm-lib/kcl/fuzz/fuzz_targets/parser.rs

Since adding workspace lints in #4665, the fuzz crate has been broken. It isn't part of the workspace. When I fixed this, cargo decided that lots of libraries needed updating.
Also, the parser fuzz target was using the old parser API. So I updated that too.

Fix fuzz crate lints and update deps

---

src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/parsing/snapshots/kcl_lib__parsing__parser__snapshot_tests__kw_function_call_in_pipe.snap

Extracted from #4826. Needed by #4893.

Add parsing keyword function calls inside pipelines

---

.github/workflows/e2e-tests.yml

Current set up prevents the tests from running once the PR goes from draft to ready, which was the intent. This is forcing ppl to commit again, which defeats the original purpose of saving compute time. Let's remove it for now.

Remove draft PR filter on e2e tests

---

packages/codemirror-lang-kcl/src/kcl.grammar
packages/codemirror-lang-kcl/test/key.txt

Replaces/closes #4915.
Authored by @mattmundell.
Add support for the new style init of object properties in `codemirror-lang-kcl`.
This was breaking folding in the editor.
Eg folding `startSketchOn` of [src/wasm-lib/kcl/tests/tan_arc_x_line/input.kcl](https://github.com/KittyCAD/modeling-app/blob/3c53babb5026a92faa95fd7786e1112ea5cedd9d/src/wasm-lib/kcl/tests/tan_arc_x_line/input.kcl#L7) before:
Vs after the PR:
`=` was added in /pull/4519.

CM KCL: Support `=` in record init

---

src/components/ToastTextToCad.tsx

When the user performs `prompt-to-edit` and hits `accept` the content will not be saved to disk if they refresh the page.
Force write to disk when the user presses `accept`

fix: writes to disk when the user accepts the prompt to edit

---

src/lang/wasm.ts
src/wasm-lib/kcl/src/execution/cache.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/src/wasm.rs

Add a new type `ExecOutcome` so that private internals of `ExecState` aren't leaked to TS. Replaces #4874.

Reduce the amount of data sent to TS and make new fields opt-in

---

.github/dependabot.yml

Make Dependabot bump all serde dependencies in a single PR.
See [Dependabot groups](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--).
Formatting was done in a separate commit.

Add dependabot group for all serde dependencies

---

src/wasm-lib/Cargo.lock
src/wasm-lib/kcl/Cargo.toml

https://github.com/Aleph-Alpha/ts-rs/releases/tag/v10.1.0
- Fix variants with empty struct https://github.com/Aleph-Alpha/ts-rs/pull/371
- Match `kittycad-modeling-cmds` v0.2.86 from https://github.com/KittyCAD/modeling-api/pull/708

Bump ts-rs from 10.0.0 to 10.1.0

---

packages/codemirror-lang-kcl/src/kcl.grammar
packages/codemirror-lang-kcl/test/range.txt

Replaces/closes #4957.
Authored by: @mattmundell 
In `codemirror-lang-kcl`, require at least one digit after the decimal point in `Number`.
The Lezer parser was failing to parse integer ranges like `[0..100]`, where the dots are right next the numbers. This was causing a slight highlighting problem for ranges.
And requiring digits looks to be consistent with fn `number` in [tokeniser.rs](https://github.com/KittyCAD/modeling-app/blob/97cef4d16c6315a702630d59dbf2671249838f23/src/wasm-lib/kcl/src/parsing/token/tokeniser.rs#L149).
Before the PR, the `..` is highlighted the same color as the number (you might have to zoom to notice):
Vs after the PR, the `..` is correctly black:
I'm guessing this was also causing the missing red underline on line 1 in the first image, due to some interplay …

CM KCL: numbers must have digits after dot

---

src/lang/abstractSyntaxTree.test.ts
src/wasm-lib/kcl/src/parsing/parser.rs

Authored by @TomPridham
Replaces/closes #4881.
closes #4871 
puts an error on the opening bracket of an array missing a closing bracket
the actual error message

fix: make error for missing a closing bracket clearer

---

e2e/playwright/fixtures/sceneFixture.ts
e2e/playwright/regression-tests.spec.ts
src/components/Stream.tsx

Adds a regression test to ensure that long-running KCL files show something building on screen and that the stream doesn't wait for execution to be completed to play the stream.
closes https://github.com/KittyCAD/modeling-app/issues/4966

Don't wait for `!isExecuting` to play the stream

---

e2e/playwright/projects.spec.ts

add a test for foreign characters in project name

---

.codespellrc
src/lib/machine-api.d.ts

Replaces/closes #4977.
Authored by @mattmundell.
Adjust excludes so that codespell runs cleanly in a messy tree.
Also fix a typo.
Before it was giving many warnings, which got in the way when the CI failed and I was trying to check it.

Make codespell smooth when run locally

---

packages/codemirror-lsp-client/src/plugin/lsp.ts

We should get rid of `startSketchAt` #4652, but until then, as a user, it's easy to mix them up. It's nice to be able to quickly see which is the bad one. Before, completions didn't look at whether the field was deprecated. Now it's both in the list and at the top of the documentation in bold.

Show deprecated indicator in CodeMirror autocomplete

---

src/routes/Onboarding/Export.tsx

Caught a stale name reference in the onboarding, and since the talk we were linking to also has an out-of-date name I figured why not use the format proposal itself as the link?

Update Katie's name reference and link in onboarding

---

e2e/playwright/point-click.spec.ts

Fix flaky playwright test 'Shell point-and-click sketch on face'

---

playwright.electron.config.ts

This allows playwright electron tests to run on linux arm64, for which Chrome doesn't exist. If anything, this should also bring us closer to what Electron packages.

Use Chromium instead of Chrome for Playwright Electron

---

flake.lock
src/wasm-lib/kcl-to-core/src/conn_mock_core.rs
src/wasm-lib/kcl/src/engine/conn.rs
src/wasm-lib/kcl/src/engine/conn_mock.rs
src/wasm-lib/kcl/src/engine/conn_wasm.rs
src/wasm-lib/kcl/src/engine/mod.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/test_server.rs
src/wasm-lib/tests/executor/cache.rs

I've added a `close` method on the EngineContext, EngineConnection, EngineManager.
This method sends close on the websocket then waits until it becomes inactive. This is really useful in tests in a single threaded context where there is only one engine available.
In rare circumstances a race occurs with the engine render thread shutting down. This currently causes all sorts of undefined behavior on the engine which I'm fixing upstream. However, the fix still just rejects new modeling websockets, so we need to listen to the engine w.r.t. closing our websocket connection and not just rely on cleanup via drop semantics.
I've tested this with an engine locally by inserting a false 5 second delay before sending close.
For internal reference:
https://github.com/KittyCAD/engine/pull/2978

Make the test executor a bit more patient

---

vitest.workspace.ts

How can devs run vitest in vscode with debug mode?
I installed the latest `vitest` extension published by `vitest`. The extension complained about multiple config files and then suggested a workspace file to be generated. I am committing the auto generated file which let me run the tests. 
- Install vitest from vitest
- Create a file called vitest.workspace.ts in the root of modelingapp (I created this file automatically when I pressed the button when it suggested this file to be created. Don't know if we need to change anything)
- Go to testing pane and click the refresh icon
- You can now run tests from the testing pane or the `*.test.ts` files.
- Some vitest files require localhost:3000 to serve `"GET /wasm_lib_bg.wasm" "node-fetch"`
- Open a terminal and run `yarn simpleserver:bg` in …

Developer workflow: added auto generated workspace file from vitest extension in vscode

---

.github/dependabot.yml

Our subpackages have fallen out of date.

Add packages to Dependabot updates

---

src/lang/std/artifactGraph.test.ts
src/lang/std/artifactGraph.ts
src/lib/promptToEdit.ts
src/lib/selections.ts

Part of #4860.
It doesn't make sense that a `Path` always has a sweep, for example. Code that uses the artifacts should be aware of the potential for a missing value and handle it.
The new `TODO`s in `artifactGraph.ts` should be impossible. If it ever does have an undefined value, it will preserve the current behavior of using empty string. All this code is going away soon, so I didn't bother to add a new error handling path.

Fix artifact types to be more accurate

---

.github/dependabot.yml

I needed to do this manually before in #4732, in particular `wasm-bindgen-futures`.

Upgrade all wasm-bindgen dependencies together

---

docs/kcl/index.md
docs/kcl/int.md
src/wasm-lib/kcl/src/execution/exec_ast.rs
src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/std/convert.rs

Two minor fixups:
- Use the std lib deprecation mechanism for the `int` function, rather than a hack in the parser
- Remove an epsilon from float to int conversion to make it match more recent float to int conversions

Minor bits and pieces

---

public/kcl-samples-manifest-fallback.json
src/components/CommandBar/CommandBar.tsx
src/components/CommandComboBox.tsx
src/hooks/useStateMachineCommands.ts
src/lib/commandBarConfigs/projectsCommandConfig.ts
src/lib/commandTypes.ts
src/lib/commandUtils.test.ts
src/lib/commandUtils.ts
src/lib/createMachineCommand.ts
src/machines/commandBarMachine.ts

Broken out from #4166. Commands have been registered and unregistered based on the actor's state in `useStateMachineCommands`, resulting in a lot of churn in commands. This makes it so that only the connection state flushes the registered commands, not every actor's state. 
Additionally, it sorts the commands in the command palette options input to surface modeling commands, suppress disabled commands, and otherwise alphabetize.

Make commands disable, not unregister, based on their machineActor

---

src/wasm-lib/derive-docs/src/lib.rs
src/wasm-lib/derive-docs/tests/args_with_lifetime.gen
src/wasm-lib/derive-docs/tests/args_with_refs.gen
src/wasm-lib/derive-docs/tests/array.gen
src/wasm-lib/derive-docs/tests/box.gen
src/wasm-lib/derive-docs/tests/doc_comment_with_code.gen
src/wasm-lib/derive-docs/tests/lineTo.gen
src/wasm-lib/derive-docs/tests/min.gen
src/wasm-lib/derive-docs/tests/option.gen
src/wasm-lib/derive-docs/tests/option_input_format.gen
src/wasm-lib/derive-docs/tests/return_vec_box_sketch.gen
src/wasm-lib/derive-docs/tests/return_vec_sketch.gen
src/wasm-lib/derive-docs/tests/show.gen
src/wasm-lib/derive-docs/tests/test_args_with_exec_state.gen
src/wasm-lib/kcl-test-server/src/lib.rs
src/wasm-lib/kcl-to-core/src/lib.rs
src/wasm-lib/kcl/src/errors.rs
src/wasm-lib/kcl/src/execution/kcl_value.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/lsp/kcl/mod.rs
src/wasm-lib/kcl/src/std/args.rs
src/wasm-lib/kcl/src/std/units.rs
src/wasm-lib/kcl/src/test_server.rs
src/wasm-lib/src/wasm.rs
src/wasm-lib/tests/executor/cache.rs
src/wasm-lib/tests/modify/main.rs

Per-file units (use per-file settings for conversion functions)

---

e2e/playwright/code-pane-and-errors.spec.ts
e2e/playwright/fixtures/cmdBarFixture.ts
e2e/playwright/fixtures/toolbarFixture.ts
e2e/playwright/projects.spec.ts
e2e/playwright/test-utils.ts
src/components/CommandBar/CommandArgOptionInput.tsx
src/components/CommandComboBox.tsx
src/components/ProjectsContextProvider.tsx
src/lib/desktopFS.test.ts
src/lib/desktopFS.ts
src/routes/Home.tsx

Closes #5083 by adding an E2E test and then adding a uniqueness check and generation to the "Create project" command.
In the future I'd like to do something more elegant than appending `-1` to the project name until it's unique, but I care more about fixing the current behavior.

Add uniqueness check to "Create project" command

---

src/wasm-lib/kcl/src/execution/annotations.rs
src/wasm-lib/kcl/src/execution/kcl_value.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/simulation_tests.rs
src/wasm-lib/kcl/tests/import_whole/artifact_commands.snap
src/wasm-lib/kcl/tests/import_whole/artifact_graph_flowchart.snap.md
src/wasm-lib/kcl/tests/import_whole/ast.snap
src/wasm-lib/kcl/tests/import_whole/exported_mod.kcl
src/wasm-lib/kcl/tests/import_whole/input.kcl
src/wasm-lib/kcl/tests/import_whole/ops.snap
src/wasm-lib/kcl/tests/import_whole/program_memory.snap

Call `set_scene_units` when rendering a submodule with different units. Seems to work in practice and as demonstrated by the command log for the test.

set scene units based on a module's default units

---

src/components/ModelingSidebar/ModelingPanes/KclEditorMenu.module.css

Fixes #5047
Only the ones that are buttons not links.

Remove extra margin on some code editor menu items

---

src/components/ModelingMachineProvider.tsx
src/editor/manager.ts
src/lib/selections.ts

closes #4859 
`lastSelectionEvent` is not properly set in one of the `set selection` workflows so when the KCL editor is mounted it will break.
In the `completeSelection` workflow which is the selection workflow when a constraint is applied I properly compute the new selection range for the AST mod. I pass this range to the `setLastSelectionEvent` which then highlights the code in codemirror.
If the range cannot be computed I select the bottom of the file by default so we can always have some selection event.
It would be nice to have a clearer workflow for selection throughout the system. We have artifact selections as well as editor selections and then multiple different selection visuals within each one. 
```
Selection
+ Entity
+ highlight
+ select
+ Code Mirror
+ Highlight range
+ …
```

Fix: Properly setting selection range when KCL editor is not mounted.

---

src/wasm-lib/kcl/src/execution/mod.rs

When you use a whole module, it gives this error.
```kcl
import 'robot-arm-base.kcl' as robotArmBase
robotArmBase
```
```
Executing module `robotArmBase` as part of an assembly did not produce a result
```
As far as I know, there's no way to produce a result from a whole module. So I think we can ignore this and return an empty KCL value.
Part of #4683.
[Slack](https://kittycadworkspace.slack.com/archives/C06L2RHP9SL/p1738002224480849)

Fix to not error when using imported whole modules

---

docs/kcl/import.md
src/wasm-lib/kcl/src/std/import.rs

Related to #5165.
Stdlib docs are displayed in the autocomplete tooltip in the editor, and we don't open links in a new window. The `import()` function is deprecated now in favor of `import` statements, so this probably doesn't matter too much.

fix: Remove link from code editor docs

---

.github/workflows/e2e-tests.yml

Our team is actively investigating a recent spike in flaky WebRTC connection behavior, which has impacted the web-only Playwright snapshot tests particularly hard. The bot squashes other GH Actions in it's wake, so I think we should turn it off so we can see the other E2E tests more clearly

Turn off snapshot commit bot

---

e2e/playwright/testing-samples-loading.spec.ts
src/lib/kclCommands.ts

Following https://github.com/KittyCAD/kcl-samples/pull/152
This will still be missing an update on the unit indicator in the bottom right corner, in a future PR.

Remove project.toml fetch during Open Sample

---

yarn.lock

https://github.com/expressjs/express/releases

Bump express from 4.21.0 to 4.21.2 for path-to-regexp fix

---

e2e/playwright/command-bar-tests.spec.ts
e2e/playwright/editor-tests.spec.ts
e2e/playwright/file-tree.spec.ts
e2e/playwright/fixtures/homePageFixture.ts
e2e/playwright/fixtures/toolbarFixture.ts
e2e/playwright/point-click.spec.ts
e2e/playwright/projects.spec.ts
e2e/playwright/sketch-tests.spec.ts
package.json
src/lang/std/engineConnection.ts

Fixes our snapshots seeing a blank canvas.
There was some sort of incorrect racing going on with ICE candidates not being completely gathered first before requesting the video track. Now we wait for a particular signal (`candidate === null`) before going further with the WebRTC process.
This also revealed a race in the engine which @iterion has a PR for
Note this PR also reveals that prod engine is not triggering browser's `icecandidatestatechange`s, and is suspicious of other mysteries going on. On a local engine, these events fire properly. We are lucky there is a second "signal" (noted above) that works here.

Wait for ICE gathering completion before requesting video track + create file e2e test fix

---

src/App.tsx

The error is caught, but the thumbnail code tries to run in the browser, making for a noisy console error in the (unsupported) browser version of the app. This makes that hook not run.

Don't run thumbnail hook in browser

---

src/lang/modifyAst/addEdgeTreatment.test.ts
src/lang/modifyAst/addEdgeTreatment.ts
src/lang/modifyAst/addShell.ts
src/machines/modelingMachine.ts

`addEdgeTreatment.ts` directly imported singletons (e.g. `kclManager`), creating a cycle with `KclSingleton.ts`.
Removed direct singleton imports and refactored functions to accept a dependency object (containing `kclManager`, `engineCommandManager`, `editorManager`, and `codeManager`). These dependencies are now injected from the higher-level module.
This change breaks the cyclic dependency.
Closes: #5239

Refactor Edge Treatment Module to Break Cyclic Dependency

---

src/lang/wasm.ts
src/wasm-lib/kcl/src/execution/artifact.rs

This also changes artifact graph errors to point to the KCL that the command originated from.

Fix artifact graph to survive when there's an execution error

---

.eslintrc
packages/codemirror-lsp-client/src/lib/utils.ts
packages/codemirror-lsp-client/src/plugin/util.ts
src/Toolbar.tsx
src/components/AstExplorer.tsx
src/components/ModelingSidebar/ModelingPanes/CodeEditor.tsx
src/editor/plugins/lsp/kcl/colors.ts
src/lang/modifyAst/addEdgeTreatment.ts
src/lang/queryAst.ts
src/lang/std/sketch.ts
src/lang/std/sketchcombos.ts
src/lang/util.ts
src/lib/settings/initialSettings.tsx
src/lib/utils.ts

See #3606 where I added a safer `isArray()`. This PR adds a lint to prevent use of the broken `Array.isArray()` in favor of this new one.
This revealed one type bug that I fixed. We're now explicit about the ImportStatement in `traverse()`.
In `src/components/AstExplorer.tsx`, I opted to use `as any` instead of fixing the entire module. But at least it's explicit now. I.e. it's now a bit noisier that the dangerous `any` is being introduced.

Fix to use more accurate types with custom isArray() and add lint

---

src/wasm-lib/kcl/Cargo.toml
src/wasm-lib/kcl/src/execution/cache.rs
src/wasm-lib/kcl/src/parsing/ast/digest.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/parsing/parser.rs

The symptoms observed were that changing only units in a file didn't change what was exported. This was discovered in #5212.

Fix to invalidate execution cache when top-level annotations change

---

e2e/playwright/text-to-cad-tests.spec.ts
public/kcl-samples-manifest-fallback.json

Too flaky and there's no need to have then run on all three OSes from a coverage perspective.

Skip text-to-cad playwright tests on windows

---

src/lang/KclSingleton.ts

Nothing ever uses this parameter. It always uses the default. We should delete it.
Related to #5166.

refactor: Remove dead code to update the artifact graph after mock execution

---

src/components/CommandComboBox.tsx

It leads to awkward UX like the one reported in #5007. Users can still go back between arguments using <kbd>Backspace</kbd> on an empty argument, but to close it they have to hit <kbd>Escape</kbd>, <kbd>Cmd+K</kbd>, or click the close button.

Don't close the command palette on backspace

---

src/wasm-lib/kcl/src/lib.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs

This is to match the other function names in #5212 and remove the unneeded `get_` prefix that isn't used [in Rust](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter).

refactor: Rename function to not have unneeded prefix

---

src/wasm-lib/justfile

I do the first step of creating the directory and KCL file all the time, and I have to hunt for the path. Then, for existing tests, when I modify the KCL, I need to rerun the accept tests in a specific order. I think this change will make things easier.

Split up creating a new simulation test and running it

---

src/wasm-lib/kcl/src/execution/annotations.rs
src/wasm-lib/kcl/src/execution/cache.rs
src/wasm-lib/kcl/src/execution/exec_ast.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/execution/state.rs
src/wasm-lib/kcl/src/parsing/ast/digest.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/parsing/snapshots/kcl_lib__parsing__parser__snapshot_tests__kw_function_decl_with_default_and_type.snap
src/wasm-lib/kcl/src/parsing/token/mod.rs
src/wasm-lib/kcl/src/unparser.rs
src/wasm-lib/kcl/tests/import_function_not_sketch/artifact_commands.snap

This is preparatory work for declaring std using KCL (extracted from #5147).
Numeric suffixes are now preserved in the AST, but we still don't actually have any effect. (But it means formatting the AST won't drop them, etc).

UoM types in AST, unnamed annotations, and syntax for importing from std

---

src/main.ts

Fixes #5325
The `--no-sandbox` extra arg passed by the default .desktop file is causing the argv[1] lookup to be the wrong one.

Fix deep links on Linux .desktop files

---

src/lang/KclSingleton.ts
src/lang/wasm.ts
src/lib/promptToEdit.ts
src/lib/textToCad.ts
src/lib/wasm_lib_wrapper.ts
src/wasm-lib/kcl/src/lib.rs
src/wasm-lib/src/wasm.rs

one thing to keep in mind, is we'd need to be sure to bump the `kcl/Cargo.toml` _before_ the ZMA release as opposed to after in order for this to work currently.

pass thru the kcl version

---

src/lang/KclSingleton.ts
src/lang/modifyAst.test.ts
src/lang/modifyAst.ts
src/lang/std/sketch.ts
src/wasm-lib/kcl/src/execution/annotations.rs
src/wasm-lib/kcl/src/execution/cache.rs
src/wasm-lib/kcl/src/execution/exec_ast.rs
src/wasm-lib/kcl/src/execution/import.rs
src/wasm-lib/kcl/src/execution/state.rs
src/wasm-lib/kcl/src/parsing/ast/digest.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/unparser.rs
src/wasm-lib/kcl/tests/import_cycle1/ast.snap
src/wasm-lib/kcl/tests/import_function_not_sketch/ast.snap
src/wasm-lib/kcl/tests/import_whole/ast.snap

This makes things a bit easier since we don't have to treat annotations as a kind of comment and also lets us have annotations on any node.

Remove annotations from non-code-meta and store them in nodes

---

packages/codemirror-lang-kcl/src/kcl.grammar
packages/codemirror-lang-kcl/test/annotation.txt

Authored by @mattmundell. Replaces/closes #5314.
In `codemirror-lang-kcl`, add support for annotations to the Lezer parser.
~I've done this the simple way by treating the annotation as a statement and allowing space, eg between the `@` and `setting` and `(`. If it really needs to parse the spacing correctly in future it might need to use Lezer's external tokenizer feature.~
~Note that the `!annotation` forces the parser to choose the `AnnotationList`, because at that point the `(` could also be the start of a statement.~
Prepares for adding highlights to annotations.
Related: /issues/5204.

CM KCL: add annotations

---

src/lang/modifyAst.ts
src/lang/std/sketch.ts
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/parsing/parser.rs
src/wasm-lib/kcl/src/parsing/snapshots/kcl_lib__parsing__parser__snapshot_tests__kw_function_call_multiline.snap
src/wasm-lib/kcl/src/parsing/snapshots/kcl_lib__parsing__parser__snapshot_tests__kw_function_call_multiline_with_comments.snap

Before, this would not parse:
```
line(
end = [44.09, 306.95],
// tag this for later
tag = $hello
)
```

KCL: Allow comments in CallExpressionKw

---

src/main.ts

This auto-hide behavior causes the bar to toggle visible and hidden when the user hits the <kbd>Alt</kbd> key, which can be quite often especially with Trackpad Friendly controls enabled.
Behavior in Nightly v25.2.18
https://github.com/user-attachments/assets/cbf6139d-afe0-4dfd-b876-cafc1007907e
New behavior from this branch
https://github.com/user-attachments/assets/225915d3-35ae-4cd9-aefa-b7a858d36ae1

Don't auto-hide menu bar on Windows and Linux

---

package.json

The current command uses the proper `copy` command but does not use `\`'s, so it fails on my Windows machine.
Previous output of `yarn isomorphic-copy-wasm`:
```Powershell
(copy src/wasm-lib/pkg/wasm_lib_bg.wasm public || cp src/wasm-lib/pkg/wasm_lib_bg.wasm public)
The syntax of the command is incorrect.
'cp' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```
Now:
```Powershell
yarn isomorphic-copy-wasm
yarn run v1.22.22
$ (copy src\wasm-lib\pkg\wasm_lib_bg.wasm public || cp src/wasm-lib/pkg/wasm_lib_bg.wasm public)
1 file(s) copied.
Done in 0.14s.
```

Fix isomorphic-copy to work on Windows

---

package.json

This reverts commit 18d87b99bd3926cd76a2802c167302a5e7f1f037.
These `\\` characters in this command cause our process for building the apps for release to choke, like [here](https://github.com/KittyCAD/modeling-app/actions/runs/13416752112/job/37479744226#step:5:27)

Revert "Fix isomorphic-copy to work on Windows (#5417)"

---

src/wasm-lib/kcl/Cargo.toml

Keeping this up to date would be nice for downstream repos like kcl-lsp. It always requires the latest version. We recently started making the patch version match between crates.

Fix kcl-lib derive-docs version

---

e2e/playwright/sketch-tests.spec.ts

Also adds a TODO with a link to https://github.com/KittyCAD/modeling-app/issues/5437 to track the underlying issue.
Current failing behavior with `600`ms timeout
https://github.com/user-attachments/assets/b067ad25-1614-4197-a7d4-86b868ae03af

Patch test with longer timeout

---

src/clientSideScene/ClientSideSceneComp.tsx
src/clientSideScene/sceneInfra.ts
tailwind.config.js

Closes #3946, which then closes #3974 since it was the only reason that issue was reopened.
Following @nadr0's good idea about using `tailwind.config.js` to set up named z-index layers that we can see all in one place in the app. There are still many places in the code base that use `z-<number>` classes from the default Tailwind config, so I left a TODO that we should enable more layers in that file, and replace all instances of numbered classes with named ones. That seemed beyond the scope of this fix.
It turns out that #3946 was actually fixed in #4816. This PR gets rid of the `zIndex: '99999999'` fix that @nadr0 had to implement, instead making the z-index of the CSS2DRenderer lower than the Overlays component.

Make z-index relation between sketch scene items explicit and colocated

---

e2e/playwright/projects.spec.ts

E2E tests pass when it really shouldn't. It fails if you manually test the step yourself.
CodeMirror does not always put the error into the DOM. The test assumes the error is in the DOM but that is not always true. CodeMirror lazy loads the text.
I fixed this by scrolling to the text to see that there is an error.
by the way this passes in main already but it passes for the wrong reason, this should pass again but be more robust.

fix: E2E test assumes codemirror error is present when it is lazy loaded

---

.gitignore
e2e/playwright/testing-settings.spec.ts
src/wasm-lib/kcl/src/execution/cache.rs
src/wasm-lib/kcl/src/execution/mod.rs

closes #5443
fixes https://github.com/KittyCAD/modeling-app/issues/5283
EDIT: yes it fixes both, sorry for putting blame on yall this was a place where the caching was not testing e2e and only unit :) I added a test

better testing for making sure we update the cache state on just settings changes

---

src/main.ts

Not sure if it fixes #3696 fully but is a low-hanging fruit towards that.
Alright this was a TYPO and fixing it already helps a lot. Tested this by building a numbered dev build locally on mac (not codesign) which fails as it should.

Show visible error when updater call fails

---

.github/ci-cd-scripts/playwright-electron.sh
.github/workflows/cargo-test.yml
.github/workflows/e2e-tests.yml

I hit a straight green first attempt three times on a row on this branch https://github.com/KittyCAD/modeling-app/compare/main...pierremtb/adhoc/e2e-external-retry
This is about retrying the whole workflow step with nick-fields/retry@v3.0.0 instead of rerunning playwright --last-failed in the script. And seems to give me much better results?? It's the first time that I brute force in one direction and I actually see tangible improvements.
Link to the three times:
https://github.com/KittyCAD/modeling-app/actions/runs/13474280984/job/37651492175
https://github.com/KittyCAD/modeling-app/actions/runs/13474388068/job/37651720678
https://github.com/KittyCAD/modeling-app/actions/runs/13474516441/job/37652011524

External retry of the playwright step instead of --last-failed

---

.github/workflows/build-apps.yml

I'm guilty of making a non-new mistake https://github.com/KittyCAD/modeling-app/actions/runs/13513410617
Went back to the double backslash at https://github.com/KittyCAD/modeling-app/pull/5335/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R98 and that got me on nightly yesterday.
I'm tempted to say that if we don't resolve this in a different way we're bound to repeat it. So my vote is it's time to cache out!

Get rid of failing cache on build-apps' setup-node

---

e2e/playwright/fixtures/fixtureSetup.ts

As discussed on Slack, commenting out the Object.assign call instead of reverting #5464.

Disable pw object.assign context

---

.github/workflows/build-apps.yml
package.json
scripts/copy-wasm.ps1

Reverts KittyCAD/modeling-app#5490 but fixes the copy without using escaped backslashes that were messing with `jq` since they might be invalid json.

Revert "Get rid of failing cache on build-apps' setup-node" and fix wasm copy on Windows

---

e2e/playwright/command-bar-tests.spec.ts

Add step to E2E test to verify `Backspace` doesn't dismiss command palette

---

src/components/CommandBar/CommandBarKclInput.module.css

Closes #4719.
Looks much better now I think, yeah?
https://github.com/user-attachments/assets/5f1aa958-3c9d-4446-a175-9991fa8d06aa

Fix overflow in KCL command palette input

---

src/wasm-lib/kcl/src/errors.rs
src/wasm-lib/kcl/src/execution/mod.rs
src/wasm-lib/kcl/src/execution/state.rs
src/wasm-lib/kcl/src/lib.rs
src/wasm-lib/kcl/src/lsp/kcl/mod.rs
src/wasm-lib/kcl/src/lsp/tests.rs
src/wasm-lib/kcl/src/parsing/ast/modify.rs
src/wasm-lib/kcl/src/parsing/ast/types/mod.rs
src/wasm-lib/kcl/src/simulation_tests.rs
src/wasm-lib/src/wasm.rs

@nrc let me know what you think of this change, basically before we could store all the source code files for modules but getting the root was hard since we parse and read the file out of step

better track the root source code

---

.github/workflows/e2e-tests.yml

I've seen this step fail sometimes and I'm not even sure we need it?
I'd say let's remove first if the tests keep to green 🔪

Remove unused Zoo CLI step in e2e-tests.yml

---

src/wasm-lib/kcl/src/std/chamfer.rs
src/wasm-lib/kcl/src/std/fillet.rs
src/wasm-lib/kcl/src/std/utils.rs

Extracted from #5460. Order of engine commands wasn't deterministic because we were sorting by UUID. Also, the error on duplicate tags wasn't working. This was caused by a recent PR:
- #5389
The PR that this was extracted from has a lot more tests that depend on this change.

Fix to have deterministic order of commands

---

src/wasm-lib/kcl/src/simulation_tests.rs
src/wasm-lib/kcl/tests/angled_line/program_memory.snap
src/wasm-lib/kcl/tests/artifact_graph_example_code1/program_memory.snap
src/wasm-lib/kcl/tests/artifact_graph_example_code_no_3d/program_memory.snap
src/wasm-lib/kcl/tests/circle_three_point/program_memory.snap
src/wasm-lib/kcl/tests/fillet-and-shell/program_memory.snap
src/wasm-lib/kcl/tests/flush_batch_on_end/program_memory.snap
src/wasm-lib/kcl/tests/i_shape/program_memory.snap
src/wasm-lib/kcl/tests/parametric/program_memory.snap
src/wasm-lib/kcl/tests/parametric_with_tan_arc/program_memory.snap
src/wasm-lib/kcl/tests/pentagon_fillet_sugar/program_memory.snap
src/wasm-lib/kcl/tests/poop_chute/program_memory.snap
src/wasm-lib/kcl/tests/sketch-on-chamfer-two-times-different-order/program_memory.snap
src/wasm-lib/kcl/tests/sketch-on-chamfer-two-times/program_memory.snap
src/wasm-lib/kcl/tests/sketch_on_face/program_memory.snap
src/wasm-lib/kcl/tests/sketch_on_face_after_fillets_referencing_face/program_memory.snap
src/wasm-lib/kcl/tests/ssi_pattern/program_memory.snap
src/wasm-lib/kcl/tests/tan_arc_x_line/program_memory.snap

Extracted from #5460. Floating point numbers were not being rounded thoroughly. The PR that this was extracted from has a lot more tests that were failing because of this.

test: Fix to round floating point numbers in test output

---

interface.d.ts
src/components/Settings/AllSettingsFields.tsx
src/main.ts
src/preload.ts

Closes #3886 by providing users with a way to manually check for app updates from the bottom of the settings.
(Edit: I had the wrong demo vid thanks @lf94)
https://github.com/user-attachments/assets/57072927-a0ff-40e5-a24a-74d191a75f7d

Add button in settings menu to manually check for updates

---

src/lib/settings/initialSettings.tsx

Closes #4463 by making this input sliders less eager to write to disk, which was gumming up the works. Now it updates the CSS variable to "preview" the change on input, and only triggers the permanent save on `mouseUp`, `pointerUp`, or keyUp`, when the user is done. Shoutout to @tmcw for [this helpful Observable notebook from back in the day](https://observablehq.com/@tmcw/inputs/2#slider); I owe you a tea.
https://github.com/user-attachments/assets/89e0e6db-47e6-4874-b5cb-5c2d546ca5e0

Only save the themeColor setting on end of input

---

rust/kcl-lib/Cargo.toml
rust/kcl-lib/src/execution/cache.rs
rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/execution/kcl_value.rs
rust/kcl-lib/src/execution/memory.rs
rust/kcl-lib/src/execution/mod.rs
rust/kcl-lib/src/execution/state.rs
rust/kcl-lib/src/lsp/kcl/mod.rs
rust/kcl-lib/src/std/args.rs

Factors out a `Stack` from `ProgramMemory` which encapsulates a call stack for a module. Multiple `Stack`s on different threads share a single `ProgramMemory` which means memory does not need to be reassembled after evaluating a module.

Make memory accessible from multiple threads/tasks

---

e2e/playwright/projects.spec.ts
src/components/ProjectCard/ProjectCard.tsx
src/components/ProjectCard/ProjectCardRenameForm.tsx
src/components/ProjectsContextProvider.tsx

Closes #4113 and adds to the project renaming E2E test

Bugfix: show proper error toast when user tries to rename project to conflicting name

---

src/lib/getKclSamplesManifest.ts
src/lib/kclCommands.ts

Fixes the last 2 E2E tests for #5460.

Fix the fetch logic for the KCL samples after vendoring

---

src/lib/coredump.ts

Fixes #5117 by just grabbing the `userData` off the group, and not trying to clone the whole class instance which errors.

Don't try to clone a THREE.js group in coredump

---

.github/workflows/e2e-tests.yml

Addresses https://github.com/KittyCAD/modeling-app/pull/5677#issuecomment-2706903363. Follow-up to #5460.
We compute the condition once, and then all steps use that. Since the job is still running, it reports the GitHub Check as success.
In the future, we can make the path detection and conditions as sophisticated as we want. Steps won't have to change.

ci: Fix e2e jobs to pass the status check even when they're not run

---

e2e/playwright/fixtures/toolbarFixture.ts
src/lib/routeLoaders.ts

Fixes #5625. #5142 regressed the project settings loading because it failed to fire off a new `load.project` XState event in the case where we were loading in the browser. It also may have had a bug with project settings loading on refresh from the file page, as we were not properly ensuring that the `settingsActor` was in the `idle` state before sending our `load.project` event regardless.

Fix project settings loading in browser

---

rust/kcl-lib/src/unparser.rs
src/lang/KclSingleton.ts
src/lang/codeManager.ts

There's a couple of weird bugs here, apologies in advance for rambling. The simplest one with the simplest fix is that numbers with a units suffix (e.g., `5ft`) were not being recast properly - it's a one line fix with a small change to test it (before the PR, that would be recast as `5ftft` which is a parse error).
On the frontend, that recast bug exposed another where if recasting produced code which in turn generated a parse error, then entering sketch mode would either fail, get into a weird state where sketching couldn't happen, or sometimes delete all the user's code(!). There was a couple of things going on here: if the UI generated code with an error or warning, then mock-executing that would try and report the error but because mock execution works over different code to that in …

Fix a recast bug and don't delete the user's code if parsing fails

---

.github/workflows/build-and-store-wasm.yml
.github/workflows/build-apps.yml
.github/workflows/e2e-tests.yml

This also migrates more uses of Rust toolchain installation actions to use the same one as in #5614.

ci: Fix e2e workflow to install rust toolchain when needed

---

.github/workflows/build-and-store-wasm.yml
.github/workflows/build-apps.yml
.github/workflows/cargo-check.yml
.github/workflows/cargo-clippy.yml
.github/workflows/cargo-fmt.yml
.github/workflows/cargo-test.yml
.github/workflows/e2e-tests.yml

This also makes it so that it doesn't swallow the error if the copy fails for some reason. Follow-up to #5728.

Fix toolchain file copy to work on all platforms

---

rust/Cargo.lock
rust/kcl-lib/Cargo.toml
rust/kcl-lib/e2e/executor/main.rs
rust/kcl-lib/src/std/args.rs

Previous error message:
"Expected a kcl_lib::execution::geometry::SolidSet but found Sketch"
New error message:
"Expected a SolidSet but found Sketch. You can convert a sketch (2D) into a Solid (3D) by calling a function like `extrude` or `revolve`"
Two improvements:
- Don't print the fully-qualified Rust name (e.g. kcl_lib::executor::Solid) instead use the last part of that (e.g. just Solid)
- Allow specific suggestions for combinations of got/want (e.g. "You can convert a sketch (2D) into a Solid (3D) by calling a function like `extrude` or `revolve`")
Closes #5616

KCL: Fix cryptic error in type mismatch

---

e2e/playwright/testing-constraints.spec.ts

Seen consistent failures of this test, example https://github.com/KittyCAD/modeling-app/actions/runs/13793844159/job/38580451541#step:27:3414
This PR changes the way we enter the sketch, through button clicks in the feature tree instead of stream coordinates.

Improve sketch constraint test

---

e2e/playwright/feature-tree-pane.spec.ts
src/components/CommandBar/CommandBarHeader.tsx
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/commandTypes.ts
src/machines/commandBarMachine.ts

As a workaround until we have time for https://github.com/KittyCAD/modeling-app/issues/5190, we will hide any selection type arguments from the command palette while the user is in an edit flow, so that they do not run the risk of selecting items that are in the scene but were generated after the operation being edited. This can be detected by the presence of a `nodeToEdit` in the command palettes arguments (which is also hidden).
This PR:
1. refactors the `hidden` argument config to be able to be a function that takes the current command palette context.
2. configures all the selection-based arguments for modeling commands we have edit flows for to be hidden if `nodeToEdit` is present
3. updates the existing E2E tests to expect the selection-based arguments to _not_ be present in edit …

Hide selection-type args from command palette while in an edit flow

---

rust/kcl-lib/e2e/executor/inputs/fillet_duplicate_tags.kcl
rust/kcl-lib/e2e/executor/main.rs
rust/kcl-lib/src/errors.rs
rust/kcl-lib/src/std/args.rs
rust/kcl-lib/src/std/chamfer.rs
rust/kcl-lib/src/std/fillet.rs
rust/kcl-lib/src/std/utils.rs

Fixes https://github.com/KittyCAD/modeling-app/issues/4307
Now if you try to fillet the same edge twice in a single fillet command, the error message is clearer, and the source range will highlight the specific edges in the array which are duplicated.
Same goes for chamfer.
Note: although the Rust KCL interpreter sends back an array of SourceRange for each KCL error, the frontend only puts the first one into CodeMirror diagnostics. We should fix that: https://github.com/KittyCAD/modeling-app/issues/5754

KCL: Fix cryptic error when using duplicate edges in fillet call

---

rust/Cargo.lock
rust/kcl-lib/src/parsing/parser.rs

Firstly, before the code "{x = 1, y = }" would give the dreaded "unexpected token" error.
Now it says "This property has a label, but no value. Put some value after the equals sign". And points to the = symbol with no matching right-hand side value. Yay!
Second fix: before, in the code `f(1, x=)`, the error complained that an unlabeled arg was not permitted there.
Now it says "This argument has a label, but no value. Put some value after the equals sign".
Closes #5647

KCL: Fix two cryptic error messages

---

.github/workflows/cargo-bench.yml

This reverts commit ec64daa01f2562e9ef6a99600050fcdd71d9aa53.
we dont have many credtis

change runner

---

.github/workflows/e2e-tests.yml
playwright.electron.config.ts

Based on recent tests this seems to work better:
- reduced flow workers from 8 per machine to 1 (so only one app)
- doubled the amount of shards from 4 to 8
- reduced the amount of auto step retries to 15 from 25
Unrelated to flow but useful with what we've seen lately: added auto step retries to snapshot tests that have gone flakey.

Only one playwright worker and less retries. Plus auto-retries on snapshots

---

.github/workflows/e2e-tests.yml

Since these are meant to ensure consistent behaviour of the upstream stack, there's little relevance in running these tests across all OSes.

Hourly e2e tests only on Ubuntu

---

e2e/playwright/secrets.ts

If the file exists but doesn't define the secrets, it should still use the environment variables. We want to move away from the file eventually.

Change playwright to always use env vars

---

Makefile

Before:
```
$ make dev
make: *** No rule to make target `public/wasm_lib_bg.wasm', needed by `dev'.  Stop.
```
After:
`make dev` starts the web app.

Fix the dev target dependency name

---

.github/workflows/e2e-tests.yml

See #5876 where this was failing to install things that weren't needed. Proof that this works will appear in #5893.

Fix e2e workflow when only kcl-samples changes

---

vite.renderer.config.ts

We need to keep both `vite-plugin-top-level-await` and the `es2022` build target for the renderer layer of electron as this was causing issues with `electron-forge start` that the team relies on for local development with convenient hot reload of all layers.
A better long term approach was started at #5881, removing the dependencies on electron-forge completely, but it wasn't successful in terms of functionality parity. More to come on that

Fix electron renderer topLevelAwait in electron-forge

---

.github/workflows/cargo-test.yml
e2e/playwright/snapshots/prompt-to-edit/prompt-to-edit-snapshot-tests-spec-ts--edit-with-ai-example-snapshots--change-colour.snap.json

When only changing kcl-samples, it should generate all the files and push them. You can see this failing in the `cargo-test` workflow of #5876.

Fix workflow to commit all generated kcl-samples files

---

rust/kcl-lib/src/engine/mod.rs
rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/execution/mod.rs
rust/kcl-lib/src/std/args.rs

One rare panic where an engine error persists to the next scene manifesting as an error in std::prelude, and one due to not enough arguments to some standard library functions.

Fix a couple of panics

---

.gitignore
Makefile

The goal here is to map out the relationships between the `package.json` scripts and the artifacts they produce.

Expand Makefile to run web and desktop apps

---

playwrightProcess.mjs

This is making it difficult to see common prefixes and query within messages in [this](https://app.axiom.co/kittycad-xx0p/dashboards/idQcOOMOsGMHFuZyqe) dashboard:

Strip ANSI control sequences to clean up Axiom dashboard

---

rust/kcl-lib/src/parsing/mod.rs
rust/kcl-lib/src/unparser.rs

If you had a KCL file with only comments, it would get formatted away to an empty file.
For #5808, parsing a file with only comments needs to have a non-empty result so that we don't blow away significant files when replacing the current buffer.

Fix so that only comments doesn't format to empty

---

src/Toolbar.tsx
src/components/ActionButtonDropdown.tsx
src/components/CommandBar/CommandBar.tsx
src/components/FileTree.tsx
src/components/ModelingSidebar/ModelingPane.tsx
src/components/ModelingSidebar/ModelingPanes/MemoryPane.tsx
src/components/ProjectCard/ProjectCard.tsx
src/components/ProjectCard/ProjectCardRenameForm.tsx
src/components/Tooltip.tsx
src/components/UserSidebarMenu.tsx
src/routes/Onboarding/index.tsx

They make things feel slow, so we should remove all of them and only add them back where they feel very critical. A good example of a tooltip "delay" we have that doesn't use this property directly is the more detailed version of the toolbar tooltips, which show essential info immediately and expand after lingering.
Reported as a polish point by @nickmccleery during our first "final appearance tweaks" meeting, and it took no time to do so I'm sneaking it in while I wait for CI elsewhere.
https://github.com/user-attachments/assets/03c894ae-2a8f-4045-8b56-c089cf28a827

Remove all tooltip delays throughout the app

---

.envrc
Makefile

As I continue to map out dependencies of all commands in the README, this adds an example target for running the end-to-end tests against the web app.

Codify dependencies to run web end-to-end tests

---

.github/workflows/update-e2e-branch.yml

The GitHub UI seems to only look at the commit SHA for status reporting, so even though the **E2E Tests** workflow runs on the `all-e2e` branch have a different run ID, it’s the same commit SHA as `main` so it overwrites the status indicator, making it look like `main` broken when it is not.

Prevent overwriting the commit status on main

---

src/components/CommandBar/CommandBarKclInput.tsx
src/lib/useCalculateKclExpression.ts

This is so that we can more reliably await for the calculation to be completed before advancing the command bar in Playwright E2E tests.
First showing the spinner artificially by making it appear indefinitely on calc errors, then showing the normal behavior. The spinner almost never appears long enough for people to see it, but Playwright can move faster than that.
https://github.com/user-attachments/assets/a35a9884-bbbe-447d-a3c8-496e1421364e

Add a loading state to CommandBarKclInput while calculating

---

.eslintrc
src/components/CommandBar/CommandBarHeader.tsx
src/components/ProjectCard/DeleteProjectDialog.tsx
src/components/Settings/AllKeybindingsFields.tsx
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/commandBarConfigs/projectsCommandConfig.ts
src/lib/types.ts
src/machines/modelingMachine.ts
src/machines/projectsMachine.ts

https://typescript-eslint.io/rules/no-empty-object-type/
The one place where I ignored the lint seems to be intertwined in a weird way. Anything I chose caused the `tsc` error to flip-flop.

Fix to not use cursed empty object type and add lint

---

.eslintrc
.github/workflows/static-analysis.yml
packages/codemirror-lsp-client/src/client/codec/demuxer.ts
src/clientSideScene/ClientSideSceneComp.tsx
src/clientSideScene/sceneInfra.ts
src/clientSideScene/segments.ts
src/components/ActionIcon.tsx
src/components/CommandBar/CommandBarHeader.tsx
src/components/FileTree.tsx
src/components/ModelingMachineProvider.tsx
src/env.ts
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/commandBarConfigs/projectsCommandConfig.ts
src/lib/constants.ts
src/lib/paths.ts
src/lib/selections.ts
src/lib/settings/initialSettings.tsx
src/lib/usePreviousVarMentions.ts
src/lib/varCompletionExtension.ts
src/machines/settingsMachine.ts

Add some more of the lints from the [`recommended-type-checked`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended-type-checked.ts) set.
- [`@typescript-eslint/no-duplicate-type-constituents`](https://typescript-eslint.io/rules/no-duplicate-type-constituents) caught a bug where we were using `CallExpression | CallExpression`. The latter should have been `CallExpressionKw`. I.e. the type didn't match the possible runtime values, so it was a bug waiting to happen.
- [`@typescript-eslint/no-unnecessary-type-assertion`](https://typescript-eslint.io/rules/no-unnecessary-type-assertion/) allowed us to remove many `as` assertions, making our code much safer as we make changes. As we've upgraded TypeScript, it's been able to infer …

Add more TS lints and fix types

---

e2e/playwright/point-click.spec.ts
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/operations.ts
src/lib/toolbar.ts

Fixes #5059 (meta issue!)
Taking the chance to add a little consistency edit by making length non-required for edge mode, since length is pretty pointless for edge mode if offset doesn't exist. If we want to provide control on the length it needs to be on both way. So I think it should remain part of the extra things for later—likely post v1—just like extrude until or offset from sketch would come in later.

Make Helix available in numbered releases

---

Makefile
e2e/playwright/lib/console-error-whitelist.ts
e2e/playwright/onboarding-tests.spec.ts

The browser context can't directly access variables from the test scope, so I think this test was passing for the wrong reason.

Fix 'originalCode' undefined in a test

---

e2e/playwright/lib/console-error-whitelist.ts

Been seeing this one a lot locally. Not always tho. But very frequently.
```
1) [chromium] › e2e/playwright/point-click.spec.ts:1347:7 › Point-and-click tests › Helix point-and-click on cylinder 
Error: expect(received).toEqual(expected) // deep equality
- Expected  - 1
+ Received  + 9
- Console error detected
+ An error was detected in the console: 
+  message:The "path" argument must be of type string. Received undefined 
+  name:Error 
+  stack:Error: The "path" argument must be of type string. Received undefined
+     at eoe (file:///Users/pierremtb/Documents/zoo/modeling-app/.vite/renderer/main_window/assets/index-BFZhA1Jp.js:56621:33)
+     at async roe (file:///Users/pierremtb/Documents/zoo/modeling-app/.vite/renderer/main_window/assets/index-BFZhA1Jp.js:56705:15)
+
+ …
```

Add path argument error to console error whitelist

---

rust/kcl-lib/src/parsing/ast/types/mod.rs

Fixes issue described in https://github.com/KittyCAD/modeling-app/pull/5808#issuecomment-2761836528.

Fix to preserve comments when changing file units

---

.github/workflows/e2e-tests.yml

No reason to keep such a stackup of env variables. I believe this is all that's needed.

Clean up env vars in e2e-tests.yml

---

rust/kcl-lib/src/std/fillet.rs
rust/kcl-lib/src/std/loft.rs
rust/kcl-lib/src/std/mod.rs
rust/kcl-lib/src/std/revolve.rs
rust/kcl-lib/src/std/sweep.rs

The default tolerance used in modeling commands is a `LengthUnit`, measured in the current scene units. So it doesn't make sense that it would be a larger number when using a larger unit. The fact that it's represented in a larger unit makes it larger. The current approach has led to unexpected failed fillets, like when using meters, which mapped to 10<sup>-3</sup>.
Ping: @nadr0 @lee-at-zoo-corp

Change default tolerance value to not depend on units

---

rust/Cargo.lock
rust/kcl-bumper/Cargo.toml
rust/kcl-derive-docs/Cargo.toml
rust/kcl-directory-test-macro/Cargo.toml
rust/kcl-language-server-release/Cargo.toml
rust/kcl-language-server/Cargo.toml
rust/kcl-lib/Cargo.toml
rust/kcl-python-bindings/Cargo.toml
rust/kcl-test-server/Cargo.toml
rust/kcl-to-core/Cargo.toml
rust/kcl-wasm-lib/Cargo.toml

v57
[Release process](https://github.com/KittyCAD/modeling-app/blob/0583eb07d56d414a1fe4948cc6ac60098ab8f9fa/rust/README.md)

Bump kcl versions

---

.eslintrc
e2e/playwright/fixtures/fixtureSetup.ts
packages/codemirror-lsp-client/src/client/codec/index.ts
src/clientSideScene/sceneInfra.ts
src/components/FileMachineProvider.tsx
src/lang/std/engineConnection.ts
src/lang/wasm.ts
src/preload.ts

Follow-up to #6037. This is the last of the easy lints in `recommended-type-checked`. There are more that are useful, but they require lots of fixes.

Add more TS lints

---

scripts/semantic-release.sh

`gh` has to be installed and requires an auth flow with GitHub. Could we do the same thing with local `git` commands?
To test this:
```
unset GH_TOKEN
./scripts/semantic-release.sh
```

Display the next version using native git commands

---

e2e/playwright/fixtures/fixtureSetup.ts

We are spamming `page.reload` in electron playwright. The code created a massive function composition that would do `page.reload` then `page.reload` etc...
I check if electron exists, if electron exists do not rebind the function.
```
Iteration 90: 4006 + 90 = 4096, total: 125670
```
If it was on the 90th test in the suite, it would literally refresh the electron instance `4096` before the test would actually run.
Then the 91st test in the suite would refresh `4187` times before it would run.
Based on the number of tests that would run in a suite here is the size of the latest shard on main
These are the number of page refreshes that would happen.
```
Iteration 1: 1 + 1 = 2, total: 2
Iteration 2: 2 + 2 = 4, total: 6
Iteration 3: 4 + 3 = 7, total: 13
Iteration 4: 7 + 4 = 11, total: 24 …
```

Fix: function composition during playwright setup created a massive page.reload loop

---

e2e/playwright/desktop-export.spec.ts

This test is failing quite regularly on main, but now passed for me with:
```
yarn test:playwright:electron --grep="export works on the first try" --repeat-each=20
```

Use scene fixture to make test more reliable on macOS

---

src/components/Settings/AllSettingsFields.tsx

In certain cases this would cause an infinite loop in the web version of the app. We should eliminate all uses of this "fire and listen with a useEffect" antipattern in the code base, it was a mistake I introduced. This uses the XState `waitFor` function to wait **only once** for the transition to complete, with some error handling in case it fails.
Fixes #5737 but cc @jacebrowning this is something I wish I could do web+desktop testing for.

[fix] Get rid of risky useEffect in restart onboarding flow

---

Makefile
playwright.config.ts
playwright.electron.config.ts

With the fix from https://github.com/KittyCAD/modeling-app/pull/6137, we might be able to speed up CI by running more workers. I'm still defaulting to one worker locally to avoid lots of windows getting in our way.

Use all available CPUs to run tests on CI

---

.github/workflows/e2e-tests.yml

With the recent testing improvements, _good_ shard runs now take less than 15 minutes and retry no more than 5 times. I think we can now lower the limits so that we don't waste time retrying legitimate test failures and provide a shorter feedback cycle.

Shorten feedback cycle for legitimate failures

---

e2e/playwright/desktop-export.spec.ts

The main source of flakiness in the `export works on the first try` test seems to be the export button in the panel not always being available right after the scene execution finishes. Adding a short delay ensures that clicking the button actually opens up the export menu.   
---
```
yarn test:playwright:electron:local --grep="export works on the first try" --repeat-each=10
```

Wait for export button to make test more reliable

---

e2e/playwright/native-file-menu.spec.ts

Skipping the one file menu test allows us to get all green on e2e, see https://github.com/KittyCAD/modeling-app/actions/runs/14285746258/job/40041141267

Skip one native menu test to make stream idle green

---

rust/kcl-lib/src/engine/mod.rs

found this while @paultag  and i were doing parallel modules, easy to just put on main!

take things off the batch in a more safe way

---

public/kcl-samples/gear/main.kcl
rust/kcl-derive-docs/src/lib.rs
rust/kcl-lib/src/docs/gen_std_tests.rs
rust/kcl-lib/src/execution/geometry.rs
rust/kcl-lib/src/execution/mod.rs
rust/kcl-lib/src/execution/state.rs
rust/kcl-lib/src/execution/types.rs
rust/kcl-lib/src/std/args.rs
rust/kcl-lib/src/std/math.rs
rust/kcl-lib/src/std/segment.rs
rust/kcl-lib/src/std/shapes.rs
rust/kcl-lib/src/std/sketch.rs
rust/kcl-lib/src/std/sweep.rs
rust/kcl-lib/src/std/units.rs
rust/kcl-lib/tests/kcl_samples/car-wheel-assembly/ops.snap
rust/kcl-lib/tests/kcl_samples/car-wheel-assembly/program_memory.snap
rust/kcl-lib/tests/kcl_samples/dodecahedron/program_memory.snap
rust/kcl-lib/tests/kcl_samples/gear/ast.snap
rust/kcl-lib/tests/kcl_samples/gear/program_memory.snap
rust/kcl-lib/tests/kcl_samples/i-beam/ops.snap
rust/kcl-lib/tests/kcl_samples/i-beam/program_memory.snap
rust/kcl-lib/tests/kcl_samples/router-template-cross-bar/program_memory.snap
rust/kcl-lib/tests/kcl_samples/router-template-slate/program_memory.snap

More carrying around numeric types rather than just using plain f64s. This is almost all of them, but there are a few left which depend on in-flight PRs. No user-facing changes. I also removed a few more deserialize derives.

More propagation of numeric types

---

.github/ci-cd-scripts/start-vector-macos.sh
.github/ci-cd-scripts/start-vector-ubuntu.sh
.github/workflows/cargo-test.yml
.github/workflows/e2e-tests.yml
.github/workflows/vector.toml

Install and start Vector on macOS CI runners

---

e2e/playwright/various.spec.ts
src/components/DownloadAppBanner.tsx
src/hooks/useCreateFileLinkQueryWatcher.ts

Fixes #6172. We don't have a way to run E2E tests in the browser right now so I left a note for myself to have one after we implement one. cc @jacebrowning there is a `fixme` that I added and I can write that test now and verify it locally if you'd like, and then just mark it as fixme for CI.

Fix unclickable state while opening share link in browser

---

src/components/ModelingSidebar/ModelingSidebar.tsx

I'm not sure if there's an issue for this but we've talked about how the "Share link" functionality is too buried in the hard-to-find project menu. This adds it to the "actions" section of the left sidebar. [I made a "link-with-right-arrow" icon in Figma](https://www.figma.com/design/5UUPOawPLEs3D0Gptf42vy/Designs?node-id=543-1464&t=M3RApEzU7kSfl2ln-11) but decided to just use the link icon we already have in there, since it's a cleaner shape. Let me know if you think I should use that one instead.
This is a part of a flurry of last minute pre-1.0 appearance tweaks to the app.

Add a sidebar action to create a share link

---

.github/workflows/build-apps.yml

Reported on Slack https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1744318449912839
Follow-up to #5974

Fix URL encoded names after rename to Zoo Design Studio

---

rust/Cargo.lock
rust/kcl-bumper/Cargo.toml
rust/kcl-derive-docs/Cargo.toml
rust/kcl-directory-test-macro/Cargo.toml
rust/kcl-language-server-release/Cargo.toml
rust/kcl-language-server/Cargo.toml
rust/kcl-lib/Cargo.toml
rust/kcl-python-bindings/Cargo.toml
rust/kcl-test-server/Cargo.toml
rust/kcl-to-core/Cargo.toml
rust/kcl-wasm-lib/Cargo.toml

getting a lib for @r-barton  to start messing with

bump kcl friends

---

src/components/CommandBar/CommandBar.tsx

The connection can't be bad if there is none yet `:galaxy-brain:`.
But seriously this behavior regressed share links because we would bail from the command palette because the connection wasn't healthy. This behavior was introduced in #5312 and not fixed by changes in #6265, only caught during smoke testing in #6283 luckily.

Don't bail command palette if there's no engineConnection

---

e2e/playwright/text-to-cad-tests.spec.ts

` await expect(page.locator('.cm-content')).toContainText(`const`)` was there as a way of asserting "there's some code in the editor right?"
But we haven't used the const keyword in ages, so maybe text-to-cad has kept using it all this time??
It's possible as the cost keyword was a lint warning, not an error.
Relevant slack thread:
https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1744585241148889

fix text-to-CAD test bug

---

e2e/playwright/lib/api-reporter.ts

This will let me identify tests that are expected to fail (e.g. `test.fail()`).

Include test annotations for analysis

---

e2e/playwright/point-click.spec.ts

The engine fixed the start angle for helices, but our e2e test has a pixel check so it broke. I made the test change the `startAngle` by `-90` rather than try to hunt around for a new working pixel value.

Update helix e2e test to account for 90deg engine change

---

rust/kcl-lib/src/parsing/parser.rs

Screenshot:
Note that
1. The error message makes sense
2. The error is on a reasonable part of the source code
3. The error doesn't prevent other kinds of parse errors (such as `1 w 3`) being picked up later
Thanks for noticing this one Frank!

KCL: Error when user sets a keyword arg multiple times

---

rust/Cargo.lock
rust/kcl-lib/Cargo.toml

Cargo decided to downgrade `windows-sys` for some reason.

Fix insta version in Cargo.toml to match lock file

---

.github/workflows/cargo-bench.yml
rust/kcl-lib/Cargo.toml
rust/kcl-lib/benches/benchmark_kcl_samples.rs

- the execution benchmarks were always failing due to websockets closing and we had to use walltime which sucks
- at least now we will good metrics for parse without walltime and in a nice vm to make sure data is good, walltime couldnt guarantee that
- you can run the execution benchmarks w the feature flag `benchmark-execution`
- this also allows us to require benchmarks to pass for ci, which means people cant make parsing significantly slower

put execution benchmarks behind flag

---

e2e/playwright/sketch-tests.spec.ts

The pixel color checks are only used for waiting. The tests check for the expected code so that should be sufficient.
--- 
```
npm run test:playwright:electron -- --grep="manual edits during sketch mode" --repeat-each=10
```
Before: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/461?branch=main
After: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/461?branch=remove-pixel-checks

Remove pixel color checks

---

src/components/ModelingMachineProvider.tsx
src/components/ToastUnsupportedSelection.tsx
src/lib/selections.ts

Closes #4866 (a P0 bug)
And opens a much lower priority one #6368 (which is a public facing issue that we can link to from within the app)
This change, 
- Updates the selection logic so we don't clear a users selections, even if they select nothing when they are holding shift (a single mis click could clear they 30 item selection :( )
- Changes logic in `getEventForSelectWithPoint` so that when we receive an entity we don't recognise from the engine (i.e. not in the artifactGrahp) we return an empty `singleCodeCursor` event which allow it to plug it with there rest of the selection logic (holding shift or not logic)
- show a toast message to the user in this case linking them to #6368 
- No tests because
https://github.com/user-attachments/assets/28f2e5d4-779d-48d9-bcfb-1b3d16f1afb8

add toast for selections we don't recognise

---

src/clientSideScene/sceneEntities.ts
src/components/ModelingMachineProvider.tsx
src/machines/modelingMachine.ts

Continues #6346 (this PR put the tear down inside of setupSketch and the render pause)
And I think related to https://github.com/KittyCAD/modeling-app/issues/4932 as it helps with perceived performance/snappyness
The TLDR of this is that tear down is handled in `sceneEntities.setupSketch` so it does not need to be done anywhere else just about, all these cases caused the flash by tearing down the old scene too soon. There is still an action that does the teardown and this is when exiting sketch, want to make sure 3js get's cleaned up.
No tests on this, because it would be extremely difficult to test in a way which is no the flakiest test in our suiete, plus if there's a regress in the flashes, it won't block users.

fix sketch flash part 2

---

.github/workflows/e2e-tests.yml
e2e/playwright/point-click.spec.ts
e2e/playwright/prompt-to-edit-snapshot-tests.spec.ts
e2e/playwright/snapshot-tests.spec.ts

Around the timing of #6342 snapshots started failing consistently

Add fixmes to failing e2e tests

---

.github/ci-cd-scripts/playwright-electron.sh
e2e/playwright/lib/api-reporter.ts
e2e/playwright/testing-settings.spec.ts

This updates the reporter to consult the TAB API to determine if a test failure should actually block CI.

Use TAB API to determine when merges are blocked

---

.github/workflows/e2e-tests.yml

Instead, I'm going to silence the individual bad tests from the TAB API, which was enabled by https://github.com/KittyCAD/modeling-app/pull/6405.

Allow snapshot tests to report status

---

e2e/playwright/prompt-to-edit.spec.ts

I think these still need work, but I'd like to enable/disable them programmatically based on the status of Text-to-CAD rather than directly in our test code.

Restore tests that use Text-to-CAD

---

.github/workflows/e2e-tests.yml

8-cores seems to result in fewer instances of these:
> Test timeout of 120000ms exceeded while setting up "tronApp".

Try running with 8 macOS cores again

---

rust/kcl-lib/src/parsing/parser.rs
rust/kcl-lib/src/parsing/snapshots/kcl_lib__parsing__parser__snapshot_tests__kw_function_in_binary_op.snap

Closes https://github.com/KittyCAD/modeling-app/issues/4992

KCL bugfix: CallExpressionKw was not usable as math operand

---

docs/kcl/getNextAdjacentEdge.md
docs/kcl/getOppositeEdge.md
docs/kcl/getPreviousAdjacentEdge.md
rust/kcl-lib/src/execution/types.rs
rust/kcl-lib/src/std/args.rs
rust/kcl-lib/src/std/edge.rs
src/lang/modifyAst/addEdgeTreatment.ts
src/lang/std/sketch.ts

This isn't a breaking change since these functions only accept one unlabeled arg.

Change getOppositeEdge, getNextAdjacentEdge, and getPreviousAdjacentEdge to keyword args

---

e2e/playwright/desktop-export.spec.ts
e2e/playwright/native-file-menu.spec.ts
e2e/playwright/projects.spec.ts
e2e/playwright/test-network-and-connection-issues.spec.ts
e2e/playwright/testing-settings.spec.ts
package.json

The only capabilities we'd expect to vary across platforms are: file menus, the file system, and networking.
---
We should only see a subset of tests run on macOS: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/results?branch=opt-in-macos&show=all

Opt-in tests that cover macOS-specific capabilities

---

.github/workflows/e2e-tests.yml

We're now running a tiny fraction of tests on macOS and Windows so I see no reason to run them every hour and simplify the CI logic.

Test all platforms hourly

---

e2e/playwright/file-tree.spec.ts

It seems more time is needed before clicking the object.
With 2seconds I'm getting 10/10 passes locally instead of 4-7/10.

Stabilize test by allowing more time before clicking object

---

.github/workflows/e2e-tests.yml

After https://github.com/KittyCAD/modeling-app/pull/6492, we're now running more tests on Linux. Increasing shards gets the longest one down from ~20 minutes to ~12 minutes.

Adjust sharding to account for more tests being run

---

rust/justfile

The function was renamed in #6488.

Fix just command to match test function rename

---

src/components/Providers/SystemIOProviderDesktop.tsx
src/machines/systemIO/systemIOMachine.ts
src/machines/systemIO/utils.ts

When you delete a project externally or internally it would refresh the home page multiple times and flash. It is really annoying.
- Added a deleteProject set last requested value to see what was the last requested project to be deleted
- When processing file deletion or project deletion see if the project was asked to be deleted and if it was successful
- If the conditions are met it won't trigger the file system watcher to reload off disk since it caught the fact that the application deleted the project. 
- When deleting a project in the system `reading projects` should be called exactly one in the system. 
- We should not have visual flickers when refreshing the home page after project deletion.

[bug]: Chokidar + reading projects spams multiple times

---

e2e/playwright/file-tree.spec.ts
e2e/playwright/named-views.spec.ts
e2e/playwright/regression-tests.spec.ts
e2e/playwright/testing-samples-loading.spec.ts
e2e/playwright/testing-settings.spec.ts
e2e/playwright/various.spec.ts

We're now tagging tests that cover platform-dependent functionality with `@macos` and/or `@windows` so these runtime `test.skip()` calls are no longer necessary. We'll also want to use `test.fail()` for expected failures.

Remove skips to align with new way of opting-in tests

---

.github/workflows/e2e-tests.yml

This makes it easier to adjust parallelization without having to disable all required branch checks.
The same naming convention was used in https://github.com/KittyCAD/modeling-app/pull/6574.

Name shards consistently

---

rust/kcl-lib/std/prelude.kcl

Fix to not double import math in the prelude

---

rust/kcl-lib/src/execution/artifact.rs
rust/kcl-lib/src/lib.rs
rust/kcl-lib/src/parsing/ast/types/mod.rs
rust/kcl-lib/src/parsing/ast/types/path.rs
rust/kcl-lib/src/source_range.rs
rust/kcl-lib/tests/misc/cube.kcl
rust/kcl-wasm-lib/src/wasm.rs
src/lang/queryAstNodePathUtils.ts
src/lang/wasm.test.ts
src/lang/wasm.ts
src/lib/rustContext.ts
src/lib/wasm_lib_wrapper.ts

Resolves #6231.
Since this is cached, this should make PathToNode computation correct even when code is formatted, whitespace changes, and source ranges are different.

Fix to cache correct PathToNode in artifact graph

---

src/lib/toolbar.ts

Removed clashing hotkey on center rectangle, seems less common than corner rectangle. Happy to be chalenged. Fixes #6634

Same hotkey for center rect and center circle

---

src/components/Settings/AllSettingsFields.tsx

Oversight on my part while refactoring the onboarding system in #6564. The new centralized `acceptOnboarding` workflow constructs a relative path, so we have to get out of the settings before invoking it.

Fix resetting onboarding from settings in web after #6564

---

package-lock.json
src/lib/operations.ts

This should have been done with #6382.
The `package-lock.json` change is unrelated. Just needed to get committed.
Before
After

Fix subtract2d icon in the Feature Tree

---

src/lib/desktop.ts

On macOS and Windows only. Linux was fine since it used a different var (which isn't great but one thing at a time).
Fixes #6655
Did some due diligence locally, checking where the token.txt file was written on both regular (release) and `files:flip-to-nightly` to mimic nightly behavior. `~/Library/Application\ Support/dev.zoo.modeling-app/token.txt` and `~/Library/Application\ Support/dev.zoo.modeling-app-nightly/token.txt` as expected on macOS

Fix app settings location not changing betwen nightly and release

---

src/components/ModelingSidebar/ModelingPanes/FeatureTreePane.tsx

It's weird to not have them consistent with the code, this at least bring back a connection between both, but is trying to be fairly subtle.

Put XY back into default plane feature tree

---

src/components/ModelingSidebar/ModelingPanes/FeatureTreePane.tsx

Align to baseline and no min width.
Before:
After:

Small touch up to default planes suffix

---

.env.development
CONTRIBUTING.md
Makefile
rust/justfile

`just test` should, well, _just work_ by installing our chosen test runner automatically.
I also removed a section of `CONTRIBUTING.md` that was already stale and I plan to revisit.
Contributes to #4012

Make 'npm run test:rust' work out-of-the-box

---

src/App.tsx
src/components/EngineStream.tsx
src/lib/screenshot.ts

closes https://github.com/KittyCAD/modeling-app/issues/6645
`thumbnail.png` was not being created when it looks like it should have. `useEngineCommands` would not set all of the engine commands if you created a project from text to cad workflow.
After the engine gets connection, the KCL is done executing, and we set the camera we will now take a screenshot.
- Home page text to cad -> new project -> :heavy_check_mark: 
- Home page -> create blank project -> :heavy_check_mark: 
- Home page -> create from sample -> :heavy_check_mark: 
- Home page -> opening a prexesiting project -> :heavy_check_mark:

Fix: thumbnail.png would not be created in a few scenarios, the commandType wasn't populated in some workflows.

---

docs/kcl-std/functions/std-helix.md
docs/kcl-std/functions/std-math-acos.md
docs/kcl-std/functions/std-math-asin.md
docs/kcl-std/functions/std-math-atan.md
docs/kcl-std/functions/std-math-atan2.md
docs/kcl-std/functions/std-math-cos.md
docs/kcl-std/functions/std-math-log.md
docs/kcl-std/functions/std-math-polar.md
docs/kcl-std/functions/std-math-pow.md
docs/kcl-std/functions/std-math-sin.md
docs/kcl-std/functions/std-math-tan.md
docs/kcl-std/functions/std-offsetPlane.md
docs/kcl-std/functions/std-sketch-circle.md
docs/kcl-std/functions/std-sketch-revolve.md
docs/kcl-std/functions/std-solid-chamfer.md
docs/kcl-std/functions/std-solid-fillet.md
docs/kcl-std/functions/std-solid-hollow.md
docs/kcl-std/functions/std-solid-shell.md
docs/kcl-std/functions/std-units-toCentimeters.md
docs/kcl-std/functions/std-units-toDegrees.md
docs/kcl-std/functions/std-units-toFeet.md
docs/kcl-std/functions/std-units-toInches.md
docs/kcl-std/functions/std-units-toMeters.md
docs/kcl-std/functions/std-units-toMillimeters.md
docs/kcl-std/functions/std-units-toRadians.md
docs/kcl-std/functions/std-units-toYards.md
docs/kcl-std/types/std-types-number.md
rust/kcl-lib/src/docs/gen_std_tests.rs
rust/kcl-lib/src/docs/mod.rs

Hack the checks for numbers so that we ignore the units for looking them up (for docs only)

Docs: Links and desciptions for number types

---

rust/Cargo.lock
rust/kcl-bumper/Cargo.toml
rust/kcl-derive-docs/Cargo.toml
rust/kcl-directory-test-macro/Cargo.toml
rust/kcl-language-server-release/Cargo.toml
rust/kcl-language-server/Cargo.toml
rust/kcl-lib/Cargo.toml
rust/kcl-python-bindings/Cargo.toml
rust/kcl-test-server/Cargo.toml
rust/kcl-to-core/Cargo.toml
rust/kcl-wasm-lib/Cargo.toml

Breaking changes:
- Fully removed positional arguments from function calls. Keyword arguments are now the only way to call a function.
Added:
- Warn on usage of the unknown numeric suffix (#6690)
Fixed:
- Fix units bug with involuteCircular (#6711)
- Importing 3D files on Windows (#6697)

Release KCL 67

---

src/components/CommandBar/CommandBarHeader.tsx

Splitting out some work I had in #6254 that wasn't directly related to onboarding into its own tiny PR.
Before:
After:

Truncate "text" arg value summaries by default

---

src/components/EngineStream.tsx

Fixes #6472. Just a missing setting moved in #5312, which wasn't caught because testing that the orbit maneuver is actually performing a "trackball-like" movement is nonexistent. I don't know how to test that reliably, but typing this object provides the red squiggles to reveal the missing property.

Fix trackball camera by weaving through EngineStream

---

e2e/playwright/sketch-tests.spec.ts
src/machines/modelingMachine.ts

Fixes #6686 
Moves the Cancel transition from Line up one level into Sketch.
Prior to this, only the Line tool cleaned up the empty draft sketch when exiting sketch mode, which caused double click to not work when Line was unequipped, or if any other tool was equipped.

#6686 Fix Unable to double click to edit sketch with specific set of actions

---

src/lib/commandBarConfigs/modelingCommandConfig.ts

Closes: #6770
since [fillet revisit](https://github.com/KittyCAD/engine/issues/1591), this warning message is no longer needed
before:

Removes "fillets cannot touch" warning message

---

rust/justfile

This is used by CI, so we need to make it good.
From `cargo check --help`:

ci: Fix just lint to check all targets

---

rust/kcl-lib/src/execution/kcl_value.rs
rust/kcl-lib/src/execution/mod.rs

Until we remove `MixedArray`, this should make it easier to debug error messages. We've received reports in the past where the message said something like "expected array but found array". This change will at least make it clear that one of them is a `MixedArray`.
If #6748 gets merged, might need to fix new error messages.

Change display of mixed array to be clear what it is

---

e2e/playwright/share-link.spec.ts
src/components/OpenInDesktopAppHandler.tsx

Won't be the solution for #6200 but may downgrade its priority from P0 to P1.
Added non-CI web tests:
```
npm run chrome:test -- -g "Open in desktop app" --headed
```

Error on "Open in desktop" click if URL is too long on Windows

---

src/components/ErrorPage.tsx

Whenever users screenshot the page it only shows an error message that has no context. We actually console log the error but the user is not expected to open the console to see the error
Just show the entire stack trace to see if that can help us on the off chance they don't give us more information.
This is to help debug future bug reports, asking someone "open your console", "press this button to copy the error message" is not seamless enough. 
Here are two tickets that the stack trace would have been useful but we do not have them
- https://github.com/KittyCAD/modeling-app/issues/6302
- https://github.com/KittyCAD/modeling-app/issues/6660
Updated GH link as well

[Fix]: Always show stack trace on the page if an Error shows up

---

rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/parsing/ast/digest.rs
rust/kcl-lib/src/parsing/ast/types/mod.rs
rust/kcl-lib/src/parsing/parser.rs
rust/kcl-lib/src/std/args.rs
rust/kcl-lib/src/std/array.rs
rust/kcl-lib/src/std/patterns.rs
rust/kcl-lib/src/unparser.rs
src/lang/modifyAst.ts
src/lang/modifyAst/addEdgeTreatment.ts
src/lang/modifyAst/tagManagement.ts
src/lang/std/sketch.ts
src/lang/std/sketchcombos.ts
src/lang/util.ts
src/lib/kclHelpers.ts
src/lib/utils.ts

This makes parsing a fair bit more generous and catches those errors later when type checking the KW args, which allows us to suggest the missing args.

Suggest a list of possible arg labels when an argument is unlabelled

---

package-lock.json

Tested on windows and macos. This field has been toggling back and forth.

Result of npm prune

---

rust/kcl-lib/e2e/executor/main.rs
rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/std/args.rs

Fixes #6613 
Extracted from #6644 to just fix the source range without touching the kwarg shorthand (left for post 1.0).

Source range for pipe value used as unlabelled arg

---

docs/kcl-lang/numeric.md
rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/execution/types.rs
rust/kcl-lib/src/std/math.rs

- Treat the type `number` as `Any` rather than `Default` numbers. I think this makes sense because we probably only want to use the default number type if there is no type at all, but still wish I wasn't doing this the day before launch! It makes me feel a bit better that I had been assuming this was how things worked, but still.
- Give an error message trying to take the sqrt of a negative number rather than letting the engine choke on it.

Some improvements to math::sqrt

---

rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/execution/kcl_value.rs
rust/kcl-lib/src/simulation_tests.rs
rust/kcl-lib/tests/array_range_expr/program_memory.snap
rust/kcl-lib/tests/array_range_mismatch_units/artifact_commands.snap
rust/kcl-lib/tests/array_range_mismatch_units/artifact_graph_flowchart.snap
rust/kcl-lib/tests/array_range_mismatch_units/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/array_range_mismatch_units/ast.snap
rust/kcl-lib/tests/array_range_mismatch_units/execution_error.snap
rust/kcl-lib/tests/array_range_mismatch_units/input.kcl
rust/kcl-lib/tests/array_range_mismatch_units/ops.snap
rust/kcl-lib/tests/array_range_mismatch_units/unparsed.snap
rust/kcl-lib/tests/array_range_negative_expr/program_memory.snap
rust/kcl-lib/tests/array_range_with_units/artifact_commands.snap
rust/kcl-lib/tests/array_range_with_units/artifact_graph_flowchart.snap
rust/kcl-lib/tests/array_range_with_units/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/array_range_with_units/ast.snap
rust/kcl-lib/tests/array_range_with_units/input.kcl
rust/kcl-lib/tests/array_range_with_units/ops.snap
rust/kcl-lib/tests/array_range_with_units/program_memory.snap
rust/kcl-lib/tests/array_range_with_units/unparsed.snap
rust/kcl-lib/tests/double_map_fn/ops.snap
rust/kcl-lib/tests/double_map_fn/program_memory.snap
rust/kcl-lib/tests/import_async/ops.snap
rust/kcl-lib/tests/kcl_samples/gear/ops.snap
rust/kcl-lib/tests/loop_tag/ops.snap

Stacked on #6816.
Before, we silently ignored units in array range expressions and always returned Count. Possible design choices:
1. Automatically coerce start and end values to Count
2. Error out if either start or end are not Count
3. Allow ranges to have any units
This PR chooses # 3 because I don't see any reason why we should prevent users from creating ranges of numbers that have units other than Count.
This is a breaking change because the units of resulting numbers can affect automatic unit conversion. It's also now an error to try to make a range where the units of start and end do not match. E.g. this is an error now: `[1mm..3in]`.
KCL samples use ranges, and their internal memory was changed. But no visual output was affected by this.

Fix to use correct units for array range expressions

---

.github/workflows/e2e-tests.yml
Makefile
package.json

In preparation for adding more KCL samples testing (https://github.com/KittyCAD/engine/issues/3412), I wanted to simplify the logic in our CI setup. Since end-to-end tests are much more reliable now, I think the tradeoff of reducing complexity is worth having them run on every PR. By removing conditions, we're actually running tests a bit sooner.

Always run end-to-end tests

---

src/components/LowerRightControls.tsx
src/components/ToastUpdate.tsx
src/routes/utils.ts

Two more tweaks around release links and updater toast after #6871 
Tested locally:

Release link and updater toast touchups on Nightly

---

Makefile
package.json
rust/Cargo.lock
rust/kcl-lib/Cargo.toml
rust/kcl-lib/src/simulation_tests/kcl_samples.rs

This is preliminary work for https://github.com/KittyCAD/engine/issues/3412. The [internal KCL samples](https://github.com/KittyCAD/kcl-samples-internal) have a nested directory structure so I have updated `generate_kcl_manifest` to support that.
This will let us test against the internal samples locally like so:
```
cd ~/Code/zoo
git clone https://github.com/KittyCAD/kcl-samples-internal 
cd ~/Code/zoo/modeling-app/public/kcl-samples
ln -s ../../../kcl-samples-internal internal
cd ~/Code/zoo/modeling-app/rust/kcl-lib
EXPECTORATE=overwrite cargo test generate_manifest
```
Then, on CI I'll find a way to clone https://github.com/KittyCAD/kcl-samples-internal into the samples directory to test against both.

Check all nested KCL samples

---

docs/kcl-lang/types.md

Jon removed support for obj["a"] a while ago in #6529 aka 2e754f2a11824bf000bbc7c4ccbb030e5cfee828

Fix docs for object properties

---

src/components/CommandComboBox.tsx
src/components/ModelingMachineProvider.tsx
src/hooks/useStateMachineCommands.ts
src/lib/commandTypes.ts
src/lib/createMachineCommand.ts
src/machines/commandBarMachine.ts

Currently, if you open the command palette before an engine connection is established, **you will never see them in the palette**. This is bad. This PR makes it possible to add and remove commands from any `commandBarMachine` state without changing the state, and it adds a `disabled` command configuration option, which it uses for the modeling commands.
https://github.com/user-attachments/assets/8ffb3f72-5269-4114-91f1-12e77158715d
@lee-at-zoo-corp I do actually need a `useMemo` for once 😆

Register modeling commands as disabled, enable without needing to re-open the command palette

---

.github/workflows/static-analysis.yml

Before: https://github.com/KittyCAD/modeling-app/actions/runs/14984901799/job/42097033589
> ✓ src/lang/kclSamples.test.ts (42 tests) 5788ms
After: https://github.com/KittyCAD/modeling-app/actions/runs/14985208778/job/42097949882?pr=6889
>✓ src/lang/kclSamples.test.ts (101 tests) 8835ms
--- 
This contributes to https://github.com/KittyCAD/engine/issues/3412 using the tooling added in https://github.com/KittyCAD/modeling-app/pull/6880.
`$GH_PAT_KCL_SAMPLES_INTERNAL` is a personal access token with fine-grained scope to https://github.com/KittyCAD/kcl-samples-internal that will expire in one year.

Check both public and internal KCL samples

---

src/machines/modelingMachine.ts

Only include the file pane on desktop. This should encourage users to try point-and-click and feature tree workflows. After #6629 is completed, we should default to the code pane being closed, and in the future we should support Blender-like Areas and Workspaces so users can set their own setups that persist nicely.

Default to the feature tree, code, and file panes open

---

src/machines/systemIO/systemIOMachine.ts

Relates to #6820, no fix but would help pinpoint this in the future

SystemIOMachine: Toast default error instead of empty string

---

e2e/playwright/regression-tests.spec.ts

Contributes to https://github.com/KittyCAD/modeling-app/issues/2978 by addressing flakiness in this test: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/239?branch=remove-unneeded-checks

Remove unneeded check on the network health text label

---

e2e/playwright/test-utils.ts
src/lib/exportSave.ts

Contributes to https://github.com/KittyCAD/modeling-app/issues/2978 by addressing flakiness in this test: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/257?branch=longer-toast-in-test

Keep toast message around longer when testing

---

rust/kcl-lib/e2e/executor/main.rs
rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/execution/kcl_value.rs
rust/kcl-lib/src/execution/mod.rs
rust/kcl-lib/src/std/args.rs
rust/kcl-lib/tests/argument_error/execution_error.snap
rust/kcl-lib/tests/array_elem_pop_empty_fail/execution_error.snap
rust/kcl-lib/tests/comparisons_multiple/execution_error.snap
rust/kcl-lib/tests/error_inside_fn_also_has_source_range_of_call_site_recursive/execution_error.snap
rust/kcl-lib/tests/invalid_member_object/execution_error.snap
rust/kcl-lib/tests/panic_repro_cube/execution_error.snap

Resolves #6818. To debug other issues, it was useful to do this now rather than wait until later.

Change KCL error messages to display principal type of values

---

e2e/playwright/sketch-tests.spec.ts
src/lang/KclSingleton.ts

Fixes https://github.com/KittyCAD/modeling-app/issues/6300

#6300 Fix wrong Feature Tree when switching to kcl file with errors

---

.github/workflows/e2e-tests.yml

Now that we're running the native file menu tests again, the macOS shard is averaging above 10 minutes.
With this change the smaller macOS and Windows suites should finish before Ubuntu.

Shard macOS and Windows e2e tests

---

src/lang/KclSingleton.ts

Related to https://github.com/KittyCAD/modeling-app/issues/6300, also pretty small, fixes this current behaviour:
- open file with any KCL errors
- leave project and open a new project with no errors
-> you still see the error notification in the Feature Tree from the previous file, until the new code is executed and errors are cleared.

Clear errors when leaving file to avoid seeing previous files errors

---

e2e/playwright/regression-tests.spec.ts
src/lib/exportSave.ts

[This test](https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/257 ) is still failing occasionally with this error:
```Locator: getByText('Exported successfully')
Expected: 2
Received: 1
Call log:
- expect.toHaveCount with timeout 5000ms
- waiting for getByText('Exported successfully')
8 × locator resolved to 3 elements
- unexpected value "3"
- locator resolved to 1 element
- unexpected value "1"
at /home/runner/_work/modeling-app/modeling-app/e2e/playwright/regression-tests.spec.ts:548:41
```
If we want to confirm both export toasts are visible then we need them to stay around even longer. The 5 seconds added in https://github.com/KittyCAD/modeling-app/pull/6902 isn't always enough.
Results for this branch: …

Keep test toast messages around for longer

---

e2e/playwright/desktop-export.spec.ts

This test started failing: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/133?branch=check-final-export
I don't think we need to care about the intermediate toast messages, just the final one on successful export.

Stop checking for intermediate export toasts

---

src/routes/Settings.tsx

Fixes #6202 
Very small, bit of a hack..
I think this was working already when closing the settings with the "x" button, it was only needed when closing it with the Esc key.
Also, I'm not sure the `useHotkey('esc', ..)` is needed, escape works for me without that..

#6202 Save input value before closing settings dialogue

---

src/components/EngineStream.tsx
src/components/ViewControlMenu.tsx
src/lib/resetCameraPosition.ts

Just copying some logic from the EngineStream code to make that button behave the same way: old initial camera position while in Playwright, isometric view for normal users.

Make the Reset View button do the same view_isometric behavior as load

---

rust/.config/nextest.toml

I'm not sure this is all correct, but this increases the max concurrency for engine tests from 2 (4/2, iiuc) to 32 (32/1) locally and 16 (32/2) in CI.
It also increases the local timeout to the same as in CI, since I sometimes hit it for the longer tests and it annoys me :-)

Permit concurrent unit tests

---

.github/workflows/build-apps.yml
CONTRIBUTING.md

Since https://github.com/KittyCAD/modeling-app/pull/6877/files, we allow the electron-updater to downgrade, so whatever is in the release bucket is prompted in the toast to the user.
This effectively makes the current dedicated updater-test builds in release smoke testing useless, since a release candidate will now automatically prompt to update to the last release out there, which is effectively a downgrade, but is still perfectly fine coverage for what we needed here: making sure the build we ship can run the update.
So I'm removing the steps for updater-test, and will also delete my branch publishing the dummy builds https://github.com/KittyCAD/modeling-app/tree/updater-test. The readme is updated as well.
This was noticed and first tested in #6950

Remove updater-test builds

---

rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/execution/types.rs
rust/kcl-lib/src/std/args.rs

Closes https://github.com/KittyCAD/modeling-app/issues/6953
If we coerce a number to another number then we hack things a little bit so as to avoid converting units. However, if you coerce to an unknown number type, that resulted in number value with unknown units, breaking an invariant that units are never partially specified (i.e., no values should ever have type `number(Length)`).
This PR fixes that by not resetting the type of a number before coercion unless it is being coerced to a fully specified numeric type. Such coercions are still allowed, but will only succeed if the number already has units and those are then not erased (we keep the more precise units). Both conditions are tested in the new unit test.
For good measure, I've made the assertion which caught this debug-only to …

Do not coerce unknown numbers and preserve known units if present

---

rust/kcl-lib/src/execution/exec_ast.rs
src/lang/wasm.ts

Resolves #6879.
I made a `lib.kcl` file that looks like this:
```kcl
export fn check(@x) {
return assert(x, isGreaterThan = 0)
}
```
Before
Clicking "View error" does nothing.
After
Clicking "View error" moves the cursor to the line with the red underline. Hover displays the message in the tooltip.
When it's in the same file, we also correctly show the call location now.
Before
After

Fix to display errors at the call site

---

rust/kcl-lib/src/execution/types.rs

I created this just recently, so figured I'd remove the panic.
Maybe we could make a macro for this so that it isn't so verbose. The correct thing should be easy and ergonomic.

Change runtime assert to runtime error and debug assert

---

e2e/playwright/onboarding-tests.spec.ts

1. Remove all `waitFor` hidden states for the post-dismiss toast: something about Playwright is making toasts hang in a way I've never seen in real use. Not something I'm worried about, and we still test that the toast fires the first time we dismiss.
2. Remove all `scene.connectionEstablished()` calls. This has me more worried because some of the flakiness on this front seems like we're not able to handle the rapid machine-speed navigation and overwriting that this test does when it doesn't have to `waitFor` toasts to disappear. But that is not the point of this test, which is just to ensure the onboarding plays correctly and initiates correctly.

Deflake onboarding test

---

src/components/EngineStream.tsx

I did this fix, because @lee-at-zoo-corp said basically yeah just fix the effect.
But can't help but think we should add a guard to the `start-or-reconfigure-engine` event when it comes from the `waiting-for-dependecies` state, to check whatever something and not allow the transition.
Should get this in, because it's no the hot path for sure.

[Bug] fix big screen boot up bug

---

src/components/CommandBar/CommandBarHeader.tsx

Relates #6976, follow-up to #6989
Before:
After:

Quick follow up fixing up experimetal progress/submit button colors

---

src/index.css

A CSS selector just needed `.dark` prepended to it.
After:

Fix light mode code mirror tooltip

---

src/Toolbar.tsx
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/toolbar.ts

Relates to #6976
After: Warning in the rich tooltip for the whole command, just like for disabled
Before: Warning on the arguments, with an unfortunate tan background:

Change warning message on Chamfer for a more discreet note in tooltip

---

src/components/CommandBar/CommandBarSelectionInput.tsx
src/components/CommandBar/CommandBarSelectionMixedInput.tsx
src/components/CommandBar/CommandBarTextareaInput.tsx
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/commandTypes.ts
src/lib/createMachineCommand.ts

Relates to #6976.
Removing one last forgotten warning message for prompt to edit. And also taking the whole pattern down so we stop using it.

Remove the warningMessage field for command args

---

src/commandLineArgs.test.ts

- iterate command line argument test cases with `forEach`

Replace map with forEach in CLI arg tests

---

src/App.tsx
src/components/WasmErrToast.tsx

Follow-up to #6973 after I realized that new users will see a tempting little toast at the bottom of their screen that might lead them to dismiss the command palette after arriving in the app from a link with a command query on it. This should avoid the scenario where someone clicks an "open sample" type link and dismisses the command palette before they can finish what they're doing. I want to make the command palette just less easy to accidentally dismiss but I think that will require more thought than I have at the moment.

Make warning toast not appear if the URL has any search params

---

rust/kcl-lib/src/execution/artifact/mermaid_tests.rs
rust/kcl-lib/tests/assembly_mixed_units_cubes/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/assembly_non_default_units/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/import_function_not_sketch/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/import_side_effect/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/import_whole_simple/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/import_whole_transitive_import/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/axial-fan/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/bench/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/car-wheel-assembly/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/multi-axis-robot/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/pillow-block-bearing/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/pipe-flange-assembly/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/walkie-talkie/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/module_return_using_var/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/pattern_circular_in_module/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/pattern_linear_in_module/artifact_graph_flowchart.snap.md

We don't support editing geometry generated in other modules. So these aren't actually a problem.

Remove false positive missing messages for other module SourceRanges

---

README.md
src/components/Settings/AllSettingsFields.tsx

Follow-up to link clean up in #7010.
Now that 'nightly' builds are straight from main they can be confusing to regular users stumbling on these links in the wild.

Remove remaining links to nightly

---

rust/kcl-lib/src/simulation_tests.rs

Authored by @rukai
Replaces/closes #7031.
---
I was poking around the repo and noticed that an issue slipped through in https://github.com/KittyCAD/modeling-app/pull/7022
String interpolation was attempted but no formatting macro was used.
This PR fixes the issue.
I used `unwrap_or_else` with `panic`, instead of `expect` with `format` to avoid allocating the error string in the success path.
Before:
After:

Fix simulation_test file load error

---

docs/kcl-std/patternCircular2d.md
docs/kcl-std/patternCircular3d.md
rust/kcl-lib/src/docs/mod.rs
rust/kcl-lib/src/std/patterns.rs

Seems like most users would want these, they seem like sensible defaults.

KCL: Default circular pattern rotateDuplicates=true, arcDegrees=360

---

src/hooks/useNetworkStatus.tsx

- avoid accumulating event listeners in `useNetworkStatus`

Fix cleanup in network status hook

---

src/lib/commandBarConfigs/applicationCommandConfig.ts

This argument is hidden since it's marked as skip, so browser users who must now invoke the command through the command palette have no way of setting the value. Since it is also required, the command palette fails silently on submission (which we need to fix more broadly). This gives it a default value so that users can submit properly.

Give a default value to `projectName` in Text-to-CAD Create command to allow invocation through command palette

---

e2e/playwright/command-bar-tests.spec.ts
e2e/playwright/fixtures/cmdBarFixture.ts
e2e/playwright/fixtures/homePageFixture.ts
src/components/CommandBar/CommandBarTextareaInput.tsx

Fix: Esc key doesn't work in Text-to-CAD prompt

---

src/lib/toolbar.ts

We want users to make edits first and foremost within projects, so we're going to surface it as the default workflow button in the toolbar. WIP until I verify that tests are okay with this.

Make Text-to-CAD Edit the default workflow in the toolbar

---

rust/kcl-lib/src/std/sketch.rs
rust/kcl-lib/tests/kcl_samples/helium-tank/artifact_commands.snap
rust/kcl-lib/tests/kcl_samples/helium-tank/program_memory.snap
rust/kcl-lib/tests/kcl_samples/router-template-cross-bar/artifact_commands.snap
rust/kcl-lib/tests/kcl_samples/router-template-cross-bar/program_memory.snap
rust/kcl-lib/tests/kcl_samples/router-template-slate/program_memory.snap

Resolves #5621.
The `Sketch` and `Path` structs used to store coordinates in the units of whatever the first point (from `startSketch(at = ...)`) used. But now we store them in the default length unit of the module, i.e. whatever is set by `@settings()`. This is what the frontend expects and uses in point-and-click.
I find it interesting that there are a few samples that use one default unit, but specify variables in another unit, so their internal representation was changed by this.

Change Sketch to use the units of the module

---

.github/workflows/e2e-tests.yml

This change is needed for https://github.com/KittyCAD/modeling-app/pull/6960 to actually work.
If we don't do this, we should instead removed the unused steps via https://github.com/KittyCAD/modeling-app/pull/7074.

Update snapshots on CI

---

src/components/CommandBar/CommandBarTextareaInput.tsx

We have a hook to auto-grow the textarea input but it wasn't running once initially. This is noticable on the onboarding, where we show the user a long Text-to-CAD Edit prompt that overflows.

Make the textarea command bar input run its resize initially

---

e2e/playwright/fixtures/cmdBarFixture.ts
e2e/playwright/point-click.spec.ts
src/components/CommandBar/CommandBarHeader.tsx

Fixes #7026. The Submit button in the command palette was not being focused for two reasons:
- in #4469 we set all `ActionButton`s to have `tabIndex={1}` making them unfocusable. I want to change this as it has caused a few keyboard use issues like this. For now, I made the `ReviewingButton` and the `GatheringArgsButton` both have `tabIndex={0}` so they become focusable without undoing the work done in that PR to make tooltips and outlines behave better.
- I discovered why the `autoFocus` attribute on this button was not having an impact on these buttons. As a Headless UI Dialog element, the first focusable element is coerced to get focus from that component, and the only static way to override that is by [passing a ref to `initialFocus`](https://headlessui.com/v1/react/dialog#managing-ini …

Fix enter key loop in sweep commands

---

rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/simulation_tests.rs
rust/kcl-lib/tests/export_var_only_at_top_level/artifact_commands.snap
rust/kcl-lib/tests/export_var_only_at_top_level/artifact_graph_flowchart.snap
rust/kcl-lib/tests/export_var_only_at_top_level/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/export_var_only_at_top_level/ast.snap
rust/kcl-lib/tests/export_var_only_at_top_level/execution_error.snap
rust/kcl-lib/tests/export_var_only_at_top_level/input.kcl
rust/kcl-lib/tests/export_var_only_at_top_level/ops.snap
rust/kcl-lib/tests/export_var_only_at_top_level/unparsed.snap

Resolves #4433.
It's a non-fatal runtime error. Ideally, we'd carry extra context in the parser or have a static analysis phase so that we didn't need to actually execute the `export` to detect it. The bad `export` could be inside a lib function that you don't call.

Show error when trying to export at non-top-level

---

src/lib/resetCameraPosition.ts
src/lib/utils.ts

When loading into the modeling page the user's camera projection setting was completely ignored when I updated the code to use the `view_isometric` endpoint.
Within `resetCameraPosition` I check we are in the user workflow and if the user has `perspective` set and we set the camera to perspective before doing the other camera API calls.
I grab a snapshot of the settings and check what the camera should reset to based on the user settings
>  `cat ~/.config/zoo-modeling-app/settings.toml ` to see if I have undefined setting
| Has Geometry | User Setting | Does it work (end result) |
|--------|--------|--------|
| No | undefined | orthographic | 
| Yes | undefined | orthographic |
| No | Perspective | Perspective |
| Yes | Perspective | Perspective |
| No | orthographic (actually undefined) …

[Fix]: When loading the modeling page the user's settings for camera projection was ignored

---

e2e/playwright/command-bar-tests.spec.ts
e2e/playwright/editor-tests.spec.ts
e2e/playwright/point-click.spec.ts
e2e/playwright/sketch-tests.spec.ts
e2e/playwright/various.spec.ts
src/components/CommandBar/CommandBarSelectionInput.tsx

Fixes #7080
This fixes a double-fire of the clean up callback calling onSubmit.
And we're back to the non-skip behavior on multi profile sweeps before #7047

Fix: Can't go back to Profiles arg in Extrude, Revolve, Loft

---

src/lib/commandBarConfigs/modelingCommandConfig.ts

Fixes #7121
Just trying to be a little more descriptive because this keeps confusing me

Impove naming in point-and-click Revolve to convey that axis are relative

---

src/components/ModelingMachineProvider.tsx

The browser version of Text-to-CAD Edit started failing after we implemented a recent change to keep the user in their current file with Text-to-CAD Edit, causing it to start to silently fail. This restores that bespoke behavior in the browser.

Fix: Follow up Text-to-CAD Edit to fix in browser

---

src/lib/commandBarConfigs/applicationCommandConfig.ts

There is now a `projectName` that isn't included in the query params I was using and wasn't including in the URLs I was building.

Fix open KCL sample via URL query param in browser

---

.github/workflows/cargo-test.yml
.github/workflows/e2e-tests.yml

Here's an example of an engine change that required us to update samples: https://github.com/KittyCAD/modeling-app/pull/7129
It would be good to detect things like this sooner by getting a continuous baseline of results against the `main` branch. This will also help with capturing flakiness metrics.

Run the KCL tests every hour to detect regressions

---

INSTALL.md
public/announce_release.py
src/lib/constants.ts

https://zoo.dev/modeling-app/download will eventually turn into a redirect.

Link to the new download page

---

rust/justfile
rust/kcl-lib/src/simulation_tests.rs
rust/kcl-lib/src/simulation_tests/kcl_samples.rs

1. The graph output became non-deterministic due to concurrent module execution
2. We started adding a lot more samples
3. Samples tend to be large, so no one looks at the updates anyway. People just accept the changes.
The result is that artifact graph samples tests in the `cargo test` CI job are really flaky with no real benefit.
This PR makes it so that we skip the assertion for samples, but we continue to write the output. As a developer, you should either use the `just` commands or the new environment variable `ZOO_SIM_UPDATE=always`.

Change to skip asserting the artifact graph for samples

---

src/hooks/useAuthNavigation.tsx
src/hooks/useQueryParamEffects.ts
src/routes/SignIn.tsx

So users can return to their invoked command after signing in. This PR also includes a change to not run query param-powered commands if the user is not logged in.

Pass the query parameters through to sign-in flow

---

e2e/playwright/editor-tests.spec.ts
rust/kcl-derive-docs/src/lib.rs
rust/kcl-derive-docs/src/tests.rs
rust/kcl-derive-docs/tests/args_with_lifetime.gen
rust/kcl-derive-docs/tests/args_with_refs.gen
rust/kcl-derive-docs/tests/array.gen
rust/kcl-derive-docs/tests/box.gen
rust/kcl-derive-docs/tests/doc_comment_with_code.gen
rust/kcl-derive-docs/tests/lineTo.gen
rust/kcl-derive-docs/tests/min.gen
rust/kcl-derive-docs/tests/option.gen
rust/kcl-derive-docs/tests/option_input_format.gen
rust/kcl-derive-docs/tests/return_vec_box_sketch.gen
rust/kcl-derive-docs/tests/return_vec_sketch.gen
rust/kcl-derive-docs/tests/show.gen
rust/kcl-derive-docs/tests/test_args_with_exec_state.gen
rust/kcl-lib/src/docs/mod.rs
rust/kcl-lib/src/std/sketch.rs

Before, the LSP snippet for `startProfile` was 
```
startProfile(%, at = [3.14, 3.14])
```
Now it's 
```
startProfile(%, at = [0, 0])
```
This is configured by adding a `snippet_value=` field to the stdlib macro. For example:
```diff
#[stdlib {
name = "startProfile",
keywords = true,
unlabeled_first = true,
args = {
sketch_surface = { docs = "What to start the profile on" },
-       at = { docs = "Where to start the profile. An absolute point." },
+       at = { docs = "Where to start the profile. An absolute point.", snippet_value = "[0, 0]" },        tag = { docs = "Tag this first starting point" },
},
tags = ["sketch"]
}]
```
- Make this work for KCL functions defined in KCL, e.g. [`fn circle`](https://github.com/KittyCAD/modeling-app/blob/36c8ad439d4d26b95ba2391ae25dc86cb3e468f0/rust/k …

KCL: Customizable per-arg and per-fn snippet values

---

rust/kcl-derive-docs/src/lib.rs
rust/kcl-derive-docs/tests/args_with_lifetime.gen
rust/kcl-derive-docs/tests/args_with_refs.gen
rust/kcl-derive-docs/tests/array.gen
rust/kcl-derive-docs/tests/box.gen
rust/kcl-derive-docs/tests/doc_comment_with_code.gen
rust/kcl-derive-docs/tests/lineTo.gen
rust/kcl-derive-docs/tests/min.gen
rust/kcl-derive-docs/tests/option.gen
rust/kcl-derive-docs/tests/option_input_format.gen
rust/kcl-derive-docs/tests/return_vec_box_sketch.gen
rust/kcl-derive-docs/tests/return_vec_sketch.gen
rust/kcl-derive-docs/tests/show.gen
rust/kcl-derive-docs/tests/test_args_with_exec_state.gen
rust/kcl-lib/src/docs/mod.rs
rust/kcl-lib/src/lsp/kcl/mod.rs
rust/kcl-lib/src/std/appearance.rs
rust/kcl-lib/src/std/assert.rs
rust/kcl-lib/src/std/csg.rs
rust/kcl-lib/src/std/edge.rs
rust/kcl-lib/src/std/extrude.rs
rust/kcl-lib/src/std/loft.rs
rust/kcl-lib/src/std/patterns.rs
rust/kcl-lib/src/std/segment.rs
rust/kcl-lib/src/std/shapes.rs
rust/kcl-lib/src/std/sketch.rs
rust/kcl-lib/src/std/sweep.rs
rust/kcl-lib/src/std/transform.rs

This has been enforced by the parser since #6639, so there's no need for `keywords = true` in every stdlib function anymore.

KCL: stdlib macro should now assume all functions use keywords

---

rust/kcl-lib/src/docs/kcl_doc.rs
rust/kcl-lib/src/docs/mod.rs
rust/kcl-lib/std/sketch.kcl

In #7156, I allowed KCL to set specific snippet completions for each arg of each function. They're optional -- if you don't set one, it'll fall back to the type-driven defaults.
That PR only worked for KCL stdlib functions defined in Rust. This PR enables the same feature, but for functions defined in KCL.

KCL: Custom snippet values for kcl-in-kcl

---

rust/kcl-lib/src/docs/mod.rs
rust/kcl-lib/src/std/patterns.rs
rust/kcl-lib/src/std/shapes.rs

Pattern functions and `polygon` both take a parameter `center` which defaulted to [3.14, 3.14] for silly reasons. They now default to [0, 0].

KCL: Autocomplete snippets for 'center' should suggest the origin

---

src/components/ToastTextToCad.test.tsx
src/components/ToastTextToCad.tsx

Closes #5792. I tried to move these over to our new component test bucket, but Remark doesn't play nice with that testing setup at least in my initial attempts.

Add markdown rendering to TTC error toast, with component tests

---

docs/kcl-std/patternLinear3d.md
rust/kcl-lib/src/docs/mod.rs
rust/kcl-lib/src/std/patterns.rs

`[3.14, 3.14]` is not a sensible default axis for a pattern.

KCL: Set sensible defaults for pattern 'axis' arg

---

package-lock.json
src/routes/SignIn.tsx

@JBEmbedded pointed this out, and we don't want a bad look for website browsers who click a stray "Try in Browser" link. There's a little message saying we're working on touch controls for now, and we steal their signin button.

Fix up the sign-in page's mobile layout

---

rust/kcl-lib/src/execution/artifact.rs

Conclusion from discussions was that even if internal error messages aren't helpful, they're better than panicking. But in tests, panicking is more likely to surface. I'll be converting assertions to "runtime error or debug panic" as I come across them.

Change artifact panics to runtime errors

---

rust/kcl-lib/src/execution/artifact.rs
rust/kcl-lib/src/simulation_tests.rs
rust/kcl-lib/tests/kcl_samples/bottle/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/cold-plate/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/helium-tank/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/kcl_samples/i-beam/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/subtract_regression10/artifact_graph_flowchart.snap.md

Part of #6440.
When using `mirror2d()` and the engine creates geometry, we now add that to the artifact graph, making it selectable. This makes the following KCL in the linked issue selectable, but it doesn't solve the other problematic examples.
```kcl
sketch003 = startSketchOn(offsetPlane(XY, offset = 21.5))
|> startProfile(at = [-61.85, 0])
|> yLine(length = 6.21)
|> xLine(endAbsolute = 61.8, tag = $myTag)
|> yLine(endAbsolute = 0)
|> close()
|> mirror2d(axis = X)
|> extrude(length = 100)
```
Check out the bottle sample's Mermaid flow chart. The graph used to have two disconnected components. Now, there are a lot more segments and the graph components are connected. The sketch-on-face part has been moved from floating to all the way on the right, built on top of everything else, where …

Fix mirror2d selection by adding artifact graph support

---

index.html
src/index.css
tailwind.config.js

Our team started getting *rate limited* with access to the font, which meant the app wasn't loading for them 😱. I don't want us to risk any user being rate limited because of a font ever.
Here are some examples of the impact of this change in the UI. We use Owners in some headings and display text as a nod to the marketing site currently.

Remove Owners font from the modeling app

---

rust/kcl-lib/src/unparser.rs

In #7179 I added exclusive ranges for KCL, but I forgot to update the formatter/unparser to handle them. So it was silently changing exclusive-end ranges to inclusive-end ranges.

Bugfix: formatter changed [0..<4] to [0..4]

---

src/lib/textToCad.ts
src/lib/trap.ts

So that users can see if they're blocked, for example.

Bubble up the actual error message in the Text-to-CAD toast message

---

src/lib/operations.ts

KCL uses a default value if the keyword argument isn't present, so the feature tree edit flow should do the same. In the future these should flow from the same source of truth so that the feature tree doesn't have to duplicate default arg values like this.

Don't error when editing via feature tree if no `angle` arg is present in revolve, use `360deg`

---

rust/kcl-lib/src/simulation_tests.rs

This has been very flaky since the output is non-deterministic. The issue has been updated.

Disable subtract_regression08 artifact graph test

---

docs/kcl-std/arc.md
docs/kcl-std/tangentialArc.md
rust/kcl-lib/src/docs/mod.rs
rust/kcl-lib/src/std/shapes.rs
rust/kcl-lib/src/std/sketch.rs

Both these functions previously took a `radius`. If you previously used the radius arg, you can keep using it, or you can use `diameter` instead.

Add diameter arg to arc and tangentialArc

---

rust/kcl-lib/e2e/executor/main.rs
rust/kcl-lib/src/execution/types.rs
rust/kcl-lib/src/std/args.rs
rust/kcl-lib/src/std/array.rs
rust/kcl-lib/src/std/assert.rs
rust/kcl-lib/src/std/chamfer.rs
rust/kcl-lib/src/std/extrude.rs
rust/kcl-lib/src/std/fillet.rs
rust/kcl-lib/src/std/helix.rs
rust/kcl-lib/src/std/loft.rs
rust/kcl-lib/src/std/patterns.rs
rust/kcl-lib/src/std/planes.rs
rust/kcl-lib/src/std/revolve.rs
rust/kcl-lib/src/std/segment.rs
rust/kcl-lib/src/std/shapes.rs
rust/kcl-lib/src/std/sketch.rs
rust/kcl-lib/src/std/sweep.rs
rust/kcl-lib/src/std/transform.rs

There are still some left over for tags and functions which need a little thinking.

Refactoring: use typed versions of args getters

---

.github/workflows/e2e-tests.yml

I've seen a few cases of Vector failing to start on the default macOS runners.
Contributes to #6773

Use the same OS images for web and desktop e2e

---

rust/kcl-lib/src/parsing/parser.rs

Previously, this KCL
```
arc(
endAbsolute = [0, 50]
interiorAbsolute = [-50, 0]
)
```
gave the error `This argument has a label, but no value. Put some value after the equals sign`.
Now it gives this much better error, on the whitespace which was missing a comma:
Thanks for reporting this @benjamaan476

KCL: Fix cryptic error when missing commas between arguments

---

rust/kcl-lib/src/execution/mod.rs
rust/kcl-lib/src/parsing/parser.rs

This program:
```kcl
1
|> extrude(
length=depth,
})
```
was giving this bad error:
```
unexpected token |>
```
Now it gives
```kcl
There was an unexpected }. Try removing it.
```
and it correctly puts the diagnostic on the extra }.
Fixes https://github.com/KittyCAD/modeling-app/issues/6126

KCL: Fix cryptic error on unexpected tokens in fn call

---

docs/kcl-std/close.md
rust/kcl-lib/src/std/sketch.rs

Tried to give some detail as to why you call `close` in addition to it draws a line to close the shape. Happy to tweak this to better fit style, the main thing I want to make sure we capture is that it's necessary to call this, not just a utility to draw the last segment.

Add more detail to close() docs

---

src/lang/wasm.test.ts

Previous PR (#7321) was set to automerge, but apparently the npm-unit-test CI target doesn't block merges if it fails. Fixed now.

Fix broken WASM test

---

rust/kcl-lib/src/errors.rs
rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/execution/fn_call.rs
rust/kcl-lib/src/execution/memory.rs
rust/kcl-lib/src/execution/state.rs
rust/kcl-lib/src/simulation_tests.rs
rust/kcl-lib/src/std/csg.rs
rust/kcl-lib/tests/var_ref_in_own_def/artifact_commands.snap
rust/kcl-lib/tests/var_ref_in_own_def/artifact_graph_flowchart.snap
rust/kcl-lib/tests/var_ref_in_own_def/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/var_ref_in_own_def/ast.snap
rust/kcl-lib/tests/var_ref_in_own_def/execution_error.snap
rust/kcl-lib/tests/var_ref_in_own_def/input.kcl
rust/kcl-lib/tests/var_ref_in_own_def/ops.snap
rust/kcl-lib/tests/var_ref_in_own_def/unparsed.snap

Previously, `x = cos(x)` would just say "`x` is undefined". Now it says that `x` cannot be referenced in its own definition, try using a different variable instead.
To do this, I've added a new `Option<String>` field to the mod-local executor context, tracking the current variable declaration. This means cloning some strings, implying a small performance hit. I think it's fine, for the better diagnostics.
In the future we could refactor this to use a &str or store variable labels in stack-allocated strings like docs.rs/compact_str or something.
Closes https://github.com/KittyCAD/modeling-app/issues/6072#issuecomment-2923227477

KCL: Fix 'cryptic' error when referencing a variable in its own declaration

---

rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/tests/var_ref_in_own_def/artifact_commands.snap
rust/kcl-lib/tests/var_ref_in_own_def/artifact_graph_flowchart.snap.md
rust/kcl-lib/tests/var_ref_in_own_def/ast.snap
rust/kcl-lib/tests/var_ref_in_own_def/execution_error.snap
rust/kcl-lib/tests/var_ref_in_own_def/input.kcl
rust/kcl-lib/tests/var_ref_in_own_def/ops.snap
rust/kcl-lib/tests/var_ref_in_own_def/unparsed.snap

I thought I did this in https://github.com/KittyCAD/modeling-app/pull/7325, but I forgot to actually set the better message.
Actually forreal fixes https://github.com/KittyCAD/modeling-app/issues/6072 this time.

KCL: Better error message when using var in its own definition

---

src/hooks/useAuthNavigation.tsx
src/lib/constants.ts
src/routes/SignIn.tsx
src/routes/utils.ts

This is for instances of when users are going to the website version of the application. They should immediately be brought to the main sign on portal.
We can change the behavior to always be this on web but let's start with this conservative change, which has a particular use-case of directing users to design studio from the text-to-cad page, which relies on this PR. https://github.com/KittyCAD/website/pull/3207

Add query parameter to skip the embedded "sign in" view

---

e2e/playwright/sketch-tests.spec.ts

I ran this test 10 times on main and got 5 failures, ran it with [this PR](https://github.com/KittyCAD/modeling-app/pull/7276)’s changes reverted and got similar results (sometimes 5, sometimes 6 fails, seems around 50%).
What I found is that changing the timeout here from 100ms to 200ms makes the test pass 10/10 for me locally, with or without my PR’s changes:
https://github.com/KittyCAD/modeling-app/blob/b47b9c961307494b9562a022c210c11c4a547bd1/e2e/playwright/sketch-tests.spec.ts#L2365
It looks like clicking the rectangle button and starting the rectangle just 100ms after is sometimes not enough time..why that changed recently is a good question.

Stabilize test: "Can edit a sketch with multiple profiles, dragging segments to edit them, and adding one new profile"

---

rust/kcl-lib/src/engine/conn_wasm.rs
rust/kcl-lib/src/execution/typed_path.rs
rust/kcl-wasm-lib/src/context.rs

This brings the `execute_mock` function into line with the `execute` function, which I tweaked in https://github.com/KittyCAD/modeling-app/pull/7351. Now mock execution, like real execution, will always return a properly-formatted KCL error, instead of any possible JS value.
Also, incidentally, I noticed that send_response always succeeds, so I changed it from Result<()> to void.

Better typechecking and error handling in executeMock

---

rust/kcl-lib/src/execution/artifact.rs
rust/kcl-lib/src/execution/cache.rs
rust/kcl-lib/src/execution/import_graph.rs
rust/kcl-lib/src/execution/mod.rs
rust/kcl-lib/src/execution/state.rs
rust/kcl-lib/src/simulation_tests.rs
rust/kcl-lib/src/test_server.rs
rust/kcl-lib/src/walk/mod.rs

This was going to be preliminary work for more caching stuff, but it's got big enough that I think it is worth landing now. The only interesting bit is that caching splits per-module from global info so that in the future we can cache information about each module more easily. There's a bunch of other stuff to just simplify the code because it's got really messy :-(

Execution refactoring

---

rust/kcl-lib/src/std/mod.rs

Turns out that fully-qualified name isn't used at all (I think we used it for error messages at some point), but I've kept it around since it is useful for debugging and difficult to synthesise.

Fix some typos in previous PR

---

rust/kcl-lib/src/parsing/ast/types/mod.rs
rust/kcl-lib/src/unparser.rs

Closes #7482
This is kinda frustrating because we should be preserving user parens, but they aren't preserved. I tried to fix this to use the minimal bracketing, but that caused a lot of changes because we previously had some weird ad-hoc formatting which special-cased subtraction and division. So this does the correct formatting (I think, it's kind of tricky to reason about associativity backwards :-) ) and then does the old ad-hoc stuff too.

Properly respect associativity when reformatting

---

.github/workflows/e2e-tests.yml

This makes it easier to read GH actions and find the artifacts you're looking for.

Nit: Name the various 'upload-artifact' CI steps

---

.github/workflows/cargo-fmt.yml
.github/workflows/nightly-rust-toolchain.toml
rust/kcl-lib/src/execution/kcl_value.rs

Resolves #6780.
The first commit verified that it fails in CI without nightly formatting.

Use nightly rustfmt in CI

---

e2e/playwright/feature-tree-pane.spec.ts
src/components/CommandBar/CommandBarKclInput.tsx
src/components/ModelingSidebar/ModelingPanes/FeatureTreePane.tsx
src/lang/queryAstNodePathUtils.ts
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/operations.ts
src/machines/commandBarMachine.ts
src/machines/modelingMachine.ts

Closes #5729 by
1. Showing the user input value for a named parameter within the Feature Tree item
2. Allowing double-click and right-click menu Edit flows
3. Reinstating the ability for a KCL-type arg to enforce that creating new variables is `disallow`ed
4. Amending an E2E test to verify editing a Parameter through the Feature Tree
https://github.com/user-attachments/assets/86d2ab92-71ee-43b1-ad49-282cce33523e

Add edit flow for Parameters to Feature Tree

---

src/lang/KclSingleton.ts
src/lang/langHelpers.ts
src/lang/wasm.ts

Non-ASCII characters in KCL source code would be displayed wrong, causing weird visuals or at worst, exceptions.
Before:
After:

Fix: Lints with non-ASCII characters

---

src/lib/commandBarConfigs/modelingCommandConfig.ts

Been meaning to do that for a long time, trigger came from https://kittycadworkspace.slack.com/archives/C07A80B83FS/p1750445284424229?thread_ts=1750426012.606539&cid=C07A80B83FS

Chore: clean up duplication of nodeToEdit props

---

src/machines/modelingMachine.ts

When there's an unexpected error, it's really useful to have this in the console to see the stacktrace.

Log to the console when there's an error

---

e2e/playwright/editor-tests.spec.ts
src/Router.tsx

Fixes #5576 
I was thinking the combination of `Control + Shift + .` was captured by the OS on Linux or the `Shift + .` part turned into a `>` character..with period it looks to be working on both Linux and Mac. 
Added a test too.

#5576 Fix coredump hotkey on linux

---

e2e/playwright/point-click.spec.ts
src/components/CommandBar/CommandBarHeaderFooter.tsx
src/lang/modifyAst/addSweep.ts
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/operations.ts
src/machines/commandBarMachine.ts
src/machines/modelingMachine.ts

Fixes #7578
Notes:
- Adds `relativeTo` arg as a set of string options, as well as the edit flow
- Fixes a bug on inability to edit helix-based sweeps
- Fixes missing case in command bar machine guard that would prevent a command with all skipable args to go to review (like Sweep in edit mode)
- Adds e2e test step to edit helix-based sweep and set `relativeTo`

Enable optional arguments in point-and-click Sweep

---

src/main.ts

Fixes #7455 reported by @jacebrowning 
On windows the initially supplied `width`, `height` was capped at the screen resolution which was still not enough to cover the entire screen. Eg. with my horizontal resolution being 2560 I had to pass 2572 to get the app to cover the screen, 2560 left a ~10px border. 
This seems to work as I expect if I call setBounds on the window so I'm just doing that.
We could go a step further and save if the window was in full screen mode before closing, which is not the same on Windows as resizing it manually to cover the screen - but then we also need to save which display it was on in case the user had multiple.
Removed a seemingly unused `reuse` param too.

#7455 Last window size improvements: fix full screen on windows

---

e2e/playwright/point-click.spec.ts
src/lang/modifyAst/addSweep.ts
src/lib/commandBarConfigs/modelingCommandConfig.ts
src/lib/operations.ts
src/machines/modelingMachine.ts

Closes #6923
- Adds `symmetric` and `bidirectionalAngle` KCL args as optional point-and-click args
- Adds e2e test step covering an edit flow with `bidirectionalAngle`

Enable optional arguments in point-and-click Revolve

---

Makefile

This ensures `generate_manifest` is skipped on subsequent runs of `make build`.
It also makes that target a no-op on Windows to avoid non-POSIX paths.

Force the samples manifest to be updated

---

e2e/playwright/editor-tests.spec.ts
rust/kcl-lib/src/lint/checks/camel_case.rs
rust/kcl-lib/src/lsp/tests.rs

From https://github.com/KittyCAD/modeling-app/pull/7546#pullrequestreview-2945780376 and https://github.com/KittyCAD/modeling-app/pull/7546#issuecomment-3000758321
Parametric CAD users are typically used to PascalCase, and hitting 'must' for a lint that's not even an error feels weird to me?
I personally think we should allow PascalCase for non-KCL users, while still nudge KCL users into camelCase, which the current lint does right I believe, except for "must"

Swap "must" for "should" in identifier casing lint

---

e2e/playwright/point-click.spec.ts
src/lang/modifyAst.ts
src/lib/commandBarConfigs/modelingCommandConfig.ts

Fixes #7589
Notes:
- Sets `hidden` on fields that didn't have it before as it was relying on the former behavior of `required`, should have been addressed during #7506 
- Makes `ccw` a true optional arg in the new sense
- Cleans up helix tests (no more runtime map and less reliance on px testing) and add test step for `ccw` as optional arg

Hide Helix arguments that should have been hidden, plus other flow fixes

---

e2e/playwright/can-create-sketches-on-all-planes-and-their-back-sides.spec.ts
e2e/playwright/fixtures/toolbarFixture.ts
src/components/CustomIcon.tsx
src/components/ModelingMachineProvider.tsx
src/components/ModelingSidebar/ModelingPanes/FeatureTreePane.tsx
src/hooks/useEngineConnectionSubscriptions.ts
src/lang/modifyAst.ts
src/machines/modelingMachine.ts

Resolves #4525
https://github.com/user-attachments/assets/d45f6250-e513-4449-b10a-3b2d01edf1c9
This PR implements a fix for issue #4525 - "Offsetting a negative plane flips the plane". The core issue was that when sketching on offset planes, the orientation logic wasn't properly determining which side of the plane was clicked, causing sketches to appear flipped.
changes:
- Fixed offset plane orientation detection by implementing camera-based logic similar to default planes
- Updated KCL code generation to properly generate `-plane001` when sketching on the back side of offset planes
- Copy pasted `Can create sketches on all planes and their back sides` tests and tweaks to test this as well
- added missing aria-label attributes to custom icons (needed one for tests, but figured would be …

[BUG] offsetPlane back-side startSketchOn

---

src/Toolbar.tsx

Fix the vertical alignment on the temporary workspace label

---

rust/kcl-lib/src/execution/fn_call.rs
rust/kcl-lib/src/execution/memory.rs
rust/kcl-lib/src/execution/mod.rs

Closes #7588
We use a stack for memory management. When a function is called we push a new frame onto the stack (aka a root environment). For efficiency and perhaps to catch some bugs, when we call a Rust function (i.e., a std lib function), we don't push a new frame and set the frame 'pointer' to a dummy value. However, when we call map or similar higher-order functions, the Rust definition calls other functions. This should be OK because we'll push a fresh stack frame for the callee if it is a KCL function and if it is a Rust function, it doesn't need a stack frame. However, when we type check the function call we might need to look up names in memory for which we need a real stack frame.
To fix this issue I considered working around this by special-casing the Rust envs, but it …

Use proper envs for Rust functions

---

rust/kcl-lib/src/execution/mod.rs
rust/kcl-lib/src/execution/state.rs

We weren't returning some of the outcome for mock execution. I don't think there was a good reason for this other than the fact that it wasn't being used.

Fix to return operations and module file names in mock execution

---

.env.development
.env.production
interface.d.ts
src/env.test.ts
src/env.ts
src/main.ts
src/preload.ts

This variable does not appear to be used anywhere in the code, nor is it set on Vercel.
Contributes to #3973

Remove unused timeout environment variable

---

rust/Cargo.lock
rust/kcl-bumper/Cargo.toml
rust/kcl-derive-docs/Cargo.toml
rust/kcl-directory-test-macro/Cargo.toml
rust/kcl-language-server-release/Cargo.toml
rust/kcl-language-server/Cargo.toml
rust/kcl-lib/Cargo.toml
rust/kcl-python-bindings/Cargo.toml
rust/kcl-test-server/Cargo.toml
rust/kcl-to-core/Cargo.toml
rust/kcl-wasm-lib/Cargo.toml

- New stdlib `planeOf` function to find the plane of a face
- Planes now have a `zAxis` property (planes are always right-handed)
- Experimental support for conic curves, hyperbolic curves, and ellipses
- Stdlib `translate` function has a new optional argument, `xyz` which lets you specify all axes at once. For example, `translate(xyz = [1, 3.2, 0.5])`
- New stdlib `concat()` and `count()` functions for arrays
- New stdlib `vector` module, with `add`, `sub`, `mul` and `div` component-wise arithmetic. Also `cross`, `dot`, `magnitude` and `normalize` functions.

Release KCL 85

---

src/lib/settings/initialSettings.tsx

This was originally done to catch more bugs in staging leading up to v1, but we're well past that now.

Use the same stream idle mode settings in all environments

---

docs/kcl-lang/settings/user.md
rust/kcl-lib/src/settings/types/mod.rs
src/clientSideScene/CameraControls.ts
src/clientSideScene/ClientSideSceneComp.tsx
src/components/EngineStream.tsx
src/lib/settings/initialSettings.tsx
src/lib/settings/settingsUtils.ts

@mlfarrell ran into an issue with his Linux trackpad registering touch events, which would interfere with his normal usage of the trackpad for camera movement within the app since #7384. We feel pretty confident he's not alone, so here I've added a user-level setting that lets users turn of touch listeners for the camera controls. [There is no reliable way to detect this without the user's input](https://codeburst.io/the-only-way-to-detect-touch-with-javascript-7791a3346685), which is why I've opted to make it an opt-out feature.
https://github.com/user-attachments/assets/cc917bcd-0dcb-44e6-8292-45d731b38010

Add setting to enable touch controls, defaulting to on

---

rust/kcl-lib/src/parsing/parser.rs
rust/kcl-lib/src/parsing/snapshots/kcl_lib__parsing__parser__snapshot_tests__space_between_unary_and_operand.snap

`x = - 1` didn't parse previously. Now it does.

KCL: Parser should allow space after negative

---

rust/kcl-lib/src/execution/mod.rs
rust/kcl-lib/src/execution/types.rs

Before, when coercing a value like `[[[1]]]` to `any`, we see that the type isn't array but we have an array of length 1, and try to recursively strip the array off.
This PR makes it so that `any` accepts anything, including arrays.

Fix to not coerce nested arrays to single level when type is any

---

e2e/playwright/lib/api-reporter.ts

---
Depends on https://github.com/KittyCAD/test-analysis-bot/pull/63

Include metadata for TAB to link back to GitHub Actions runs

---

rust/kcl-lib/benches/compiler_benchmark_criterion.rs

The frontend needs to recast every time the user drags a line/point around in sketch mode, so this should also correlate with user-perceived sketch mode latency.

KCL: Benchmark recast speed

---

rust/kcl-lib/src/execution/fn_call.rs
rust/kcl-lib/tests/kw_fn_unlabeled_but_has_label/execution_error.snap

Error message was using the old `x: value` syntax instead of `x = value`.

Fix to use updated syntax in error message

---

rust/kcl-lib/src/unparser.rs

Improves perf by 27% to 38% on my mac, 56-88% on Codspeed.

KCL: Remove unnecessary clone in recast

---

vite.config.ts

A small percentage of the tests take longer that 1s on average: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app?search=vitest&enabled=true&sort=-average_duration

Increase the vitest timeout from 1s to 2s

---

rust/kcl-lib/src/unparser.rs

Gives a 3% and 7% improvement on my Macbook to recaster benchmarks.

KCL: Remove another clone in recast

---

rust/kcl-lib/src/lib.rs
rust/kcl-lib/src/lint/checks/camel_case.rs
rust/kcl-lib/src/lsp/kcl/mod.rs
rust/kcl-lib/src/parsing/ast/types/mod.rs
rust/kcl-lib/src/simulation_tests.rs
rust/kcl-lib/src/unparser.rs
rust/kcl-lib/tests/export_var_only_at_top_level/unparsed.snap

On my Macbook, this speeds up benchmarks by 2x to 2.7x
Before this PR, most of the recast functions looked like this 
```
fn recast(&self, options, indentation_level) -> String
```
In other words, when they ran, they allocated and returned a string. This mean every function would perform at least 1 allocation.
Now they generally look like this:
```
fn recast(&self, buf: &mut String, options, indentation_level)
```
In other words, they usually accept a string from the caller and append to it, rather than allocating a new one. This reduces allocations (because generally the same single string can be shared across recasts) which saves time (because a huge portion of recast time was just allocating strings, appending their contents to some other string, then dropping it).

KCL: Mostly reuse one string buffer in recaster

---

e2e/playwright/feature-tree-pane.spec.ts
src/components/ModelingSidebar/ModelingPanes/FeatureTreePane.tsx
src/lang/KclSingleton.ts

Operations reference code via CodeRef. We were using whatever code was in KclContext. Weirdly, the KclContext code can get out of sync with CodeManager's code. But that's a red herring. Synchronizing them led to other issues. The real solution was to store the KCL code that was executed so that the Operations refer to what they originated from, regardless of the code editor or KclContext code.
Checklist:

Fix to display the correct code in Feature Tree Parameters

---

src/routes/Onboarding/BrowserOnboardingRoutes.tsx
src/routes/Onboarding/DesktopOnboardingRoutes.tsx

Before:
After:
---
I also updated the Text-to-CAD credits explainer to reflect the new pricing: https://zoo.dev/design-studio-pricing
Alternatively, we could drop the exact count from that modal and use generic wording like "limited number of free credits".

Adjust onboarding to handle the new toolbar location

---

docs/kcl-lang/arithmetic.md

This is what it looks like on the website now.

docs: Fix markdown table formatting with pipe character

---

.github/CODEOWNERS

The `docs` directory is KCL docs.

Change code owner of docs directory to kcl

---

rust/kcl-lib/benches/compiler_benchmark_criterion.rs
rust/kcl-lib/src/parsing/ast/types/mod.rs
rust/kcl-lib/src/parsing/math.rs
rust/kcl-lib/src/parsing/parser.rs

Fixes https://github.com/KittyCAD/modeling-app/issues/7866
This PR fixes two instances of unnecessary backtracking - one in the single unlabelled argument case of parsing function calls and one in pipeline/non-pipeline expression distinction which combined led to exponential blowup when parsing nested function calls. For the particular example in #7866 this changes non-termination in a reasonable time into practically instant.

Avoid backtracking when parsing function call expressions

---

.github/workflows/e2e-tests.yml
e2e/playwright/snapshot-tests.spec.ts
src/components/ModelingMachineProvider.tsx

Now that snapshots are more reliable, using the `--last-failed` option actually returns an error when all tests pass.
I also refactored the timeout based on this: https://github.com/KittyCAD/modeling-app/pull/7956#discussion_r2248489307

Only update snapshots when there are failures

---

rust/kcl-lib/src/parsing/parser.rs

Fix cryptic error when keyword is used as an object key

---

Makefile
e2e/playwright/editor-tests.spec.ts

The test was trying to test if the signature helper modal pops up when the user presses comma in the code editor.

Fix signature helper editor tests

---

rust/kcl-lib/src/simulation_tests.rs

https://github.com/KittyCAD/engine/pull/3688 will change the output of this. We can re-enable this when it merges.

test: Ignore test until engine fix merges

---

rust/kcl-lib/src/docs/kcl_doc.rs
rust/kcl-lib/src/docs/mod.rs

Uses better default values for and explicit units for angle arguments.
Pulled out of https://github.com/KittyCAD/modeling-app/pull/7502

Use explicit units for angles in autocomplete

---

src/lib/desktop.ts

The local desktop app conflicts with the production app usage:
1. Launch  the production **Zoo Design Studio** (ZDS) and log into `zoo.dev`
2. Close the production ZDS
3. `$ make run-desktop` and log into `dev.zoo.dev`
4. Close the local ZDS
5. Launch  the production ZDS again
6. [Bug] Observe that you are logged out and it's defaulting to `dev.zoo.dev`
The production desktop app conflicts with local app development:
1. Set `$VITE_KITTYCAD_API_TOKEN` and `$ make run-desktop` to log into `dev.zoo.dev`
2. Close the local ZDS
3. Launch  the production ZDS and log into `zoo.dev`
4. Close the production ZDS
5. `$ make run-desktop` again
6. [Bug] Observe that `$VITE_KITTYCAD_API_TOKEN` is ignored an it's defaulting to `zoo.dev`
The local and production desktop apps have separate environment …

Fix conflict between local (debug) and production app settings

---

src/lib/desktop.ts

Amends https://github.com/KittyCAD/modeling-app/pull/8058 so that folks don't have their **Zoo Design Studio (Staging)** settings reset.

Preserve the original folder for settings in the staging app

---

e2e/playwright/testing-camera-movement.spec.ts

Updates https://github.com/KittyCAD/modeling-app/pull/7341 to improve the reliability of CI for tests like this: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/2796
Here are those tests running on this branch: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/results?search=testing-camera-movement&branch=test-desktop-camera&show=all

Switch camera movement tests to run on the desktop target

---

rust/kcl-lib/src/execution/fn_call.rs
rust/kcl-lib/tests/var_ref_in_own_def/ast.snap
rust/kcl-lib/tests/var_ref_in_own_def/execution_error.snap
rust/kcl-lib/tests/var_ref_in_own_def/input.kcl
rust/kcl-lib/tests/var_ref_in_own_def/unparsed.snap

```
foo(one(), x = two(), y = three())
```
Before, unlabeled args like `one()` would get executed after labeled arguments `two()` and `three()`. Execution order was:
1. `two()`
2. `three()`
3. `one()`
4. `foo`
This PR makes it in left-to-right order.
1. `foo`
2. `one()`
3. `two()`
4. `three()`
This is a breaking change due to things like #2728, but I don't think many KCL programs rely on the current behavior. I think it's worth it to change.

Fix unlabeled arg execution order

---

rust/kcl-error/src/source_range.rs
rust/kcl-lib/src/execution/cad_op.rs
rust/kcl-lib/src/execution/exec_ast.rs
rust/kcl-lib/src/execution/fn_call.rs
rust/kcl-lib/src/execution/types.rs
rust/kcl-lib/src/std/args.rs
rust/kcl-lib/src/std/array.rs
rust/kcl-lib/src/std/patterns.rs
rust/kcl-lib/tests/helix_ccw/ops.snap
rust/kcl-lib/tests/kw_fn_unlabeled_but_has_label/execution_error.snap
rust/kcl-lib/tests/kw_fn_unlabeled_but_has_label/ops.snap
rust/kcl-lib/tests/kw_fn_unlabeled_but_has_label/program_memory.snap

This is required for constraints/sketch 2.0 and can improve ergonomics of some other functions. Marked as experimental and (deliberately) undocumented (for now).

Allow multiple unlabelled arguments if the input arg is an array

---

docs/kcl-lang/settings/user.md
rust/Cargo.lock
rust/Cargo.toml
rust/ezpz/Cargo.toml
rust/justfile
rust/kcl-api/Cargo.toml
rust/kcl-lib/src/execution/mod.rs
rust/kcl-lib/src/execution/types.rs
rust/kcl-lib/src/lib.rs
rust/kcl-lib/src/lsp/kcl/custom_notifications.rs
rust/kcl-lib/src/settings/mod.rs
rust/kcl-lib/src/settings/types/mod.rs
rust/kcl-lib/src/settings/types/project.rs
rust/kcl-python-bindings/kcl.pyi
rust/kcl-python-bindings/pyproject.toml
rust/kcl-python-bindings/src/lib.rs
rust/kcl-python-bindings/tests/tests.py

so we can get rid of https://github.com/KittyCAD/text-to-cad/blob/079d2518cf0721c48cf8bcc80137d7018781a0b6/text_to_cad/routes.py#L68
removed duplicate UnitLength and fixes the default to mm and adds a bunch of tests for it

Expose allowed file types

---

src/components/MlEphantConversation.tsx
src/components/PromptCard.tsx

- Adds support for newlines in the prompt box with <kbd>Shift+Enter</kbd>
- Makes the past prompts' display with word wrapping and hyphenation, preserving newlines

Shift+Enter for line breaks, show them in the prompt outcome box

---

e2e/playwright/prompt-to-edit.spec.ts

This test is failing 90% of the time: https://test-analysis-bot.hawk-dinosaur.ts.net/projects/KittyCAD/modeling-app/tests/201?branch=wait-for-ttc-error
The rendering of KCL is irrelevant to this test.

Wait longer for the TTC error and remove extra steps

---

src/components/MlEphantConversation.tsx
src/components/ModelingSidebar/ModelingPanes/index.tsx
tailwind.config.js

- adds a popover to the TTC pane that gives some additional info on TTC being experimental and that conversation history memory is coming soon
- adds a welcome message with some prompting tips in the spirit of https://text-to-cad.zoo.dev/
- adds a tailwind utility for light-mode-only styling, which helped me finally start trying to address a styling problem I've had because our ML green color is very nice for text in dark mode but completely unreadable in light mode. I'm trying out making "Text-to-CAD" green in dark mode, and giving it a green underline in light mode instead.

Add an info popover for "conversation memory coming soon", add a welcome message with prompt tips

---

.github/ISSUE_TEMPLATE/release.md

This link wasn't working here: https://github.com/KittyCAD/modeling-app/issues/8223

Use full URL to fix README link

---

.github/workflows/update-staging.yml
vercel.json

https://github.com/KittyCAD/modeling-app/pull/8213 disabled the staging deployments, which we don't want.
Vercel insists on associating environments to branches so I'm going to create a new one for this purpose.
---
Contributes to https://github.com/KittyCAD/modeling-app/issues/8161

Created a dedicated branch for the Vercel staging environment

---

e2e/playwright/fixtures/fixtureSetup.ts
e2e/playwright/test-utils.ts
src/lib/constants.ts

We need to clear the `'playwright'` key from local storage after tests run to prevent them from impacting the production app sidebar layout. I also removed `PLAYWRIGHT_KEY` and `PLAYWRIGHT_TEST_DIR` which no longer seem to serve a purpose.
---
Relates to https://github.com/KittyCAD/modeling-app/issues/7453

Fix Playwright impacting app sidebar layout

---

e2e/playwright/text-to-cad-tests.spec.ts
package-lock.json

"a 2x4 lego" is now taking longer than a minute. For this test, the actual prompt is irrelevant as long as it works.

Use a faster prompt to test Text-to-CAD

---

src/components/CommandBar/CommandBarArgument.tsx
src/components/CommandBar/CommandBarVector3DInput.tsx
src/lib/commandTypes.ts

This PR adds a `vector3d` input type to the `CommandBar`. Instead of making users type arrays like [1, 0, 0], you get clear X/Y/Z fields for 3D vector input.
- Added 'vector3d' to command input types in `commandTypes.ts`
- New `CommandBarVector3DInput` component with number validation and keyboard nav
- Routed new input type in `CommandBarArgument.tsx`
- Better UX for 3D vectors - no `[,,]`
- Matches the rest of the CommandBar input patterns
[Follow-up PRs](https://github.com/KittyCAD/modeling-app/issues/8193) will hook up Pattern Circular 3D commands to use these fields.
Closes #8277

Add Vector3D Input Type to CommandBar

---

src/components/Explorer/FileExplorer.tsx
src/components/RouteProvider.tsx
src/lib/codeEditor.ts

Fixes #7686 by adding a guard against re-firing the full execution pipeline if we receive a "change" event from the file system watcher, but our in-memory codeManager already has the same code that is read off of disk.

Do not fire re-execution if the code read from disk matches codeManager

---

src/routes/Onboarding/BrowserOnboardingRoutes.tsx
src/routes/Onboarding/DesktopOnboardingRoutes.tsx

It's too early in the user journey to bring up the specifics of how credits are spent.

Remove credits details from onboarding

---

docs/kcl-lang/settings.md
rust/kcl-lib/src/execution/annotations.rs

Follow-up to #8286. Since `defaultAngleUnit` is a warning now, we should not suggest it to users.

Remove defaultAngleUnit from @settings() autocomplete

---

src/machines/sketchSolve/sketchSolveMode.ts

Why the exhaustive `switch` was needed
* With `spawn` is typed for any actors on this machine, TS can’t relate the key to the concrete actor logic/type.
* The exhaustive `switch` narrows `nameOfToolToSpawn` to a string literal in each branch so spawn is able to figure it out.
* The `default` case with `never` enforces exhaustiveness: adding a new tool breaks compilation until you handle it. HOWEVER this is still maintenance pain of having to add a new case to the switch statement when a new tool is added.
Why `SpawnToolActor` type fills the same role
`SpawnToolActor` fixes it by just informing spawn tool of the association between the `EquipTools` type and the machines in  `equipTools`.
Since `const spawn: SpawnToolActor = _spawn` is a type annotation, not a type assertion. The compiler …

Sketch 2.0 WIP: spawn tool types
